### ISSUE TITLE
URL SHORTENER

### ISSUE THREAD

**Issue by shruti-sen2004** [apu52/METAVERSE#1]
**Describe the project you want to add with tech stack**
It is a url shortener. It shortens the length of a any link.

**Expected behavior**
It should shorten a link. And when the given link is copied into the browser, you will be redirected to the website.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by apu52** [comment]
@shruti-sen2004 Welcome to Metaverse!!!!!!!!!🥳
Thanks For raising the Issue. 👍

**Comment by apu52** [comment]
@shruti-sen2004 Please do not make any type of PR until you are get assigned in any issue

**Comment by apu52** [comment]
@shruti-sen2004 Can you please give additional images or SS of the URL Shortener

**Comment by apu52** [comment]
& please mention the tech stack like what are the languages or  Databases you have used

**Comment by shruti-sen2004** [comment]
This was just for testing....no need to assign..........you have maintained your pr well...........all the best ..........keep it up
