### ISSUE TITLE
Add alarm clock website named Wakemeup

### ISSUE THREAD

**Issue by Mapur2** [apu52/METAVERSE#10]
**Describe the project you want to add with tech stack**

A website where we can set our alarms

**Comment by Mapur2** [comment]
Please assign me

**Comment by apu52** [comment]
@Mapur2 Welcome to Metaverse!!!!!!!!!🥳
Thanks For raising the Issue. 👍

**Comment by apu52** [comment]
Please follow contributing.md file for the contribution details
