### ISSUE TITLE
[Feature Request]: Content overflowing

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The cards in the kolhapur district crops project is overflowing i would like to fix it.

### Use Case

This would improve the website UI.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e432ec16-22b9-440a-b1bc-b793171654db)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@chaanakyaaM under which open source programme u are contributing??

**Comment by chaanakyaaM** [comment]
under GSSOC'24

**Comment by chaanakyaaM** [comment]
sorry for the mistake...

**Comment by apu52** [comment]
> sorry for the mistake...

no matter .it happens .i am assigning u
