### ISSUE TITLE
[Feature Request]: Add musical floor game

### ISSUE THREAD

**Issue by PDBharadwaj** [apu52/METAVERSE#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As the mouse hovers on various tiles on the window, it produce music. Alternatively, user can use keyboard keys as mentioned on the tiles to produce sound.

### Use Case

It is a game for recreational purposes.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@PDBharadwaj adding a project in this website/repo is not a valid contribution . please follow the rules mentioned in contributing.md file . Sorry to close this issue. but u can still make new issues .
