### ISSUE TITLE
[Feature Request]: Update Transit masters link

### ISSUE THREAD

**Issue by PDBharadwaj** [apu52/METAVERSE#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The transit-masters link is showing "404 error" when clicked. I want to update the url link.

### Use Case

Rectify the error in URL of transit-masters.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@PDBharadwaj u are assigned
