### ISSUE TITLE
[Feature Request]:  Newsletter Section Addition in food ordering website

### ISSUE THREAD

**Issue by Damini2004** [apu52/METAVERSE#1008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Newsletter Section Addition in food ordering website

### Use Case

Newsletter Section Addition in food ordering website

### Benefits

Newsletter Section Addition in food ordering website

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a4ab68d3-bc90-430a-acdd-c079481938b1)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Damini2004 I have assigned you this issue .but at first please try to complete previously assigned issue
