### ISSUE TITLE
[Feature Request]:  Menu Section hover enhacemnet in Food ordering website

### ISSUE THREAD

**Issue by Damini2004** [apu52/METAVERSE#1009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Menu Section hover enhacemnet in Food ordering website

### Use Case

Menu Section hover enhacemnet in Food ordering website

### Benefits

Menu Section hover enhacemnet in Food ordering website

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e168b7de-dd87-4820-a7c9-0b92ef8179e2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Damini2004 I have assigned u previously 2 issues. So please try to complete previous 2 issues at first & please don't raise more than 2 issues at a time. After completing previously assigned issues ping me here .Then I will assign u

**Comment by Damini2004** [comment]
@apu52 I have created the PR so review it,  kindly assign this issue to me.

**Comment by Damini2004** [comment]
@apu52 assign this issue to me.
