### ISSUE TITLE
[Feature Request]:  Button is not present in newsletter section 

### ISSUE THREAD

**Issue by Damini2004** [apu52/METAVERSE#1010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Button is not present in newsletter section 

### Use Case

Button is not present in newsletter section 

### Benefits

Button is not present in newsletter section 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e7825700-132f-4191-860a-67e26c9dccbe)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Damini2004 I really can't understand the issue ?? can u make it more clear 7 understandable

**Comment by Damini2004** [comment]
@apu52  Subscribe button is not present besides input field so its required to be present their.

**Comment by Damini2004** [comment]
Assign this issue to me. @apu52
