### ISSUE TITLE
[Feature Request]: make Faq section for TinDog website

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#1013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

a faq setion for the ewebsite

### Use Case

faq section for this website 

### Benefits

users can clear their doubts regarding to the website 

### Add ScreenShots

https://github.com/user-attachments/assets/12d2ce6b-8991-4d65-bd76-c8e4d4fbf030

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@heysagnik @apu52 please assign me this issue i wil complete all in time

**Comment by apu52** [comment]
@ANKeshri  I have assigned you this issue .but at first please try to complete previously assigned issue
