### ISSUE TITLE
[Feature Request]:  add real colour hover on the social icons of hostel management website 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add actual colour hover  on social icons 

### Use Case

improve ui 

### Benefits

loks good 

### Add ScreenShots

before : 

https://github.com/user-attachments/assets/4a89b1e0-24a3-4aac-9d7f-42ff3cc0f9d0

after : 

https://github.com/user-attachments/assets/077922b4-2251-4af3-bab8-0e85280728a9

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@heysagnik @apu52 please assign me this , i will surely complete all in time

**Comment by apu52** [comment]
@ANKeshri I have assigned u previously 2 issues. So please try to complete previous 2 issues at first & please don't raise more than 2 issues at a time. After completing previously assigned issues ping me here .Then I will assign u

**Comment by ANKeshri** [comment]
@a

> @ANKeshri I have assigned u previously 2 issues. So please try to complete previous 2 issues at first & please don't raise more than 2 issues at a time. After completing previously assigned issues ping me here .Then I will assign u

sure @apu52 from now i will raise max 2 issue

**Comment by ANKeshri** [comment]
@apu52 please assign me this issue
