### ISSUE TITLE
[Feature Request]: Adding new section of "Desserts" in "Food Website"

### ISSUE THREAD

**Issue by Maana-Ajmera** [apu52/METAVERSE#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a new section of desserts in food website

### Use Case

It would help in adding more options for the user , making it a good user-friendly site

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Maana-Ajmera I have assigned you this issue .but at first please try to complete previously assigned issue
