### ISSUE TITLE
[Feature Request]: Bayes Theorem Calculator

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [apu52/METAVERSE#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Calculator

### Use Case

Calculator

### Add ScreenShots

![Screenshot 2024-07-07 230510](https://github.com/user-attachments/assets/3c6809f2-fa91-43d5-9527-71dbb239aa39)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Ishitamukherjee2004 I can't get the point of this issue ?? can u please explain it so make it more relatable & more understandable

**Comment by Ishitamukherjee2004** [comment]
@apu52 The Bayes' Rule Calculator handles problems that can be solved using [Bayes' rule]. It computes the probability of one event, based on known probabilities of other events. And it generates an easy-to-understand report that describes the analysis step-by-step.

**Comment by siddharthbaleja7** [comment]
Can you please assign this issue to me?
