### ISSUE TITLE
[Bug]:  No navbar in Restaurant website

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [apu52/METAVERSE#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no navbar and and the nav sign is not working

### Expected behavior

There should be home, about etc in navbar

### Add ScreenShots

![Screenshot 2024-07-19 185932](https://github.com/user-attachments/assets/5bcd441b-813e-42f5-9888-23cbae444ddd)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Ishitamukherjee2004 I have assigned you .but from next time please don't raise more than 2 issues at a time . & also please try to complete the previously assigned issue at first

**Comment by Ishitamukherjee2004** [comment]
@apu52  Ok! Sorry for this.....I'll definitely remember

**Comment by apu52** [comment]
> @apu52 Ok! Sorry for this.....I'll definitely remember

No matter . Just try to follow the rules from next time .HAPPY CODING!!!!!!!!
