### ISSUE TITLE
[Feature Request]: Add hover effects

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add hover effects to the links on the footer and also change the background color to white for the text visibility which is in grey color.

### Use Case

This improves the UI and makes it more professional.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/03972313-65f1-4ee1-a8ac-a835060cc610)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@chaanakyaaM please follow the rules mentioned in CONTRIBTING.md . This issue is now in queue . At first try to complete previously assigned issues

**Comment by chaanakyaaM** [comment]
Would you kindly assign this issue to me, because I have completed the previous issue.

**Comment by apu52** [comment]
@chaanakyaaM I have assigned u this issue. But I think u also have 2 earlier issues mark as "PENDING" Do u want to work on those issues otherwise close those issues ASAP.

**Comment by chaanakyaaM** [comment]
Yes, I do want to work on those issues, but as per the guidelines im working on one issue at a time.
