### ISSUE TITLE
[Feature Request]: Add animation to barber website

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add animation to the barber website.

### Use Case

This improves overall Website UI.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1b852b86-f716-40d7-aa4a-8dbde4c6da21)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@chaanakyaaM please follow the rules mentioned in CONTRIBTING.md . This issue is now in queue . At first try to complete previously assigned issues
