### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by lovelymahor** [apu52/METAVERSE#1052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Our website currently lacks a newsletter subscription option in the footer. Adding this feature will help us engage with our audience and keep them updated with our latest news and offers.

Required Features:

Email input field
Subscribe button
Confirmation message

### Use Case

Adding a newsletter subscription feature enhances user engagement by allowing easy access for users to receive updates, promotions, and news, thereby increasing user interaction and retention.

### Benefits

Adding a newsletter subscription in the footer boosts user engagement, increases mailing list growth, and keeps users informed about updates and offers.

### Add ScreenShots

![Screenshot (252)](https://github.com/user-attachments/assets/9691d262-b294-4064-a22f-e590b4251a62)

Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@lovelymahor under which open source programme do u want to contribute??
GSSOC/SSOC??

**Comment by lovelymahor** [comment]
@apu52 I want to work on GSSOC

**Comment by apu52** [comment]
@lovelymahor u are assigned
