### ISSUE TITLE
[Feature Request]: Add logo in the Hackathons website 

### ISSUE THREAD

**Issue by Gultreen** [apu52/METAVERSE#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding a logo to a website helps in establishing and reinforcing the brand's identity. It provides a visual representation of the brand, making it easily recognizable to users.

### Use Case

A company’s website prominently displays its logo at the top-left corner of every page.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
#1035 on this same issue is already present in this repo . so sorry to close this issue . Thanks for raising this issue but sorry to close this issue .
HAPPY CODING!!!!!!!!
