### ISSUE TITLE
Add ChatBot

### ISSUE THREAD

**Issue by sreevidya-16** [apu52/METAVERSE#1055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add Chatbot to enhance user support

### Use Case

Enhances user support to the website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@sreevidya-16 this issue is not properly clear to me.....please explain it more so that I can understand it  more clearly ...
& under which open source programme do u want to contribute??

**Comment by sreevidya-16** [comment]
Adding a chatbot to the "Metaverse Front-End Playground" will enhance user interaction and support within our dynamic community.
The chatbot will serve as an interactive assistant, helping users navigate the platform, answering frequently asked questions, and providing real-time guidance on metaverse development. By integrating this feature, I aim to streamline user experience, faster engagement, and ensure that both newcomers and seasoned developers receive the support they need to innovate and collaborate effectively.

I'm participating in GSSOC'24 
Kindly assign me this issue, with appropriate label of the level

**Comment by apu52** [comment]
@sreevidya-16 thanks for explaining . I have assigned you . you can start working . All the best

**Comment by apu52** [comment]
& please don't call me sir , I am just a student

**Comment by sreevidya-16** [comment]
Ok, thanks 😊

**Comment by sreevidya-16** [comment]
> & please don't call me sir , I am just a student

Ok, sure
