### ISSUE TITLE
Code Editor Project

### ISSUE THREAD

**Issue by Geeks-Arpan** [apu52/METAVERSE#106]
Title: Code Editor Project

Tech Tools: Html ,Css and Js

Description:
A code editor is a software application that allows programmers to write and edit code. Code editors have features that help programmers write and edit code more efficiently. 

**Screenshots (optional)**

![Screenshot 2023-11-01 195727](https://github.com/apu52/METAVERSE/assets/99377659/11af4e2e-2e7d-44d5-9257-134d7df464a8)

**Additional context (Mandatory )**
- I am a contributor in OSEN open source programme

**Comment by apu52** [comment]
@Geeks-Arpan There is just a general query , If you have tried to create the code space environment as sublime text code editor?

**Comment by Geeks-Arpan** [comment]
@apu52 only three language html,css and js are present in this code editor?

**Comment by apu52** [comment]
> @apu52 only three language html,css and js are present in this code editor?

No , there are many languages in the code editor you can work on
