### ISSUE TITLE
[Feature Request]:  make a page for getting necessary details for booking an appointment 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#1066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 make a page for getting necessary details for booking an appointment 

### Use Case

getting necessary details for booking an appointment 

### Benefits

users can book appointment before hand 

### Add ScreenShots

https://github.com/user-attachments/assets/947380d3-11c2-410a-88a2-114375807c00

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@apu52 i have created pr for my earlier assigned issue so can you  please assign me this issue

**Comment by apu52** [comment]
@ANKeshri u are assigned
