### ISSUE TITLE
[Feature Request]: Make footer for the Inno Hub website 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#1067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

footer for innohub website 

### Use Case

it will contain social to conect and gives good look to website 

### Benefits

it will contain social to conect and gives good look to website 

### Add ScreenShots

https://github.com/user-attachments/assets/248c864f-9dcd-45a6-9a13-a8f32fbb1cb5

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ANKeshri please try to complete the previous assigned PR , then I will assign u this issue

**Comment by ANKeshri** [comment]
> @ANKeshri please try to complete the previous assigned PR , then I will assign u this issue

@apu52 i have completed all my assigned issue can you please assign me this
