### ISSUE TITLE
[Bug]: Scroll Down Progress Bar Not Working Properly

### ISSUE THREAD

**Issue by MastanSayyad** [apu52/METAVERSE#1069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @apu52 

The scroll-down progress bar on the website is not working properly, 
- The Bar completes even if the page is not scrolled up to the bottom 
- The scroll down progress bar does not match with the design theme (it should have disco light effect just like the other components)
- The size is not suitable according to the body content size

### Expected behavior

N/A

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4c451a39-445e-48eb-b4cb-e79a7f58528e)

https://github.com/user-attachments/assets/df9fc862-58df-43d7-9b44-447a04adc013

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@MastanSayyad in which open source programme u are contributing??

**Comment by MastanSayyad** [comment]
> @MastanSayyad in which open source programme u are contributing??

Sorry for the confusion, it is gssoc!
