### ISSUE TITLE
[Feature Request]:  Add functionality to Tinder Clone

### ISSUE THREAD

**Issue by abckhush** [apu52/METAVERSE#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Right now only a video is being played on the tinder-clone project. I would like to add functionality to:
1. Create Account
2. Learn
3. Safety 
4. Support

### Use Case

Will add functionality to the page.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/70d7c212-6a27-4509-ac1c-c81de351e931)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@abckhush I have assigned u .but at first please try to complete previously assigned issue
