### ISSUE TITLE
[Feature Request]: Add game Angry Birds

### ISSUE THREAD

**Issue by arunimaChintu** [apu52/METAVERSE#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This adds  all the required files for the project of Angry Bird game like index,styles,script,manifest, readme,... etc.

### Use Case

This will provide a clear code for the projects and include angry Bird as its projects...

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by arunimaChintu** [comment]
@apu52 Please assign me this issue!

**Comment by apu52** [comment]
@arunimaChintu Adding a project in this repo is not a valid contribution . Please try to follow the rules mentioned in CONTRIBUTING.md file before contributing. Sorry to close this issue . Nut u can still raise new issues on which u want to work on.
HAPPY CODING!!!!
