### ISSUE TITLE
[Feature Request]: Wanted to Add Sorting Visulaizer

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [apu52/METAVERSE#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. **Dropdown Menu**: Allow users to select from various sorting algorithms such as Bubble Sort, Selection Sort, Insertion Sort, Merge Sort, Quick Sort, and Heap Sort.
2. **Random Array**: Generate a random array of numbers.
3. **Speed Control**: Adjust the speed of the animation.
4. **Bars/Lines**: Represent array elements as vertical bars or lines of varying heights.
5. **Description Panel**: Display a brief description of the selected algorithm, including its time complexity and space complexity.

### Use Case

1. **Teaching Sorting Algorithms**: Visualizers are excellent for teaching how sorting algorithms work. They help students understand the step-by-step process and the inner workings of different algorithms.
2. **Demonstrating Algorithm Efficiency**: By visualizing the sorting process, students can see firsthand the efficiency differences between algorithms (e.g., O(n^2) vs. O(n log n)).
3. **Comparing Algorithms**: Researchers and developers can use visualizers to compare the performance of different sorting algorithms on various types of data.
4. **Hands-On Experience**: Interactive visualizers allow users to manipulate the array, step through the algorithm, and observe changes in real-time, enhancing understanding through active engagement.
5. **Self-Study**: Individuals learning algorithms on their own can use visualizers to better understand and practice sorting techniques

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Vaibhav-kesarwani  Adding a project in this repo is not a valid contribution . Please try to follow the rules mentioned in CONTRIBUTING.md file before contributing. Sorry to close this issue . Nut u can still raise new issues on which u want to work on.
HAPPY CODING!!!!
