### ISSUE TITLE
[Feature Request]:  Job place website Performance page reso

### ISSUE THREAD

**Issue by dhairyagothi** [apu52/METAVERSE#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

making performance page responsive

### Use Case

making page responsive

### Add ScreenShots

![Screenshot 2024-07-24 122553](https://github.com/user-attachments/assets/a77aed1a-5644-4986-be1e-ea468c846e8c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by dhairyagothi** [comment]
@apu52 please assign me

**Comment by apu52** [comment]
@dhairyagothi I have assigned u .but at first please try to complete previously assigned issue
