### ISSUE TITLE
[Feature Request]:  UI Enhancement of the Feedback Section

### ISSUE THREAD

**Issue by Damini2004** [apu52/METAVERSE#1092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

UI Enhancement of the Feedback Section

### Use Case

UI Enhancement of the Feedback Section

### Benefits

UI Enhancement of the Feedback Section

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b8ccaf3c-a808-4dc8-b932-1ee4a1e983b7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Damini2004 I have assigned u .but at first please try to complete previously assigned issue
