### ISSUE TITLE
[Feature Request]: Making Contact Section in Gamics Project

### ISSUE THREAD

**Issue by Maana-Ajmera** [apu52/METAVERSE#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently , contact is present in header but their is no contact page made

### Use Case

Users can share anything if they want to, it will help in better user experience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Maana-Ajmera** [comment]
@apu52 Please assign it to me

**Comment by apu52** [comment]
@Maana-Ajmera u are assigned .But At first please try to complete the previously assigned issue at first.

**Comment by Maana-Ajmera** [comment]
@apu52 Please review my PR and merge it
