### ISSUE TITLE
[Feature Request]: add faq for eduland website and real colour hover effect on social icons 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding faq section on eduland website

### Use Case

get t know more about the website and uses

### Benefits

get answers beforehand 

### Add ScreenShots

https://github.com/user-attachments/assets/1cb5646f-2b0a-4085-8a16-f4118a6f7fcc

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ANKeshri I have assigned u . but at first please try to complete please try to complete previously assigned issue
