### ISSUE TITLE
[Feature Request]:  Want to implement the navbar of the bootstrap project as original website and completing the copy to clipboard functionality 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [apu52/METAVERSE#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to implement the navbar on the bootstrap as original website
I want to complete the copy to clipboard functionlity to the project

### Use Case

It will looks more like the original one

### Add ScreenShots
![image](https://github.com/user-attachments/assets/29d3d772-745e-4d4a-a2f9-9d403b51e89f)
![image](https://github.com/user-attachments/assets/b375d3dd-a1cb-4d05-a79b-612093e1717d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Ayushmaanagarwal1211 u are assigned .but at first please try to complete previously assigned issue.

**Comment by Ayushmaanagarwal1211** [comment]
@apu52 yes yes actually i already created the page for amazon and raised a pr just now and now i am starting working on this 
#1110
