### ISSUE TITLE
[Bug]: Calculator is not working properly

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [apu52/METAVERSE#1106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we click 0036+06, instead of 42 it is given 36

### Expected behavior

The result should come 42.

### Add ScreenShots

https://github.com/user-attachments/assets/304007e1-41dc-4a50-9e91-a6a51e27ac4f

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Ishitamukherjee2004 u are assigned

**Comment by apu52** [comment]
@Ishitamukherjee2004 u are assigned .but at first please try to complete previously assigned issue.
