### ISSUE TITLE
[Feature Request]: Want to add the Fit Gym Website 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [apu52/METAVERSE#1113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the fitness website 
In this website their are many pages linked to each other and it is responsive for all screen sizes as well 

### Use Case

It will increase the number of projects as well as it will tell about gym 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/53fd604c-8554-4f3c-a339-67a361b847ad)
![image](https://github.com/user-attachments/assets/a4e4fb91-a915-405e-92f5-742a723abd59)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Ayushmaanagarwal1211 adding a new project is not a valid contribution in this repo . Sorry to close this issue . But u can still make other new issues on which u want to work on.

**Comment by Ayushmaanagarwal1211** [comment]
Sure No problem
