### ISSUE TITLE
[Feature Request]: Movie Recommendation App

### ISSUE THREAD

**Issue by Inferno2211** [apu52/METAVERSE#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Allows users to search for movies and get recommendations based on their preferences, and previously watched movies

- Will use APIs like TMDb for movie data

### Use Case

We can get personalized recommendation based on our taste and discover hidden gems

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Inferno2211 do u like to add a new project of Movie recommendation in this website??

**Comment by Inferno2211** [comment]
Yes, I would like to add a new project

**Comment by apu52** [comment]
@Inferno2211 actually adding a new project in this repo is not considered as a valid contribution .Sorry to close this issue . But u can still work on other issues .
