### ISSUE TITLE
[Feature Request]: Snake Game is Not working at all .

### ISSUE THREAD

**Issue by nishant0708** [apu52/METAVERSE#1122]
### Is there an existing issue for this?
And Its Not Snake Game when user clicks he want to feel that nostalgia of snake scoring points
- [X] I have searched the existing issues

### Feature Description

Currently Snake Game is Not Working I want to Fix That:
https://apu52.github.io/METAVERSE/Projects/Snakes_Game/

### Use Case

It will Enhance User Experience

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7292d064-2e1d-45e2-bb73-cfb930d6dc84)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by nishant0708** [comment]
hey @apu52  can i work on this.

**Comment by apu52** [comment]
@nishant0708 u are contributing under GSSOC right??

**Comment by nishant0708** [comment]
@apu52 yes
