### ISSUE TITLE
[Feature Request]: Add the latest logo of twitter on "Twitter Clone".

### ISSUE THREAD

**Issue by harsh02mishra** [apu52/METAVERSE#1125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The logo of the twitter clone replace with the latest logo.

### Use Case

The Website should be updated.

### Add ScreenShots

![logo3](https://github.com/user-attachments/assets/64534ce9-3385-457b-8d45-e92e397d4c6e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Praveeng029** [comment]
please assign me in this issue. please FAST

**Comment by apu52** [comment]
@harsh02mishra u are assigned . but please try to complete previously assigned issue at first.

**Comment by apu52** [comment]
> please assign me in this issue. please FAST

this issue is already assigned . So I would like to suggest u to raise new issues to get assigned,

**Comment by Praveeng029** [comment]
Mai iss issue ko solve Karu ? Ya nahi.

**Comment by Praveeng029** [comment]
Kya mujhe new issues create karke unpar work karna chahiye?

**Comment by apu52** [comment]
> Mai iss issue ko solve Karu ? Ya nahi.

nope. Its already completed . u can't work on this issue.

**Comment by apu52** [comment]
> Kya mujhe new issues create karke unpar work karna chahiye?

yess. always welcome .u can raise other new issues on which u want to work on.
