### ISSUE TITLE
[Feature Request]: Adding morse code Generator

### ISSUE THREAD

**Issue by Saipradyumnagoud** [apu52/METAVERSE#1126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding morse code Generator

### Use Case

Generates morse Code

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Saipradyumnagoud** [comment]
@apu52 Can you please Assign me soon

**Comment by apu52** [comment]
@Saipradyumnagoud do u want to add a new project as morse code generator??

**Comment by Saipradyumnagoud** [comment]
@apu52 yes I want to add as project

**Comment by apu52** [comment]
@Saipradyumnagoud actually adding a new project in this repo is not considered as a valid contribution .Sorry to close this issue . But u can still work on other issues .
