### ISSUE TITLE
[Feature Request]:  Animated gif Addition 

### ISSUE THREAD

**Issue by Damini2004** [apu52/METAVERSE#1131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Animated gif Addition 

### Use Case

Animated gif Addition 

### Benefits

Animated gif Addition 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/8b7b3b69-f324-4382-885a-6e2c18a40748)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Damini2004 in which project do u want to add the GIF effect??

**Comment by Damini2004** [comment]
@apu52 https://apu52.github.io/METAVERSE/Projects/SEO_WEBSITE/ this one

**Comment by apu52** [comment]
@Damini2004 I have merged this PR .But from next time please don't make any type of PR until u get assigned to any issue .

**Comment by Damini2004** [comment]
#1172 
Assign this to me sir.
