### ISSUE TITLE
[Feature Request]:  Tlit Effect to the Image

### ISSUE THREAD

**Issue by Damini2004** [apu52/METAVERSE#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Tlit Effect to the Image

### Use Case

Tlit Effect to the Image

### Benefits

Tlit Effect to the Image

### Add ScreenShots

![image](https://github.com/user-attachments/assets/3d5a895b-f876-4f2c-9b78-1ef03f9681ad)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Damini2004 I have assigned u this issue .But please from next time provide some more details about your issue like in which project do u want to add the animation...& why ?? how will be the users get the benefits  after u add this features to that project

**Comment by Damini2004** [comment]
@apu52 Sure sir.
