### ISSUE TITLE
[Feature Request]: Want to add a Google Search Engine Clone

### ISSUE THREAD

**Issue by zul132** [apu52/METAVERSE#1137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a new Front end project "Google Search Engine Clone" which would be an exact replica of the classic Google Search Homepage implemented using HTML, CSS and JavaScript. 
In addition to the Google UI, I also intend to implement the search functionality so that when a user tries to search for something in the search bar, it will redirect them to the actual Google search result.

### Use Case

My website will allow visitors to search for any topic, person, site or item they like and provide the corresponding Google results just like the actual Google Search Engine website. 
My plan is to make the UI design as close to the actual Google website's UI as possible down to the minute details like the shadows on the icons, which would greatly enhance the User experience.

### Benefits

I believe my proposed project is a good beginner friendly frontend project suitable for this repository. New web developers and members of the METAVERSE community who are just starting their HTML journey will surely find this project useful for learning HTML, CSS and JavaScript.
I would be sure to leave plenty of useful comments in the source code of my website that would be helpful for anyone in the community who wishes to learn from my project.

## This is what the Landing page would look like: 
![image](https://github.com/user-attachments/assets/b31971c0-7081-4cea-b8cb-e44978d0449e)

## Search Result would look something like this:
![image](https://github.com/user-attachments/assets/03eb8e34-e99c-4b58-94b3-03b82ba9e6a9)

Disclaimer: I just took these images from Google as a sample.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by zul132** [comment]
@apu52 Kindly assign me this issue under SSOC'24.

**Comment by apu52** [comment]
@zul132 actually adding a new project in this repo is not considered as a valid contribution .Sorry to close this issue . But u can still work on other issues .
