### ISSUE TITLE
Fixing the contributors section in readme file

### ISSUE THREAD

**Issue by shruti-sen2004** [apu52/METAVERSE#114]
**Describe the bug**
I want to fix some orientations in the contributors section in the readme file.

**Expected behavior**
It will look prettier.

**Screenshots**
Before:
![image](https://github.com/apu52/METAVERSE/assets/115914670/8be26307-42e9-4111-9308-b6b2d6cecc38)

After : 
![image](https://github.com/apu52/METAVERSE/assets/115914670/447e10d3-9ffb-498e-b05e-3733f53dfcfe)

**Additional context (Mandatory )**
 
- [ ] I am a contributor in OSEN open source programme

**Comment by apu52** [comment]
@shruti-sen2004 Welcome to METAVERSE!!!!!!!!
