### ISSUE TITLE
[Feature Request]: faq section for innohub website 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#1141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

faq section for inno hub website

### Use Case

users will get to know general solutions of their problems

### Benefits

users will get to know general solutions of their problems

### Add ScreenShots

https://github.com/user-attachments/assets/414ee54a-fac8-493c-9fa0-4b49fd28d7dc

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@apu52 please assign me this issue i have created pr for earlier assigned issues

**Comment by apu52** [comment]
@ANKeshri please upload the video properly...its still showing as loading...

**Comment by ANKeshri** [comment]
@apu52 i have added video please assign me it happened because of network issue sorry
