### ISSUE TITLE
[Documentation Update]:  Adding a backend file uploader project 

### ISSUE THREAD

**Issue by dhairyagothi** [apu52/METAVERSE#1146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

adding a backend file uploader project using node js

### Suggested Change

file uploader

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@dhairyagothi adding a project is not a valid contribution in this repo . Sorry to close this issue . But u can still make new issues
