### ISSUE TITLE
[alignment]:  In Food-Ordering-Website some heading text is not align properly.

### ISSUE THREAD

**Issue by Praveeng029** [apu52/METAVERSE#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Heading text is not align properly in FOOD_ORDERING_WEBSITE.
![Screenshot (114)](https://github.com/user-attachments/assets/07a471b7-600e-454a-b5fa-25f7236eb2c0)
![Screenshot (115)](https://github.com/user-attachments/assets/333e7343-534d-48d9-a4a3-d72f3d1250c2)

### Suggested Change

I want the text of this website to be well aligned, So that the UI & UX can be better.

![Screenshot (116)](https://github.com/user-attachments/assets/fe6e1ef8-cebd-4a3a-a58c-bf0d2949a3b6)
![Screenshot (117)](https://github.com/user-attachments/assets/9aa6fd5d-113d-4709-87e7-a9432db89729)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Praveeng029** [comment]
Please assign me in this issue.

**Comment by anuragverma108** [comment]
Assigned! @Praveeng029
