### ISSUE TITLE
Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [apu52/METAVERSE#1169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

### Use Case

It will Enhance User Experience 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@sailaja-adapa welcome to the repo . Can u please specify under which open source programme u are contributing???

**Comment by sailaja-adapa** [comment]
GSSOC'24
