### ISSUE TITLE
[Feature Request]: Making register form for Hostel Management project

### ISSUE THREAD

**Issue by Maana-Ajmera** [apu52/METAVERSE#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add register page in hostel management project , there is an option to register , but there is no page for registration

### Use Case

It would help new customers to join 

### Add ScreenShots

This is the login page , I want to make similar register page

![image](https://github.com/user-attachments/assets/7c133278-3e3a-487e-8d04-4bde8e301b70)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Maana-Ajmera** [comment]
@apu52 Please assign it to me

**Comment by apu52** [comment]
@Maana-Ajmera can u please double check it , I think the register page also exists in the website

**Comment by Maana-Ajmera** [comment]
yes sorry , it exists , I am closing this issue
