### ISSUE TITLE
[Feature Request]: Add "CLASH OF CLANS" Game

### ISSUE THREAD

**Issue by arunimaChintu** [apu52/METAVERSE#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Clash of Clans is a mobile strategy game where players build and upgrade their village, train troops, and attack other players to earn resources. The game's logic involves managing resources (gold, elixir, and dark elixir), constructing and upgrading buildings, and planning offensive and defensive strategies. Players join clans to participate in clan wars, donate troops, and collaborate on strategies. The game requires both real-time and long-term planning to succeed in both base-building and combat.

### Use Case

Base Building: Construct and upgrade various buildings, including defensive structures, resource collectors, and army camps.
Resource Management: Gather and manage gold, elixir, and dark elixir to fund upgrades and train troops.
Troop Training and Battles: Train a variety of troops and spells to attack other players' bases for resources and trophies.
Clan System: Join or create clans to participate in clan wars, donate troops, and engage in clan games for additional rewards.
Regular Updates: The game receives frequent updates introducing new troops, buildings, events, and game modes.

### Benefits

Troop Training and Battles: Train a variety of troops and spells to attack other players' bases for resources and trophies.
Clan System: Join or create clans to participate in clan wars, donate troops, and engage in clan games for additional rewards.
Regular Updates: The game receives frequent updates introducing new troops, buildings, events, and game modes.

### Add ScreenShots

<img width="298" alt="Screenshot 2024-07-31 at 9 50 53 PM" src="https://github.com/user-attachments/assets/e0145578-f325-4cf2-96b7-012589108364">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by arunimaChintu** [comment]
@apu52 Please assign me this issue

**Comment by apu52** [comment]
@arunimaChintu adding a project in this repo is not a valid contribution .So for that I can't assign u this issue . Sorry to close this issue .but u can still make new issues on which u want to work on.
