### ISSUE TITLE
[Feature Request]: Add random advice generator .

### ISSUE THREAD

**Issue by meetarora10** [apu52/METAVERSE#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a Random Advice Generator app which generates a random advice each time on click of the button .
Uses an api to generate a random advice .

### Use Case

This app will dynamically generate a random advice simply on click of the button and hence this project will add more functionalities to the website .

### Add ScreenShots

![Screenshot (522)](https://github.com/user-attachments/assets/47ccde90-a227-44fe-87b5-3d486e25d4ae)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
New Project are not allowed. You have to add features or solve bugs in the existing projects.
