### ISSUE TITLE
Digital Clock Project

### ISSUE THREAD

**Issue by Geeks-Arpan** [apu52/METAVERSE#118]
Title: Digital Clock

Tech Tools: Html, Css and Js

**Expected behavior**
A digital clock displays the time in numerals or other symbols, as opposed to an analog clock. Digital clocks can be found on watches, phones, or alarm clocks. They can display the time in both 12 and 24-hour formats. 

**Screenshots (mandatory)**
![Screenshot 2023-11-05 214924](https://github.com/apu52/METAVERSE/assets/99377659/8e4ae575-0945-4c55-ad8d-5820ce625faa)

**Additional context (Mandatory )**
- I am a contributor in OSEN open source programme

**Comment by Pooja1672** [comment]
Hi @Geeks-Arpan , I would like to work on this issue . Can you please assign it to me?

**Comment by Geeks-Arpan** [comment]
@apu52 pls assign me

**Comment by apu52** [comment]
@Pooja1672 Please try to make a new Issue on which project you want to work on
