### ISSUE TITLE
[Bug]: Position of toggle mode button is not proper .

### ISSUE THREAD

**Issue by meetarora10** [apu52/METAVERSE#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Position of toggle mode button is not proper . 
This button is visible only on scroll to the right and its position suddenly changes on click .

### Expected behavior

I can fix this issue by making the button visible on screen and fix its position so that the position does not changes on click of button .

### Add ScreenShots

https://github.com/user-attachments/assets/f8097d02-0a35-40f1-b852-7fac38ec391f

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@apu52 now kindly assign me this . I have completed one .

**Comment by apu52** [comment]
@meetarora10 u also have another assigned issue , please try to complete that at first .then I will assign u this issue.

**Comment by meetarora10** [comment]
@apu52 assign me now.
