### ISSUE TITLE
[Feature Request]: Add contact us page in the Travel Website .

### ISSUE THREAD

**Issue by meetarora10** [apu52/METAVERSE#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

No action takes place on click of the contact us button on the navbar .

### Use Case

I want to attach a contact us page with the website so that on click of the button contact page is displayed .

### Add ScreenShots

![Screenshot (968)](https://github.com/user-attachments/assets/47c82b48-3f2d-4d31-a78d-aca79546910d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by sachan13harshit** [comment]
@apu52 please assign this issue to me

**Comment by meetarora10** [comment]
@apu52 assign me now , I have completed previous.
