### ISSUE TITLE
Fix Navbar at top and make it responsive

### ISSUE THREAD

**Issue by Utsavladia** [apu52/METAVERSE#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Navbar should be fixed at top and should be responsive

### Expected behavior

![image](https://github.com/user-attachments/assets/4c4197fb-648e-407a-82f7-0ef7279faf16)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Utsavladia u are already assigned with 2 issues . Please try to complete previous 2 assigned issues . then just ping me here , I will assign u this issue.

**Comment by Utsavladia** [comment]
@apu52 
Sure I have completed and created PR for them.. now I can work on this one too.

**Comment by Utsavladia** [comment]
@apu52  
Kindly merge this PR before GSSOC ends 😌
