### ISSUE TITLE
Label issues

### ISSUE THREAD

**Issue by anusha7530** [apu52/METAVERSE#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Add issues of varying difficulty to the repo often. you must add the tag wob24, Level 1, Level2, Level 3 good first issue etc.
How we calculate the Scores on Leaderboard: Every PR one point
Level 1: 10 points
Level 2: 25 points
Level 3: 45 points

### Suggested Change

- Include documentation-related issues to provide an easier entry point for beginners to explore open-source.
- Even if you plan on solving an issue yourself, generate it to maintain the repository’s activity.
- Commit and contribute frequently to prevent the repo from becoming inactive.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@anusha7530 thanks a lot for informing me regarding the rules as well as the points system for the WOB'24 . I will try to maintain the rules throughout the programme
