### ISSUE TITLE
[Bug]: Social icons not visible in homepage

### ISSUE THREAD

**Issue by VijaySamant4368** [apu52/METAVERSE#1242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When user hovers over the social media icons in the homepage, they get fully covered.

### Expected behavior

The social media icons should be visible even when user hovers over them.

### Add ScreenShots

https://github.com/user-attachments/assets/a2641cf8-fcd0-4dc7-90a0-30cb4cdaa31c

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by sriraghavi22** [comment]
Hey i would like to work on this . Can you assign it to me?

**Comment by VijaySamant4368** [comment]
@apu52 please assign this issue to me as soon as u can.

**Comment by apu52** [comment]
@VijaySamant4368 u are assigned , u can start working on this issue
