### ISSUE TITLE
Feature Request : Missing Animation of Mouse hover on contributors page

### ISSUE THREAD

**Issue by Shariq2003** [apu52/METAVERSE#1243]
@sanjay-kv @Stiffpixels @OkenHaha @KeyurGK 
I am going to add the exact same animation of mouse hover on the page of contributors to match the page with the all pages and the theme of the website.

Please assign the issue to me.

https://github.com/user-attachments/assets/bf9b2922-8e2e-4f46-9e1a-6137e1d88dcb

**Comment by apu52** [comment]
@Shariq2003 I have assigned u the issue ...
But casn u tell me under which open source programme u are contributing??
GSSOC ext , WOB , hactoberfest???

**Comment by Shariq2003** [comment]
Gssoc

**Comment by apu52** [comment]
@Shariq2003 u are assigend

**Comment by Shariq2003** [comment]
Thanks sir, will try my best to deliver this asap

**Comment by Shariq2003** [comment]
@apu52 please review and merge this

**Comment by Shariq2003** [comment]
@apu52 sir, please review and merge my PR.
