### ISSUE TITLE
[Bug]: Navigation Bar Buttons Not Redirecting Correctly & Overlapping Issue on Scroll

### ISSUE THREAD

**Issue by Hamza20203064** [apu52/METAVERSE#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Issue 1**: Home Button Redirection Issue When navigating between different pages like About, Rate Us, or Contributor, the Home button fails to redirect the user back to the homepage. Althoug the page refreshes, it stays on the current page rather than returning to the home page as expected.

https://github.com/user-attachments/assets/eb629b51-d140-458d-80b5-0a7beb883536

**Issue 2:** Navigation Bar Text Overlap on Scroll The navigation bar has a transparent background, causing the text in the navigation bar to overlap with the content of the webpage when scrolling. This creates an undesirable visual experience.

### Expected behavior

For Issue1: The Home button should redirect the user to the homepage when clicked, no matter which page they are on.
For Issue 2: Update the background of the navigation bar to a translucent coloro avoid text overlap while maintaining the semi-transparent look.

### Add ScreenShots

![Screenshot 2024-10-01 234224](https://github.com/user-attachments/assets/ca402c97-f14a-4f43-acad-43d4b5633f8b)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Hamza20203064** [comment]
Assigned this issue to me under gssoc-extd, I would love to work on that.

**Comment by apu52** [comment]
@Hamza20203064 u are assigned

**Comment by Hamza20203064** [comment]
thankyou @apu52

**Comment by Hamza20203064** [comment]
@apu52 please check and merge the pull request
