### ISSUE TITLE
[Bug]: Change the Twitter icon to X Icon

### ISSUE THREAD

**Issue by Bhanuprakash842** [apu52/METAVERSE#1245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The twitter icon has changed to X icon .So, i want to change that.I can alspo add some of the other icons if required.I would be grateful if you assign me this issue under **Gssoc-ext, hacktoberfest** .My Github Id is @Bhanuprakash842

### Expected behavior

The change in all the twitter icons to the X icons in the website

### Add ScreenShots

![Screenshot 2024-10-02 003819](https://github.com/user-attachments/assets/a4c552ea-1c10-4644-9314-0c18439487b2)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by devarsheecodess** [comment]
Please assign this to me with gssoc-extd label. i can do this for you

**Comment by Arsomuu** [comment]
Assign this task to me !!!

**Comment by tanishirai** [comment]
@Bhanuprakash842 I would like to work on this issue

**Comment by Piyushsahu99** [comment]
I am eager to work on this project can you pls assign it to me.

**Comment by SonalTripathi21** [comment]
Please assign this task to me .

**Comment by Piyushsahu99** [comment]
Sure

**Comment by apu52** [comment]
@Bhanuprakash842 u are assigned
