### ISSUE TITLE
[Bug]: No submission indication of Rating in Rate us page

### ISSUE THREAD

**Issue by Rounit-1st** [apu52/METAVERSE#1247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i submit a rating there is no indication .  
I mean this

https://github.com/user-attachments/assets/bdaad86f-3304-4d3b-ae9a-ceba3b2aaeab

### Expected behavior

I want to fix it and make it like this 

![image](https://github.com/user-attachments/assets/17a0baf2-bb9b-41eb-bf9d-cdb132595ca6)

Not this crappy but better than above

Also making emoji pop out more when user click on it

Also please add the tag gssoc-ext and hacktoberfest in it

### Add ScreenShots

![image](https://github.com/user-attachments/assets/17a0baf2-bb9b-41eb-bf9d-cdb132595ca6)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Rounit-1st u are assigned
