### ISSUE TITLE
[Feature Request]: make the contact us page better

### ISSUE THREAD

**Issue by snehaapratap** [apu52/METAVERSE#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to see the contact page redesigned to improve user experience by organizing sections more clearly and using a more intuitive layout. Making the team member cards more readable, clearer input fields, and accessible fonts would enhance readability and ease of use. This change would make it easier for users to reach out and find necessary information quickly.

### Use Case

A user visiting the contact page should easily locate contact options, such as phone, email, or live chat, without confusion. This would reduce frustration when looking for support, ensuring a smoother interaction with the platform. It's particularly helpful for new visitors who may not be familiar with the interface.

### Benefits

This feature would improve user satisfaction, resulting in higher engagement and fewer support requests due to better clarity. It enhances accessibility, making it usable for a wider audience, including those with disabilities. Overall, it strengthens the platform's professionalism and usability for all visitors.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4951fce1-4755-488a-86c7-aff07b5fa685)
![image](https://github.com/user-attachments/assets/4adc1c0b-8304-4ffc-8aa8-3477acd40033)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by subikshabamboo** [comment]
Can you assign me this issue

**Comment by ABD018** [comment]
I want to work on this issue. Please assign it to me under gssoc-extd and hacktoberfest

**Comment by apu52** [comment]
@snehaapratap u are assigned . just want to request you one thing try to maintain the theme of the project in the contact us page also on comparison with other website pages
