### ISSUE TITLE
[Feature Request]: Add Planet Defense

### ISSUE THREAD

**Issue by pavitraag** [apu52/METAVERSE#1249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Planet Earth needs to be protected.
There is a gun with planet.
Gun is used to attack stones or meteroids hitting the planet.
Score increases if you hit the meteroids.
Game ends if any one touches the earth.

### Use Case

Stones come from all directions that is 360 degrees.
Gun can rotate 360 degree to hit the stone.
To hit with gun just press to hit the stones.
The stones are of different size and can be alone or with many.
Game can also be started again if you want.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@pavitraag Can u please mention the tech stack of the project u want to add??
As I think from the description that it's a web 1 or web 2 based project

**Comment by pavitraag** [comment]
tech stack is html,css and javascript

**Comment by apu52** [comment]
> tech stack is html,css and javascript

Then sorry i can't assign u the issue . As of now this repo is accepting just web3 based projects as new project , but u can still make contributions in this repo on web2 projects also . Please go through the CONTRIBUTING.md file for all of the details . sorry to close this issue for now . But eager to see more of your farther issues
