### ISSUE TITLE
[Feature Request]: Nav Bar Asymmetrical and Better Footer

### ISSUE THREAD

**Issue by NishantRana07** [apu52/METAVERSE#1252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Better Footer with socials can be added and I can implement

Nav bar can be fixed 

![Uploading Screenshot 2024-10-05 094341.png…]()

### Use Case

Can make it very interactive and improve User experience 

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@NishantRana07 please describe properly that what are the proper changes u want to add with description & proper SS/prototypes

**Comment by NishantRana07** [comment]
A good footer with social links can be implemented

**Comment by NishantRana07** [comment]
Also there is a big in na bar

**Comment by apu52** [comment]
can u give me some idea like how u will design the navabar & the footer (maybe any type of description or ss if u want to share)
