### ISSUE TITLE
[Feature Request]: fixing UI of Rate Us page

### ISSUE THREAD

**Issue by trahulprabhu38** [apu52/METAVERSE#1253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the UI of this page is can be improved and the backend functionality can be added.
Please assign me this so i can fix this @apu52 

### Add ScreenShots

<img width="1461" alt="Screenshot 2024-10-05 at 8 24 09 PM" src="https://github.com/user-attachments/assets/4a7cf1dd-05a6-4c12-bf20-f6e756291c03">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@T-Rahul-prabhu-38 u are assigned

**Comment by T-Rahul-prabhu-38** [comment]
@apu52 can you please review this , i have one more PR to make.
