### ISSUE TITLE
[Feature Request]: Smash Monty Mole game using html, css, js

### ISSUE THREAD

**Issue by rugved0102** [apu52/METAVERSE#1255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The game involves clicking on randomly appearing moles to score points while avoiding randomly appearing piranha plants, as clicking on a plant ends the game. Moles and plants appear at random intervals on a 3x3 grid, and the score updates dynamically based on player actions.

### Use Case

A simple game for entertainment and will be helpful for beginners as it is easy to build.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b8bcf46f-eacb-4548-b93c-2d6c5e20cedf)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by rugved0102** [comment]
can you please assign me the issue ?

**Comment by apu52** [comment]
@rugved0102 actually this repo is not accepting any type of web 2 or web 1 type of projects now . Only web 3 based projects are accepted as a valid contribution . Please go through the CONTRIBUTING.md file for more details of the cpntribution.
Sorry to close this issue for now .
But u can still make new issues on which u want to work on
