### ISSUE TITLE
[Feature Request]: update social media icon

### ISSUE THREAD

**Issue by Antima2004** [apu52/METAVERSE#1256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the footer section there are social media icon but the twitter logo is not updated 

Please assign this to me and also add label

### Use Case

This will help the website user experience 

### Add ScreenShots

Here's the image of it:
![Screenshot_2024-10-07-15-49-46-16_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/0689165e-1026-4b8c-8179-1865dc218d21)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Harish5232** [comment]
Can you please assign me this issue ?

**Comment by Antima2004** [comment]
@Harish5232 assign me this issue so that i can make changes

**Comment by Antima2004** [comment]
@apu52 please assign this to me so taht i can start working.

**Comment by apu52** [comment]
#1245 is already present there on the same issue . so sorry i cant assign you this issue for now. But u can still make new issues on which u want to work on

**Comment by Antima2004** [comment]
Ok thanks
