### ISSUE TITLE
[Bug]: Bug in Contributors page 

### ISSUE THREAD

**Issue by Abhi9shinde** [apu52/METAVERSE#1257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Issue with contributors page is that it doesn't do anything when clicked "HOME" in the navbar

### Expected behavior

After clicking navbar it should eventually to go the home page but it stays as it is.
Please give this a tag of hactoberfest, gssoc-ext, level 1

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
#1244 already present there on the same issue . Sorry to close this issue for now . But u can still make new issue on which u want to work on
