### ISSUE TITLE
[Bug]: Input field placeholder text is not visible

### ISSUE THREAD

**Issue by neeru24** [apu52/METAVERSE#1258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi there,

I was exploring the project and appreciate the work done so far.

I would like to propose the change in the styling of the placeholder in the "subscribe to our newsletter" on homepage.

The color of the placeholder text is not visible like what's written in it.

### Expected behavior

I would like to change the styling so that it looks consistent on the input field.

Kindly assign me this issue.

Thanks :)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/716e5cac-d723-4ff0-9dd5-f3d0301ea683)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@neeru24 u are assigned
