### ISSUE TITLE
[Feature Request]: I would like to update the about page

### ISSUE THREAD

**Issue by eshaalal** [apu52/METAVERSE#1259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Features I will be adding :
1. GSAP Animation 
2. ScrollTrigger

### Use Case

It will improve the User Experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by eshaalal** [comment]
@apu52 please assign me this task with gssoc-ext, level 3 label

**Comment by apu52** [comment]
@eshaalal u are assigned

**Comment by eshaalal** [comment]
@apu52 do assign me the level as well

**Comment by apu52** [comment]
> @apu52 do assign me the level as well

I will add the appropriate labels as per the review of the pr
