### ISSUE TITLE
To adding the animation effect to social media icons

### ISSUE THREAD

**Issue by Sujal1201** [apu52/METAVERSE#1260]
Issue: animation effect to social media icons

**screen recording**

https://github.com/user-attachments/assets/9d2f87c1-be82-47aa-925b-2bbf2a59bf0d

**Comment by Sujal1201** [comment]
please assign me for this issue

**Comment by apu52** [comment]
@Sujal1201 I didn't got your point , Can u please explain the issue properly???

**Comment by Sujal1201** [comment]
More attractive Hover effect with animation

**Comment by Sujal1201** [comment]
i will add hover effects to social icons

**Comment by apu52** [comment]
@Sujal1201 i think the issue on this adding hover animation to the social icons is already assigned on this repo. sorry I can't assign you this issue right now . but u can still make new issues on which u want to work on . sorry to close this issue
