### ISSUE TITLE
[Bug]: Previous and Next Button in home page

### ISSUE THREAD

**Issue by shretimag** [apu52/METAVERSE#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="1657" alt="Screenshot 2024-10-09 at 10 50 43 PM" src="https://github.com/user-attachments/assets/3fd3bd25-57a0-48bf-b844-b0db89a0f278">

### Expected behavior

These privous and next buttons on the home page are confusing. i would like to remove these

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by SonalTripathi21** [comment]
Assign me for this task.

**Comment by apu52** [comment]
@shretimag actually there are many projects already listed in the website , but for some issue the projects are not showing up in the website actually for that The buttons are present there , don't remove them as they are necessary 
So sorry to close this issue ,
But u can raise a new issue to retrieve the project list in the main website 
U can take reference from previous PR's
