### ISSUE TITLE
[Documentation Update]: the browse podcast button is not placed correctly in the spotify clone project

### ISSUE THREAD

**Issue by Harish5232** [apu52/METAVERSE#1262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

to update the existing CSS to bring the button inside the backdrop

### Suggested Change

by changing the dimensions of the backgroung present and positioning the button by changing its dispaly property

### Rationale

it will make sure the front end of clone  looks the same as the spotify aplplication

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Harish5232** [comment]
can you please assign me this issue ?

**Comment by apu52** [comment]
@Harish5232 u are assigned

**Comment by Aditya-PS-05** [comment]
Can you assign me this project?
