### ISSUE TITLE
[Bug]: Navbar routes are not working

### ISSUE THREAD

**Issue by Bhum-ika** [apu52/METAVERSE#1263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The routes are not functioning properly, and the address is not updating in the address bar.

### Expected behavior

When a user clicks on them, they should take user to that page

### Add ScreenShots

https://github.com/user-attachments/assets/0910dcc4-90f7-4d2f-85eb-b900f0553015

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ambarmishraa** [comment]
Assign me this task, i will do it asap!

**Comment by apu52** [comment]
@Bhum-ika u are assigned
