### ISSUE TITLE
[Feature Request]: SEO Optimization

### ISSUE THREAD

**Issue by snehas-05** [apu52/METAVERSE#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To improve search engine ranking and visibility, the website should include key SEO elements like:

Title: A clear and concise title that summarizes the site's content (visible on browser tabs and search results).

Meta Description: A 150–160-character description that explains the purpose of the site. This is what appears below the title in search results and influences click-through rates.

Keywords: Relevant search terms that describe the main topics of the site (e.g., "metaverse, virtual reality, augmented reality").

Author: Specify the author to give ownership and trustworthiness.

Viewport Meta Tag: This tag ensures the site is responsive on mobile devices.

### Use Case

Use Case: How SEO Optimization Enhances My Use of the Project

SEO optimization, through proper metadata (title, description, keywords), improves the website's visibility on search engines. This enhancement would:

Increase Organic Traffic: More users can find the site through relevant search queries related to "metaverse," driving natural traffic.
Improve User Engagement: A compelling meta description encourages more clicks from search results.
Higher Ranking: Good SEO leads to better search engine ranking, making the project more accessible to users searching for metaverse-related content.

### Benefits

Proper metadata helps search engines understand the site’s content, improves ranking, and drives traffic to the site.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Harish5232** [comment]
can you please assign me this issue ?

**Comment by apu52** [comment]
@snehas-05 u are assigned
