### ISSUE TITLE
[Bug]: Enhancing the ui design of the contributors page.

### ISSUE THREAD

**Issue by tarunkumar2005** [apu52/METAVERSE#1265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Enhancing the ui design of the contributors page.

### Expected behavior

More good contributors page in place of just images and all i will make it super awersome and stylish according to the ui.

### Add ScreenShots

@apu52 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@tarunkumar2005 u are assigned
