### ISSUE TITLE
[Bug]: Uniform Navbar in "Rate us" Page.

### ISSUE THREAD

**Issue by ahmarcode** [apu52/METAVERSE#1266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Navbar in "Rate us" page is different than that of the rest of the pages. Making it same as others will make pages look uniform

### Expected behavior

The navbar should have been same as the rest of the pages.

### Add ScreenShots

Rate us Page:
![image](https://github.com/user-attachments/assets/bb70d45f-545a-434f-8dc4-0cbeafb79443)

Other Pages (ALL): 
![image](https://github.com/user-attachments/assets/b77ecbab-95f9-4e48-8872-87af11d6e5c5)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ahmarcode** [comment]
Assign this "bug" to me please.

**Comment by apu52** [comment]
#1253 is already present there on the same issue . Sorry to close this issue for now , But u can still make new issues on which u want to work on
