### ISSUE TITLE
Improve About Us Page Animation and Make Navbar Sticky

### ISSUE THREAD

**Issue by AnushkaChouhan25** [apu52/METAVERSE#1268]
![image](https://github.com/user-attachments/assets/7cef08eb-0c47-4e3f-91d4-5fc00a0971d8)

Propose changing the animation of the "About Us" page content to prevent it from going out of the box and making the navbar sticky to ensure it remains visible while scrolling down the page.
 
Please assign this issue to me under gssoc-ext, hacktoberfest, and a suitable level label i would like to contribute into it.

**Comment by apu52** [comment]
@AnushkaChouhan25 #1244  is already present there on the same issue . Sorry to close this issue for now , But u can still make new issues on which u want to work on
