### ISSUE TITLE
[Bug]: hamburger is not working in small screen 

### ISSUE THREAD

**Issue by srishti023** [apu52/METAVERSE#1269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/user-attachments/assets/fcfc3b9c-1a2b-4efe-a57e-9fabe7345988

The hamburger is not working in small screen sizes it affects the User Experience.

### Expected behavior

The menu should dropped down when hamburger is clicked . 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@srishti023 u are assigned

**Comment by srishti023** [comment]
Please merge my PR
