### ISSUE TITLE
[Feature Request]: adding page translator to the footer

### ISSUE THREAD

**Issue by nandani-goyal** [apu52/METAVERSE#1271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the existing footer of the netflix clone project is quite different from the official netflix site.
the footer lacks the page translator button in the footer. Kindly assign me this issue @apu52 so that I can enhance the footer and it look exactly the way it is in the official website.

### Use Case

adding translator can make it more user friendly

### Add ScreenShots

![Screenshot 2024-10-13 010020](https://github.com/user-attachments/assets/1e131c4e-4eb8-4935-ac94-2edbf08329f5)
this is the actual footer of the official website
![Screenshot 2024-10-13 010007](https://github.com/user-attachments/assets/adaf845c-bd57-4666-824c-015c33b7d909)
the netflix clone project footer

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@nandani-goyal u are assigned
