### ISSUE TITLE
[Feature Request]:  Creating signup and login

### ISSUE THREAD

**Issue by trahulprabhu38** [apu52/METAVERSE#1272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

ill add a login and signup which will also store the user details. @apu52 can you please assign me this task.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@T-Rahul-prabhu-38 u are assigned , But u have already been assigned 1 issue beforehand , so please try to complete the issues separately one by one

**Comment by T-Rahul-prabhu-38** [comment]
i have made the PR. can you please review that.

**Comment by T-Rahul-prabhu-38** [comment]
> i have made the PR. can you please review that.

@apu52 
issue #1282 solved. please review this. thank you.
