### ISSUE TITLE
Update feedback form UI

### ISSUE THREAD

**Issue by NK-Works** [apu52/METAVERSE#1276]
![image](https://github.com/user-attachments/assets/e06106d3-63b7-40a9-9ec6-e3b92b8c806d)
The feedback form doesnt look good i can make it better

**Comment by NK-Works** [comment]
Also I will make the UI aligned with the website....

**Comment by apu52** [comment]
#1253 is already present there on the same issue @NK-Works , Sorry but I can't assign u this issue . But u can still make new issues on which u want to work on . Sorry to close this issue . But really eager to see your new issue
