### ISSUE TITLE
[ADD]: Event Countdown Timer

### ISSUE THREAD

**Issue by adwityac** [apu52/METAVERSE#1283]
**The name of the WEB 3 project you want to add:**
Event Countdown Timer

**Describe the WEB 3project you want to add:**
The Event Countdown Timer is a web application designed to help users keep track of upcoming events by providing a visual countdown. Users can input the name and date of an event, and the timer will display the time remaining until the event occurs.

Features:
Event Input: Users can enter the event name and select the date and time.
Real-Time Countdown: The timer updates every second to show the remaining days, hours, minutes, and seconds until the event starts.
User-Friendly Interface: A simple and intuitive design makes it easy for anyone to use.
Alerts: Users receive a notification when the countdown reaches zero, indicating that the event has started.

**Tech Stack of the project:**
Technologies Used:
HTML: For the structure of the webpage.
CSS: For styling and layout.
JavaScript: For countdown functionality and dynamic updates.

**Screenshots /Videos(Mandatory)**

![Screenshot 2024-10-16 225359](https://github.com/user-attachments/assets/292a129b-ab7e-4593-8aa2-e3e9298cc272)

**Additional context(Mandatory)**

- [✅] I have read the Contributing Guidelines *
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [✅] I'm a GSSOC'24 Extended contributor
- [ ] I'm a Hacktoberfest'24 Extended contributor
- [✅] I have starred the repository *

**Comment by apu52** [comment]
@adwityac basically as I have already mentioned in the contributing.md file also that this repo is just accepting the WEB3 projects only(maybe based on blockchain , selenium , polygon ,eth , solana) but this project is based on web2 or web1 ...
But sorry to close this issue as this will not be a valid contribution for our repo
But u can still make new issues on which u want to work on

**Comment by adwityac** [comment]
okay got it
