### ISSUE TITLE
[Bug]: In footer social media icons are not synchronized for hovering effect

### ISSUE THREAD

**Issue by Suvadip-sana** [apu52/METAVERSE#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In footer social media icons hover effect are not applied properly. Also for Github, the hover effect is not applying

### Expected behavior

This icons hover effect should be synchronized in nature.  

### Add ScreenShots/Videos

https://github.com/user-attachments/assets/87d00977-3dbc-49b8-ba69-d3b253d4e4df

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Suvadip-sana #1242 is already present in this repo on same topic  & already assigned , So sorry  i can't assign u this issue . But u can still make new issues on which u want to work on
