### ISSUE TITLE
Enhance

### ISSUE THREAD

**Issue by shubhagarwal1** [apu52/METAVERSE#1294]
As the navbar is not visible which makes a bad UI/UX
<img width="1352" alt="Screenshot 2024-10-18 at 4 29 41 PM" src="https://github.com/user-attachments/assets/b4b85532-b92b-49fd-8829-dd827b65a2a0">
Hey @apu52 please assign me this task

**Comment by apu52** [comment]
@shubhagarwal1 Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.

Sorry to close this issue for now .
