### ISSUE TITLE
[Documentation Update]: Spelling Error in About session of the project 

### ISSUE THREAD

**Issue by Jaytailor15** [apu52/METAVERSE#1298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Hello Team,
@sanjay-kv 
@apu52 

I noticed that the spelling of "Hactoberfest'24" in the About section of our project is incorrect. It should be "Hacktoberfest'24" to ensure accuracy and maintain professionalism in our documentation.

Thank you for your attention to this detail!

### Suggested Change

Correct the spelling of "Hactoberfest'24" to "Hacktoberfest'24" in the About section of the project documentation. This change will enhance the professionalism and clarity of our repository, ensuring that we accurately represent the event and maintain consistency throughout our materials.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Jaytailor15 u are assigned . But please just one request don't tag Sanjay sir unnecessarily as he is the program manger , it may be disturbing his work
