### ISSUE TITLE
[Feature Request]: Adding Commuinty Forums section

### ISSUE THREAD

**Issue by shivenyadavs** [apu52/METAVERSE#1300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This will allow user to give feedback based on the usage.

### Use Case

This will increase the number of users on the website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by shivenyadavs** [comment]
@apu52 please check here also

**Comment by apu52** [comment]
@shivenyadavs can u please provide me more ideas about the Community forums which u want to add
