### ISSUE TITLE
[enhancement]: Add light mode and dark mode toggle 

### ISSUE THREAD

**Issue by faiz66388** [apu52/METAVERSE#1304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A light and dark mode toggle would provide users with the flexibility to switch between themes based on their preference or environment. This enhancement could be implemented as a simple toggle button in the user interface, allowing users to quickly switch between light and dark modes. The application should also store the user’s preference and apply it automatically upon subsequent visits.

### Use Case

This feature would be particularly useful in scenarios where users are working in different lighting conditions. For instance, a user may prefer dark mode during nighttime or low-light settings to reduce eye strain, while others may prefer light mode during the day. It provides greater accessibility and a personalized user experience.

### Benefits

Enhanced User Experience: Offering a choice between light and dark themes caters to users' preferences, improving comfort and usability.
Accessibility: Reducing eye strain in low-light environments makes the platform more accessible to a broader audience.
Modern Aesthetic: A theme toggle is now a common and expected feature in modern applications, bringing the project in line with current design trends.
User Retention: The ability to customize the interface according to user preference encourages longer engagement with the platform.

### Add ScreenShots/Videos

![Screenshot 2024-10-20 204324](https://github.com/user-attachments/assets/7884b211-cbfd-404a-953a-f53d504f3efc)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by faiz66388** [comment]
Could you also please add the labels?

**Comment by apu52** [comment]
> Could you also please add the labels?

@faiz66388 I will add the appropriate labels as per the review of the pr
