### ISSUE TITLE
[Documentation Update]: Update code_of_conduct file

### ISSUE THREAD

**Issue by Nikhil0-3** [apu52/METAVERSE#1306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

It does not contain following sections 

How to contribute (fix bugs, add features)
Steps for submitting changes
Project setup instructions
Rules for code style
Code of conduct for respectful behavior
Enhance the project structure
Add the help and support section
Add the pull request section
Add issue report process section

### Suggested Change

Wanted to do the following changes :-

How to contribute (fix bugs, add features)
Steps for submitting changes
Project setup instructions
Rules for code style
Code of conduct for respectful behavior
Enhance the project structure
Add the help and support section
Add the pull request section
Add issue report process section

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Nikhil0-3 for the "How to contribute (fix bugs, add features)
Steps for submitting changes" section CONTRIBUTING.md file is already present there . so don't make any type of changes in the code_of_conduct.md files regarding that , just try to make the other changes u have proposed in that file
I have assigned you
