### ISSUE TITLE
[Feature Request]: Adding feedback form

### ISSUE THREAD

**Issue by TBorundia** [apu52/METAVERSE#1312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@TBorundia this project already has the feedback form section & also has the rating system section , so I think this issue is not appropriate . Thanks for raising the issue but u can still make new issues on which u want to work on.
