### ISSUE TITLE
[Bug]: textArea is not cleared after submitting feedback

### ISSUE THREAD

**Issue by Amnyadav** [apu52/METAVERSE#1315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

whenever user submits a feedback the textarea is remains as it is .
it should be empty after successfully submiting the feedback.

![Screenshot 2024-10-23 195222](https://github.com/user-attachments/assets/9e4df09d-e6ac-4d38-bf62-0b0bfc005a51)

### Expected behavior

text field should be empty after submitting the feedback

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Amnyadav  this issue is already present in the repo previously & already been assigned to another contributor . sorry to close this issue . but u can still make new issues on which u want to work on
