### ISSUE TITLE
[Feature Request]: New Designed Logo instead of Rocket Emoji

### ISSUE THREAD

**Issue by iamsaura8h** [apu52/METAVERSE#1321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

hey @apu52 , 
Currently, the app lacks a distinct logo that reflects its branding so As a UI/UX designer and front-end developer, I propose to Design and implement a new logo that aligns with the app's theme and improves branding.

![image](https://github.com/user-attachments/assets/b2cbf7f7-d259-435d-8794-81e075a679f3)

Please assign this issue to me with the `hacktoberfest-accepted` and `gssoc-ext` labels.

### Use Case

This would be beneficial to the app's branding and intent.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by harith-hacky03** [comment]
Can you assign me under hacktoberfest?
