### ISSUE TITLE
[Feature Request]: UI enhanced submit button

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [apu52/METAVERSE#1327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

in Rate us page the Submit button should be implement more styled to enhanced this feedback from

### Use Case

for attention grab

### Benefits

it's make the user good experience

### Add ScreenShots/Videos

![WhatsApp Image 2024-10-26 at 22 26 24_57e407f9](https://github.com/user-attachments/assets/382e64f0-750e-4173-ad7a-78540604c141)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by harith-hacky03** [comment]
I'm eager to work on it. Can you assign me please?

**Comment by apu52** [comment]
@biswajit-sarkar-007 I have assigned u 2 issues . try to make separate PR's according to the issues
