### ISSUE TITLE
[Feature Request]: Improve Navbar UI of Rate us page

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [apu52/METAVERSE#1328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

in Rate us page i want to improve the Navbar its not so much good as compare it your other's page Navbar i want to improve this UI 

### Use Case

it's give your viewers a god experience 

### Benefits

it's make your rate us page more reliable to other's page

### Add ScreenShots/Videos

![WhatsApp Image 2024-10-26 at 22 31 25_c606ffd7](https://github.com/user-attachments/assets/ee243a0c-644d-4a5e-8109-eff28b5a66bc)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by harith-hacky03** [comment]
Assign me please?

**Comment by apu52** [comment]
@biswajit-sarkar-007 Please don't raise more than 2 issues It violates the rules of the contribution guidelines of this repo. Please go through the contributing.md file before contributing. I have  make this issue as PEMDING , please try to complete the previously assigned 2 issue s , then ping me here , i will assign u the issues

**Comment by biswajit-sarkar-007** [comment]
@apu52 okay

**Comment by biswajit-sarkar-007** [comment]
@apu52 hey done i want to work on this issue

**Comment by apu52** [comment]
@biswajit-sarkar-007 I have assigned you , now u can submit your pr

**Comment by biswajit-sarkar-007** [comment]
@apu52  okay 👍

**Comment by biswajit-sarkar-007** [comment]
@apu52  okay 👍

**Comment by harith-hacky03** [comment]
I asked yesterday to assign me sir! If you only assign your friends circle then create private repo and do it please! Thank you

**Comment by biswajit-sarkar-007** [comment]
@harith-hacky03 brother, who created the issue?
