### ISSUE TITLE
[Feature Request]: Adding multiple language support system

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [apu52/METAVERSE#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to imlement a multiple language support systems for your website

### Use Case

its's help the other country people who are not good an english

### Benefits

It's about bringing an audience to your website.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@biswajit-sarkar-007 Please don't raise more than 2 issues It violates the rules of the contribution guidelines of this repo. Please go through the contributing.md file before contributing. raise this issues after u complete the previous assigned issues
