### ISSUE TITLE
[ADD]: Ludo Game

### ISSUE THREAD

**Issue by Mansi07sharma** [apu52/METAVERSE#1332]
**The name of the WEB 3 project you want to add:**
Ludo

**Describe the WEB 3project you want to add:**
Ludo is the board game

**Tech Stack of the project:**
It is made up of HTML CSS JS

**Screenshots /Videos(Mandatory)**
![image](https://github.com/user-attachments/assets/6c1c0d9a-3de5-4bd2-b9a4-8123b1cc6e62)

**Additional context(Mandatory)**

- [x] I have read the Contributing Guidelines *
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [x] I'm a GSSOC'24 Extended contributor
- [x] I'm a Hacktoberfest'24 Extended contributor
- [x] I have starred the repository *

**Comment by apu52** [comment]
@Mansi07sharma sorry but web2 or web1 based projects are not considered as valid contribution in this repo . sorry to close this repo .Please go through the contributing.md file before contributing.  only web3 based projects are allowed as new projects .
But u can still make new issues on which u want to work on
