### ISSUE TITLE
[Bug]: Theme toggle button and Projects Error

### ISSUE THREAD

**Issue by haseebzaki-07** [apu52/METAVERSE#1349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Project and theme toggle button are not visible on the site. I want to fix them 

### Expected behavior

They should be ideally visible 

### Add ScreenShots/Videos

![Screenshot 2024-10-31 120535](https://github.com/user-attachments/assets/37fb83a2-76bd-4354-851b-57ecdc6b8474)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@haseebzaki-07 try to complete the issues u have raised one by one

**Comment by haseebzaki-07** [comment]
@apu52 sure
