### ISSUE TITLE
[Bug]: Navbar is not showing in light mode

### ISSUE THREAD

**Issue by souvikpramanikgit** [apu52/METAVERSE#1363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Navbar is not showing in light mode

### Expected behavior

Because the the text is white in this light mode, the color is matching that's why the text can't be showing, but when you change to dark mode it will show, i have to add some css and some functions.

### Add ScreenShots/Videos

![image](https://github.com/user-attachments/assets/3d79d452-f902-4be3-8980-fb4371349dfe)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by Pragati1466** [comment]
@apu52 could u pls assign me this under ieee-igdtuw it is still not resolved
