### ISSUE TITLE
[Bug]: Light Mode

### ISSUE THREAD

**Issue by saumyayadav25** [apu52/METAVERSE#1366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In light mode, navbar is not visible.

### Expected behavior

Navbar should be visible in light mode as well.

### Add ScreenShots/Videos

<img width="1440" alt="Screenshot 2024-11-13 at 8 27 38 PM" src="https://github.com/user-attachments/assets/dd64f3b0-5aa4-4549-8a08-786e35ff2d90">

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a IEEE-IGDTUW Open Source Week 2024 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@saumyayadav25 u are assigned , start working on this issue & submit your PR
