### ISSUE TITLE
Google clone

### ISSUE THREAD

**Issue by gva-cse** [apu52/METAVERSE#137]
**Describe the project you want to add with tech stack**

**Expected behavior**

**Screenshots (mandatory)**

**Additional context (Mandatory )**
 
- [x] I am a contributor in OSEN open source programme

**Comment by apu52** [comment]
@gva-cse welcome to METAVERSE!!!!!!!
Please go through contributing.md before contributing

**Comment by apu52** [comment]
@gva-cse Please attach a SS of your project

**Comment by Prakashd20** [comment]
@apu52 is this project still ongoing or closed?

**Comment by apu52** [comment]
> @apu52 is this project still ongoing or closed?

This issue is still open. You can work on it. But please try to raise another fresh ossue in this topic.
