### ISSUE TITLE
[ADD]: I want to add my Spotify Clone in the clone section

### ISSUE THREAD

**Issue by Bhumika-00** [apu52/METAVERSE#1371]
**The name of the WEB 3 project you want to add:**
Spotify Clone

**Describe the WEB 3project you want to add:**
Spotify Clone is website tha enables you to play and listen songs.

**Tech Stack of the project:**
HTML/CSS , Javasrcipt 

**Screenshots /Videos(Mandatory)**
![Screenshot from 2024-11-23 18-42-51](https://github.com/user-attachments/assets/807ff9c0-8a90-4944-9f18-aff97feb8794)

**Additional context(Mandatory)**

- [ Yes] I have read the Contributing Guidelines *
- [Yes ] I'm a IEEE-IGDTUW Open Source Week 2024 contributor
- [Yes ] I have starred the repository *

**Comment by apu52** [comment]
@Bhumika-00 Thanks for raising this issue ...
but are u contributing under KWOC???

**Comment by Bhumika-00** [comment]
Yes

**Comment by apu52** [comment]
@Bhumika-00 sorry to close this issue , as only web3 projects are allowed as a valid contribution incase of adding a new project in this repo . other than that u can fix bugs , add features . 
Hoping to see you soon with more contributions
