### ISSUE TITLE
[ADD]: Want to add a new website into the food category.

### ISSUE THREAD

**Issue by Bhumika-00** [apu52/METAVERSE#1373]
**The name of the WEB 3 project you want to add:**
DishDash

**Describe the WEB 3project you want to add:**
It's a website that consist of recipes of various food items.

**Tech Stack of the project:**
HTML/CSS , Javascript(API)

**Screenshots /Videos(Mandatory)**
![Screenshot from 2024-11-23 18-50-49](https://github.com/user-attachments/assets/45159a46-ee8b-4782-abeb-6563312c7f6e)

**Additional context(Mandatory)**

- [ Yes] I have read the Contributing Guidelines *
- [ Yes] I'm a IEEE-IGDTUW Open Source Week 2024 contributor
- [ Yes] I have starred the repository *

![Screenshot from 2024-11-23 18-50-34](https://github.com/user-attachments/assets/7be3c1e0-2543-4c58-97ae-f53a50707dbb)

**Comment by apu52** [comment]
@Bhumika-00 Thanks for raising this issue ...
but are u contributing under KWOC???

**Comment by Bhumika-00** [comment]
Yeh I am contributing under KWOC

**Comment by apu52** [comment]
@Bhumika-00 Actually i want to inform u one thing , that the contribution period of kwoc will start from 5 th dec , so any contributions before that timeline will not count towards KWOC , so please try to start contributing after 5th DEC .

& regarding this issues which u have raised prior , don't worry about it , i will review & assign u this issues after the contribution period starts

**Comment by Bhumika-00** [comment]
Okay thank you so much

**Comment by apu52** [comment]
@Bhumika-00 sorry to close this issue , as only web3 projects are allowed as a valid contribution incase of adding a new project in this repo . other than that u can fix bugs , add features .
Hoping to see you soon with more contributions
