### ISSUE TITLE
[Bug]: x logo change

### ISSUE THREAD

**Issue by neeraj10122004** [apu52/METAVERSE#1379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the color of the x logo is in contrast with the other logos aside of it

### Expected behavior

x logo should be black too

### Add ScreenShots/Videos

![image](https://github.com/user-attachments/assets/af134f3e-9506-4e68-aa72-5bb5d4e6a73d)
![image](https://github.com/user-attachments/assets/14b61e7f-d3a1-4308-a5b8-f8468eb2187a)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a KWOC 2024 contributor
- [X] I have starred the repository

**Comment by neeraj10122004** [comment]
please assign this issue to me under KWOC 2024

**Comment by neeraj10122004** [comment]
@apu52

**Comment by apu52** [comment]
@neeraj10122004 u are assigned
