### ISSUE TITLE
[Feature Request]: Add visibility to navbar options. 

### ISSUE THREAD

**Issue by Nishakulkarni06** [apu52/METAVERSE#1381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

For smaller screen sizes hamburger icon is added but the options are not quite visible. 
Add some styling to improve the UI of it. 

### Use Case

For smaller screen sizes. 

### Add ScreenShots/Videos

![Screenshot 2024-12-09 153647](https://github.com/user-attachments/assets/0eba3ac4-7731-4d72-a930-b5ae904c2b10)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a KWOC 2024 contributor
- [X] I have starred the repository

**Comment by Nishakulkarni06** [comment]
@apu52 Assign this issue to me

**Comment by apu52** [comment]
@Nishakulkarni06 u can start working on it . I have assigned you the issue
