### ISSUE TITLE
[Bug]: Fix the broken links of mini projects. 

### ISSUE THREAD

**Issue by Nishakulkarni06** [apu52/METAVERSE#1383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some links of mini projects listed at last are broken. Not redirecting to desired destination. I want to fix this. 

### Expected behavior

It should redirect to desired page. 

### Add ScreenShots/Videos

https://github.com/user-attachments/assets/ae084b24-a53a-45e6-9b51-24b5f83b58ac

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a KWOC 2024 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Nishakulkarni06 u are assigned
