### ISSUE TITLE
[UI Improve]: Improve 404 page not found to new look

### ISSUE THREAD

**Issue by ThePhoenix08** [apu52/METAVERSE#1388]
I propose, using a nice 3D spline model to add intractability and make the 404 page look cooler. Keeping the older go back home button intact. On mobiles, which cant load 3D models, I will use a svg of 404 to replace the 3D model. Overall improve looks and feel of the 404 page.

**Comment by apu52** [comment]
@ThePhoenix08 i am assigning u this issue for this time , but from next time please try to follow the issue templates already provided in the repo with all the proper details , Now as i have assigned you start working on the pr

**Comment by ThePhoenix08** [comment]
My sincere apologies for making a blank issue and providing you improper details. I am new to this was unaware of how it works. I assure you I will follow the guidelines and be more careful from next time.

**Comment by apu52** [comment]
> My sincere apologies for making a blank issue and providing you improper details. I am new to this was unaware of how it works. I assure you I will follow the guidelines and be more careful from next time.

no worries about that it's okay , just go on with your pr
