### ISSUE TITLE
[Feature Request]: Online Courses Selling Website

### ISSUE THREAD

**Issue by Smritigit1202** [apu52/METAVERSE#1389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Online Courses Selling Website

### Use Case

Online Courses Selling Website using HTML, CSS, JS

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a KWOC 2024 contributor
- [X] I have starred the repository

**Comment by Smritigit1202** [comment]
Pls assign me the issue

**Comment by apu52** [comment]
@Smritigit1202 in this repo only web3 based projects are allowed as a new project contribution , so sorry to close this issue for now , but still u can make new issues , please go through the contributing.md file before contributing .
All the best for your future contributions
