### ISSUE TITLE
want to display age in dog years (age calculator project)

### ISSUE THREAD

**Issue by abhayvershwal** [apu52/METAVERSE#151]
Certainly! When raising a feature request on GitHub, providing clear and detailed information helps the maintainers understand your suggestion. Here's a template for raising the "Age in Dog Years" feature as an issue:

Feature Request: Age in Dog Years
Description
I would like to propose the addition of a fun and lighthearted feature to the Age Calculator. The idea is to include an option that allows users to calculate their age in dog years.

Motivation
Calculating age in dog years can add an entertaining element to the calculator, making it more engaging for users. It aligns with the playful nature of the tool and can be a unique feature that sets it apart.

Proposed Implementation
I suggest adding a new option, "Dog Years," to the unitSelector dropdown. When users select this option and click the "Calculate" button, the calculator should provide their age converted into dog years. As a simple conversion, we can assume 1 human year is equivalent to 7 dog years.
I am an OSEN contributor 
![image](https://github.com/apu52/METAVERSE/assets/93792490/2e4baf5d-6730-4ea8-9556-56a2488006fd)

**Comment by apu52** [comment]
@abhayvershwal Welcome to METAVERTSE!!!!!
Please go through contribibuting.md before contributing

**Comment by apu52** [comment]
& also @abhayvershwal From next time please try to fill up your issue with the help of **_Feature request_** template  as it will be easily explainable.

**Comment by tusharshah21** [comment]
please assign it to me @apu52

**Comment by shruti-sen2004** [comment]
> please assign it to me @apu52

@tusharshah21 thank you for showing your interest to work on this project but it has been already assigned to @abhayvershwal. Please try to work on a different issue.
