### ISSUE TITLE
Add new project

### ISSUE THREAD

**Issue by SOMNATH0904** [apu52/METAVERSE#152]
### Project title
Spotify-CLone

### Project Description
This Project Spotify Clone is created Only using HTML and CSS ...

### Web stack
The web stacks used are : 1. HTML 2. CSS

### Screenshot(mandatory)

<img width="959" alt="SS1" src="https://github.com/apu52/METAVERSE/assets/130086832/dc9d9481-b94e-4eab-bc79-a82ec07eda34">

<img width="960" alt="SS2" src="https://github.com/apu52/METAVERSE/assets/130086832/046d3a46-0dba-4bdc-966a-e5be46113328">

#### Are you contributing under any open-source program ?
Yes, Contributing under OSEN Program ...

<hr/>

**Comment by apu52** [comment]
@SOMNATH0904 Welcome to METAVERSE!!!!!!!!
Please go through contributing.md before contributing.
