### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by Geeks-Arpan** [apu52/METAVERSE#154]
Title: 
Random Password Generator

 Description:
A random password generator is a software program or hardware device that automatically generates a password.

 Web stack:
Html,Css and Js

 Screenshot(mandatory):
![Screenshot 2023-11-11 184129](https://github.com/apu52/METAVERSE/assets/99377659/361200c5-e26c-4676-8c7b-7915b1092676)

Are you contributing under any open-source program ?
OSEN

<hr/>

**Comment by apu52** [comment]
> As a KWOC Contributor, I would like to work on this issue.

@ayann07 You can work on this issue
But first of ALL TRY TO RAISE A NEW ISSUE regarding this.

**Comment by apu52** [comment]
> I have now raised a new issue.

You are already assigned
