### ISSUE TITLE
The Simon Game

### ISSUE THREAD

**Issue by Subhrangsu90** [apu52/METAVERSE#158]
### Project title:
The Simon Game

### Project Description:
The Simon Game is an engaging and interactive web application that brings the classic memory game to life. Players are challenged to follow a dynamic sequence of colored buttons, testing and enhancing their memory skills. With a highest score feature, players can aim to beat their own records, adding an extra layer of excitement to the game.

### Web stack:
HTML, CSS, JavaScript

### Screenshot(mandatory):
![Screenshot (92)](https://github.com/apu52/METAVERSE/assets/76052002/a1043f94-93a8-41d3-ae74-33cc8365285f)

#### Are you contributing under any open-source program ?
 KWOC

<hr/>

**Comment by apu52** [comment]
Btw this project is not a part of KOSS . It's part of KWOC

**Comment by apu52** [comment]
> Thank you for clarifying. I'm excited to be contributing to KWOC, and this is my first open-source contribution. Could you please grant me permission to edit the issue?

@Subhrangsu90 you can edit it anytime & obvio welcome to the world of open-source

**Comment by apu52** [comment]
I am  assigning u  this  issue , U can start work on these. Although the coding period haven't started yet for KWOC .
