### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by harshitkandpal** [apu52/METAVERSE#159]
**Is your feature request related to a problem? Please describe.**

https://github.com/apu52/METAVERSE/assets/111063866/b9bf38e6-a15c-437e-a19b-6be77b717a0e

1. The text field needs some padding and font size needs to be a little small.
2. I want to add  intellisense to this editor this will help in code faster and improves the user experience.

***Are you contributing under any open-source program ?***

KWOC

**Comment by apu52** [comment]
@harshitkandpal Welcome to METAVERSE!!!!!!
Please go through contributing.md before contributing.

**Comment by harshitkandpal** [comment]
https://github.com/apu52/METAVERSE/assets/111063866/93bd80d6-6df9-4798-9370-3e5ee2247554

Current status of the code editor 
please add label KWOC23 then I will create a PR.
