### ISSUE TITLE
New Animation

### ISSUE THREAD

**Issue by apu52** [apu52/METAVERSE#160]
### Project title

Hello ,
I want to add a new animation
### Project Description

I have made an animation as "Day & night fox" where we can see the change of theme (light to dark) with a fox animation
### Web stack

HTML , CSS

### Screenshot(mandatory)

![Day   night fox img](https://github.com/apu52/METAVERSE/assets/114172928/61dee81f-c64b-4e02-a52a-d461ba853c11)

#### Are you contributing under any open-source program ?

Codepeak23
<hr/>

**Comment by Swap-nil-2003** [comment]
Hey, @apu52 could I be assigned this issue under Codepeak. Thanks!

**Comment by apu52** [comment]
> Hey, @apu52 could I be assigned this issue under Codepeak. Thanks!

@Swap-nil-2003 You can work on this issue . Shall I assign you on this issue?

**Comment by Swap-nil-2003** [comment]
@apu52 yes i would like to work on this

**Comment by apu52** [comment]
> @apu52 yes i would like to work on this

I have assigned you
