### ISSUE TITLE
Add new animation

### ISSUE THREAD

**Issue by apu52** [apu52/METAVERSE#161]
### Project title

Hello ,
I want to add a new Cassette Animation
### Project Description

It is a cassette animation where we can see a cassette playing a song.
### Web stack

HTML & CSS

### Screenshot(mandatory)

![image](https://github.com/apu52/METAVERSE/assets/114172928/d22f881d-37b1-466c-b0b2-aace364996a2)

#### Are you contributing under any open-source program ?

Codepeak'23
<hr/>

**Comment by apu52** [comment]
> @apu52 please assign this to me... Can you tell me do we have to make a new folder naming Cassette animation or it is in the Repo files just we need to add the animations?

you have to make a new folder & have to upload it there
For more detailed info please follow Contributing.md file

**Comment by singhcoder694** [comment]
@apu52 yes, under Codepeak'23

**Comment by apu52** [comment]
> @apu52 yes, under Codepeak'23, Also I can make Cassette Animation using any images or Do I need to use this image and design?

you can make any design of your own choice!

**Comment by apu52** [comment]
@singhcoder694 I have assigned you. Happy Coding!!!
If you face any problem you can reach out to us in DISCORD
