### ISSUE TITLE
Heading (metaverse and the logo) is not responsive 

### ISSUE THREAD

**Issue by Devesh-Daku** [apu52/METAVERSE#163]
Heading of the Project is not Responsive 
the logoImage and the Tiltoe(Metaverse) are not completely visible on mobile 
Also the button (to switch between dark and light mode ) also come above the title when viewing by mobile

**Comment by Preeti8021** [comment]
Hello, can i contribute to it as a part of Code Peak 23' ? If yes, please assign

**Comment by apu52** [comment]
> Heading of the Project is not Responsive the logoImage and the Tiltoe(Metaverse) are not completely visible on mobile Also the button (to switch between dark and light mode ) also come above the title when viewing by mobile

@Devesh-Daku Welcome to Metaverse!!!!!!!!

**Comment by Devesh-Daku** [comment]
Thanks,

**Comment by Devesh-Daku** [comment]
I am interested in solving the issue if available i want to solve

**Comment by apu52** [comment]
> > Heading of the Project is not Responsive the logoImage and the Tiltoe(Metaverse) are not completely visible on mobile Also the button (to switch between dark and light mode ) also come above the title when viewing by mobile
> 
> @Devesh-Daku Welcome to Metaverse!!!!!!!!

![image](https://github.com/apu52/METAVERSE/assets/114172928/0fc93a9b-5675-41d7-b25f-edfb7c6d6436)

@Devesh-Daku Please try to raise this  issue with this template which is already available in the **"new Issue"** section to elaborate .

**Comment by apu52** [comment]
> Hello, can i contribute to it as a part of Code Peak 23' ? If yes, please assign

@Preeti8021 Welcome to METAVERSE!!!!!!!
Please try to raise a new issue as this issue is already raised.

**Comment by Devesh-Daku** [comment]
Okay got it
