### ISSUE TITLE
Feature_Request - Add a featured products section to navbar of Myntra Clone Website

### ISSUE THREAD

**Issue by Swap-nil-2003** [apu52/METAVERSE#164]
**Is your feature request related to a problem? Please describe.**

To improve and enhance the user experience for the Myntra Clone website, would want to implement this redirection feature which would help users to directly move into the featured products section. Additionally, the functionality of 'about' and 'contact' on navbar needs to be fixed since on clicking them it redirects us to a 404:Page not found.

**Describe the solution you'd like**

Create a link against the tag which would take us to 'Featured Projects' section.

**Describe alternatives you've considered**

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

Codepeak 2023

**Comment by apu52** [comment]
@Swap-nil-2003 Welcome to METAVERSE!!!
Please go through contributing.md before contributing
