### ISSUE TITLE
Heading Responsive issue 

### ISSUE THREAD

**Issue by Devesh-Daku** [apu52/METAVERSE#165]
Heading of the Project is not Responsive
the logoImage and the Tiltoe(Metaverse) are not completely visible on mobile
Also the button (to switch between dark and light mode ) also come above the title when viewing by mobile

**Comment by Fahass** [comment]
Hi, I'll like to work on this issue please.

**Comment by Devesh-Daku** [comment]
🙂

**Comment by Devesh-Daku** [comment]
Please label codepeak to the issue and i am interested in solving

**Comment by Fahass** [comment]
@Devesh-Daku I keep on getting error when trying to clone the project on my local IDE.

**Comment by apu52** [comment]
@Devesh-Daku please try to use the issue template of  "BUG report" not this issue template.
![image](https://github.com/apu52/METAVERSE/assets/114172928/18dbf577-6c31-4f07-ad13-6eb6c4dcd3d3)

this issue template
