### ISSUE TITLE
Analog Clock

### ISSUE THREAD

**Issue by MitulSonagara** [apu52/METAVERSE#167]
### Project title
Analog Clock

### Project Description
This Analog Clock is created using HTML, CSS and JavaScript. This have features like showing minutes, hours and as well as seconds also. The design of the clock is responsive in design.

### Web stack
HTML, CSS and JavaScript

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/95460188/01453f52-6fac-4b5c-9b5f-f53cde285ea9)

#### Are you contributing under any open-source program ?
I am contributing under KWOC 2023 program...
<hr/>

**Comment by apu52** [comment]
@MitulSonagara Welcome to METAVERSE!!!!!!
Please go through contributing.md before contributing.

**Comment by ayann07** [comment]
Description - I want to contribute by having both analog and digital time display clock. Please assign it to me. i am contributing under KWOC.

**Comment by apu52** [comment]
> Description - I want to contribute by having both analog and digital time display clock. Please assign it to me. i am contributing under KWOC.

@ayann07 Welcome to METAVERSE!
Please try to raise a new issue regarding your topic as this issue is already being taken

**Comment by MitulSonagara** [comment]
@ayann07  I have created a PR by creating analog clock using html, css and js ... please check the PR and give me some suggestions if needed
