### ISSUE TITLE
Centering contributor list

### ISSUE THREAD

**Issue by Afterdie** [apu52/METAVERSE#170]
**Describe the bug**
The contributor list is left aligned

**Expected behavior**
The div should be center aligned

**Screenshots (Mandatory)**
![image](https://github.com/apu52/METAVERSE/assets/82810411/0d875d3d-a6f7-4eb4-a4d8-f68b4891cd32)

***Are you contributing under any open-source program ?***
Codepeak 23

**Comment by Afterdie** [comment]
Id like to work on this issue

**Comment by apu52** [comment]
@Afterdie Welcome to METAVERSE!!!
Please go through contributing.md before contributing.
