### ISSUE TITLE
Random Password generator 

### ISSUE THREAD

**Issue by ayann07** [apu52/METAVERSE#171]
Description: This software will generate a random password in which user can specify length of password, whether they want to include numbers ,symbol, upper case letters or lower case letters in the password.

Tech stack:
Html , css and javascript

Screenshot:
![main-issue](https://github.com/apu52/METAVERSE/assets/126085856/3cf3832a-e373-4d65-a48a-c66bd144393f)

 Ae you contributing under any open- source program?
 Yes, Kharagpur Winter Of Code

**Comment by apu52** [comment]
@ayann07 I am assigning you this issue
Please go through contributing.md before contributing.
