### ISSUE TITLE
Digital Clock

### ISSUE THREAD

**Issue by Paarisha1** [apu52/METAVERSE#173]
Description: In this project we will make a Digital clock that will display the current time in Hours, Minutes and second. This  
clock display the time as per Local time zone. We will use HTML and CSS to design this Clock, and for Updating the current time we will use JavaScript Date Object. 
![digital clock](https://github.com/apu52/METAVERSE/assets/147527266/e1cbd432-7335-4b5e-a23d-7db6d8e9a6b7)
2d18fea)

tech stack  :html ,css  ,JavaScript
Are you contributing under any open source program?
yes, Kharagpur winter of code.

**Comment by shruti-sen2004** [comment]
Hello @Paarisha1 ....Thank you for showing your interest to work on this issue but we already have this project as a part of Metaverse. Please try to contribute on a different issue.
