### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by Albert-2** [apu52/METAVERSE#174]
**Describe the bug**

the website looks great on desktop and on tablet devices too but layout failed in mobile screen size

**Expected behavior**

I can fixed the issue so that the layout will look cool and consistent irrespective of any screen size

**Screenshots (Mandatory)**

![image](https://github.com/apu52/METAVERSE/assets/90373859/a1956b56-326b-42c0-a4c9-30b53ddc85e7)

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by apu52** [comment]
@Albert-2  Are you contributing under any open source programme???
Codepeak'23 or KWOC?

**Comment by Albert-2** [comment]
yes....

**Comment by apu52** [comment]
> yes....

Which open-source programme?

**Comment by Albert-2** [comment]
Codepeak'23

**Comment by Albert-2** [comment]
Thanks man.....
Appreciate.... 😀👍

**Comment by Albert-2** [comment]
hey @apu52 
Someone fixed the UI 
your book review website has same issue
can i fixed that as someone already fixed the home page under this issue
![image](https://github.com/apu52/METAVERSE/assets/90373859/14abd446-8d24-4a05-a28a-4486f0e6ce3b)

**Comment by apu52** [comment]
> hey @apu52 Someone fixed the UI your book review website has same issue can i fixed that as someone already fixed the home page under this issue ![image](https://private-user-images.githubusercontent.com/90373859/289342103-14abd446-8d24-4a05-a28a-4486f0e6ce3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTM4MTgsIm5iZiI6MTcwMjE5MzUxOCwicGF0aCI6Ii85MDM3Mzg1OS8yODkzNDIxMDMtMTRhYmQ0NDYtOGQyNC00YTA1LWEyOGEtNDQ4NmYwZTZjZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA3MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZGVhOWQ5ZTEyNGM3NmI5NmFkNTU5MzMzZDY2OTk2ODlhODdlNzUyZDUxYTEyNjc0NWNmZmYzYTI1ZTRkMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.04A6dsfNjIs81AH2_3zwJc7pB3jHsO9hD2OsvSa6k9M)

ok.Please raise an new issue regarding this. So that I can assign assign you this
