### ISSUE TITLE
Issue in Responsiveness in Heading

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#181]
**Describe the bug**
The heading of the website is not at all responsive.

**Expected behavior**
It should be properly dimensioned and responsive.

**Screenshots (Mandatory)**

![Screenshot (4)](https://github.com/apu52/METAVERSE/assets/127030695/10ee9c31-0c82-4180-8b3f-19519b39f760)

**Additional context (Mandatory )**
This issue was already existing. It was not in proper format thatswhy i raised it again.

***Are you contributing under any open-source program ?***
Yes I am contributing under KWOC.

**Comment by apu52** [comment]
Please don't make any PR until & unless you get assigned to that issue
