### ISSUE TITLE
Recipe App

### ISSUE THREAD

**Issue by Paarisha1** [apu52/METAVERSE#182]
A recipe app built with HTML, CSS, and JavaScript is a user-friendly web application that allows users to browse, search, and view recipes, here we can also see what are the ingredients needed to make that particular dish.

Screenshot: 
![recipe app](https://github.com/apu52/METAVERSE/assets/147527266/e9086a8c-c1d8-4293-a4a1-dc57f9d77d2f)

Tech stack:  HTML ,css,  Javascript.
Are you contributing under any open source/
Yes, Kharagpur winter of code.

**Comment by apu52** [comment]
@Paarisha1 Welcome to METAVERSE!!!!!!!
PLEASE GO THROUGH contributing.md before contributing.
