### ISSUE TITLE
Add new project - Productive Webapp

### ISSUE THREAD

**Issue by Surajit0573** [apu52/METAVERSE#184]
### Project title
Productive Webapp

### Project Description
This is a user-friendly productivity app made with HTML, CSS, JavaScript, and a Weather API. There are....

1.✅ To-Do List

2.⏰ Alarm Features

3.🌦️ Weather Updates

### Web stack
HTML, CSS, JavaScript, and a Weather API

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/111490250/108cfc5a-7a46-4e2a-ace3-2542e0571ed0)

#### Are you contributing under any open-source program ?
yes, I am contributing in KWOC 2023.

<hr/>

**Comment by apu52** [comment]
@Surajit0573 Welcome to METAVERSE!!!!!!!
Please go through contributing.md before submitting your PR.
