### ISSUE TITLE
An event organizing App

### ISSUE THREAD

**Issue by NandishM0618** [apu52/METAVERSE#191]
### Project title
An event tracking and organizing app

### Project Description
This web app is designed in such way that it helps users to know which event is live or upcoming and number of attendees and many. And it has feature to host the users event also. 

### Web stack
React js 
Tailwind CSS
CSS

### Screenshot(mandatory)
![Screenshot_2023_1210_005604](https://github.com/apu52/METAVERSE/assets/100901899/8cfbda4e-224e-4d34-b8e3-1ca7ac470ba4)

### Additional Context(mandatory)
It helps to know the live events and know more about organisation's which helps to conducts the events. users can also view the past events too. 

#### Are you contributing under any open-source program
Yes. codepeak'23

**Comment by apu52** [comment]
@NandishM0618 Welcome to METAVERSE!!!!!!
Please go through contributing.md before contributing

**Comment by NandishM0618** [comment]
@apu52 can you help me out how can I update my project name projectData.json.
