### ISSUE TITLE
E-commerce Website

### ISSUE THREAD

**Issue by singhcoder694** [apu52/METAVERSE#193]
### Project title
E-COMMERCE WEBSITE

### Project Description
It is website which gives a good descritption of how a Ecommerce website should look like. It is working website having so many E-commerce facilities like Adding a **Product, Updating a Product, Showing Description of Product, Deleting Product**

### Web stack
1.) ReactJS
2.) HTML, CSS and JS
3.) Bootstrap 5
4.) API (GET, PUT, POST, PATCH, DELETE)

### Screenshot(mandatory)

**Home Page**
<img width="885" alt="Screenshot 2023-12-10 114036" src="https://github.com/apu52/METAVERSE/assets/114601400/a19b1f1a-4e34-49ab-bbb5-ec1d741ed100">

**Contact Page**
<img width="882" alt="Screenshot 2023-12-10 114048" src="https://github.com/apu52/METAVERSE/assets/114601400/9e10f235-d1d0-4011-be06-2edb4339843f">

**Product Page**
<img width="913" alt="Screenshot 2023-12-10 114128" src="https://github.com/apu52/METAVERSE/assets/114601400/2b90a063-965d-4cfb-8f02-d2eabca60cbc">

**Client Views**
<img width="910" alt="Screenshot 2023-12-10 114144" src="https://github.com/apu52/METAVERSE/assets/114601400/3550bfd5-0b74-4575-af69-0dc1dfe14671">

**Footer**
<img width="939" alt="Screenshot 2023-12-10 114152" src="https://github.com/apu52/METAVERSE/assets/114601400/4b6abdfe-d00b-4efc-b4f7-0c2b359931e9">

### Additional Context(mandatory)

**Full Fledged website for Ecommerce.**

#### Are you contributing under any open-source program ?
CodePeak'23

<hr/>

**Comment by singhcoder694** [comment]
@apu52 I had question regarding points.... This is big project with many functionalites and other stuff. How will you give points for this issue?

**Comment by singhcoder694** [comment]
@apu52 I had one more doubt, since it is a React Web App. How should I add it in Project folder ? With node modules(Large Size Issue) or without node module folder?

**Comment by apu52** [comment]
> @apu52 I had question regarding points.... This is big project with many functionalites and other stuff. How will you give points for this issue?

the point system consists of EASY/MEDIUM/HARD/1-point PR. The mods will only decide the point of the PR as per their review

**Comment by apu52** [comment]
> @apu52 I had one more doubt, since it is a React Web App. How should I add it in Project folder ? With node modules(Large Size Issue) or without node module folder?

No. you don't have to upload it
