### ISSUE TITLE
Feature_Request: Improving the UI of the navbar of Hackathon website.

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#196]
**Is your feature request related to a problem? Please describe.**

The navbar of the website is not looking good.It needs some corrections.

**Describe the solution you'd like**

I am going to improve the UI of the navbar with the help of CSS and JavaScript.

Screenshot of the problem:
![Screenshot (11)](https://github.com/apu52/METAVERSE/assets/127030695/514f17c6-993e-4b96-9a9e-5e9c116e4762)

**Additional context (Mandatory )**
Kindly assign me this issue. I want to contribute to this project.

***Are you contributing under any open-source program ?***

Yes under KWOC.

**Comment by siwamsingh** [comment]
Idea for Improvement of current ui - for  improving navbar we can move home, contest, about and contact at the left side with small gaps in between.  While for the search bar can be upgraded by increasing height and background colour. 

Appropriate colour uses and background images for better ui experience.
Using only css is not enough we can add bit javascript for some animation.

Kindly assign me this issue. I want to contribute to this project.

Thankyou
