### ISSUE TITLE
Moto Racer

### ISSUE THREAD

**Issue by drockparashar** [apu52/METAVERSE#199]
### Project title
Moto Racer

### Project Description
This a 2D car racing game.

### Web stack
HTML, CSS, Javascript

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/118686637/cfbfbac3-cb19-4c06-8d1e-94a049ae61c7)

#### Are you contributing under any open-source program ?
Codepeak 23

<hr/>

**Comment by apu52** [comment]
@drockparashar Welcome to METAVERSE!!!
In which open-source programme you are contributing?

**Comment by drockparashar** [comment]
I have added - Codepeak 23
