### ISSUE TITLE
Add a calender app

### ISSUE THREAD

**Issue by dhwanish-3** [apu52/METAVERSE#20]
**Description**
I want add a calender app built using html, css, javascript

**Comment by aryankshl** [comment]
hey @dhwanish-3 can you assign this to me?

**Comment by apu52** [comment]
@dhwanish-3 Welcome to Metaverse!!!!!!!!!🥳
Thanks For raising the Issue. 👍

**Comment by apu52** [comment]
@dhwanish-3 Can you please add some more description using the issue template . So, that I can assign you in this project....

**Comment by dhwanish-3** [comment]
> hey @dhwanish-3 can you assign this to me?

Sorry, I can not do it as I do not have write access
Try creating a new issue according to contributions.md

**Comment by apu52** [comment]
@aryankshl try to create another new issue
