### ISSUE TITLE
snake-game

### ISSUE THREAD

**Issue by Surajit0573** [apu52/METAVERSE#202]
### Project title
snake-game

### Project Description
Its a basics Javascript snake game using DOM Event.

### Web stack
HTML, CSS, JavaScript.

### Screenshot(mandatory)

![image](https://github.com/apu52/METAVERSE/assets/111490250/dc8dcea9-f8d0-4f19-b069-fa75e21d4e2e)

#### Are you contributing under any open-source program ?
Yes, under Codepeak 2023.

<hr/>

**Comment by apu52** [comment]
@Surajit0573 Welcome to METAVERSE!!!!!!!
Please go through contributing.md before contributing.
