### ISSUE TITLE
Responsiveness Problem in Food_Ordering_Website

### ISSUE THREAD

**Issue by bibhabasuiitkgp** [apu52/METAVERSE#203]
**Describe the bug**

The components in the website are not at all responsive
The images and the text overlap during mobile view and the

**Expected behavior**

**Screenshots (Mandatory)**

![issue in food website](https://github.com/apu52/METAVERSE/assets/122109000/215f280c-8518-4181-b355-278da84212fa)

**Additional context (Mandatory )**
Kindly assign me this issue

***Are you contributing under any open-source program ?***

KWOC 2023

**Comment by apu52** [comment]
@bibhabasuiitkgp Welcome to METAVERSE!!!!!!
Please go through contributing.md before contributing.
