### ISSUE TITLE
Add new project

### ISSUE THREAD

**Issue by GAGANRAGHAV** [apu52/METAVERSE#205]
### Project title
Space Invader game
### Web stack
python

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/120806356/c6ac6282-f384-4949-aa2e-b08ee1a674bf)

### Additional Context(mandatory)
a game made my python 
#### Are you contributing under any open-source program ?
codepeak 2023
<hr/>

**Comment by apu52** [comment]
sorry @GAGANRAGHAV , but we can't accept this webstack as this repo is consists of front-end projects
