### ISSUE TITLE
TIC-TAC-TOE

### ISSUE THREAD

**Issue by GAGANRAGHAV** [apu52/METAVERSE#206]
### Project title
tic tac toe game

### Web stack
HTML , CSS , JAVASCRIPT

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/120806356/53299cd5-c7ea-4dfc-b262-21b17022461a)

### Additional Context(mandatory)
2 players can play this game 

<hr/>

**Comment by apu52** [comment]
@GAGANRAGHAV under which open source programme you are contributing?

**Comment by GAGANRAGHAV** [comment]
Codepeak 2023
