### ISSUE TITLE
NFT Website Clone

### ISSUE THREAD

**Issue by anand-harsh** [apu52/METAVERSE#208]
### Project title
NFT Website Clone

### Project Description
It is clone of a NFT Single page Website of Solana

### Web stack
HTML, CSS

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/94885893/9c47aa1a-143d-4a4c-8465-92df534b3650)

### Additional Context(mandatory)
It is responsive with all types of devices.

#### Are you contributing under any open-source program ?
Kwoc 2023

<hr/>

**Comment by apu52** [comment]
@anand-harsh Welcome to METAVERSE!!!!!!!!
Please go through contributing.md before contributing.

**Comment by apu52** [comment]
@anand-harsh Are you contributing this issue in CODEPEAK'23 also?

**Comment by anand-harsh** [comment]
Yes @apu52
