### ISSUE TITLE
simple Pac-Man game 

### ISSUE THREAD

**Issue by Sami3160** [apu52/METAVERSE#217]
### Project title
a game using html-css-js

### Project Description
im intrested to add an og game as project, its pac man. Same pacman controls will be here with 4 ghosts following you with some random movements and some with planned movements. I'll be using vanilla js, html and css in it.

### Web stack
vanilla js, html css or bootstrap maybe

### Screenshot(mandatory)
![Screenshot (109)](https://github.com/apu52/METAVERSE/assets/110652247/20296020-3520-4aad-b60a-6d1d263d3b26)
this is how game will be looking. yet my ui have some issues so as reference take this google image. Mine will be ditto same

### Additional Context(mandatory)
game need just a browser, no special api, framework, or anything. it is single player game
#### Are you contributing under any open-source program ?

<hr/>

**Comment by Sami3160** [comment]
> ### Project title
> a game using html-css-js
> 
> ### Project Description
> im intrested to add an og game as project, its pac man. Same pacman controls will be here with 4 ghosts following you with some random movements and some with planned movements. I'll be using vanilla js, html and css in it.
> 
> ### Web stack
> vanilla js, html css or bootstrap maybe
> 
> ### Screenshot(mandatory)
> ![Screenshot (109)](https://private-user-images.githubusercontent.com/110652247/289612030-20296020-3520-4aad-b60a-6d1d263d3b26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTQ0MjYsIm5iZiI6MTcwMjMxNDEyNiwicGF0aCI6Ii8xMTA2NTIyNDcvMjg5NjEyMDMwLTIwMjk2MDIwLTM1MjAtNGFhZC1iNjBhLTZkMWQyNjNkM2IyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNzAyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2MxZmY4NzExZjJhODM0ZTlkZTJkNTExOTA5Y2I3YmQ1OWNjNmY0NDFiYmE5YjA3Y2I0N2EyMzExZDJjYzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mbjvTg8T6FYOTftKEgDFC5rrRA-yGYMYo0YcWVFgrKY) this is how game will be looking. yet my ui have some issues so as reference take this google image. Mine will be ditto same
> 
> ### Additional Context(mandatory)
> game need just a browser, no special api, framework, or anything. it is single player game
> 
> #### Are you contributing under any open-source program ?

code peak 2023

**Comment by apu52** [comment]
@Sami3160 Welcome to METAVERSE!!!!!!
please go through contributing.md before contributing.
