### ISSUE TITLE
Speakify- Translator app

### ISSUE THREAD

**Issue by Souvik34** [apu52/METAVERSE#219]
### Project title
Speakify- Translator app

### Project Description
A custom translator application made with HTML, CSS, JavaScript and can translate to any language. It is responsive too and has audio features embedded
### Web stack

HTML
CSS
JavaScript

### Screenshot(mandatory)

<img width="547" alt="image" src="https://github.com/apu52/METAVERSE/assets/98397984/3fba23ca-816d-49a6-9ef9-76b8071db4ca">
<img width="551" alt="image" src="https://github.com/apu52/METAVERSE/assets/98397984/b3ca542c-3208-4d2a-9ab9-d4d0f614d733">

#### Are you contributing under any open-source program ?

KWOC 2023

<hr/>

**Comment by Souvik34** [comment]
label kwoc 2023

**Comment by Souvik34** [comment]
> ### Project title
> Translator
> 
> ### Project Description
> A custom translator application made with HTML, CSS, JavaScript and can translate to any language. It is responsive too and has audio features embedded
> 
> ### Web stack
> HTML CSS JavaScript
> 
> ### Screenshot(mandatory)
> <img alt="image" width="547" src="https://private-user-images.githubusercontent.com/98397984/289644816-3fba23ca-816d-49a6-9ef9-76b8071db4ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjI4MTQsIm5iZiI6MTcwMjMyMjUxNCwicGF0aCI6Ii85ODM5Nzk4NC8yODk2NDQ4MTYtM2ZiYTIzY2EtODE2ZC00OWE2LTllZjktNzZiODA3MWRiNGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE5MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOTQ3YzRlMjQ3MGNhNDBjNDFmMjkxM2I1NmI1N2I2ODJmNGFhZmJhMDczNjFjYjQyOTMxMGE5ZGYyY2RkOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BsFb8jZgSpPEebXFhiFBQP5ofeCp5vgkbGllkAJiHU0"> <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/98397984/289644932-b3ca542c-3208-4d2a-9ab9-d4d0f614d733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjI4MTQsIm5iZiI6MTcwMjMyMjUxNCwicGF0aCI6Ii85ODM5Nzk4NC8yODk2NDQ5MzItYjNjYTU0MmMtMzIwOC00ZDJhLTlhYjktZDRkMGY2MTRkNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE5MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyODI0ZmUzNGNhMDcwNzcyMGM1NDcyMjczZDliMzcxYjI4Y2NlMjI4YThkMGE2ZjRmN2Q5ZDVlZmQ0ODEyMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BBt_Oi0Wd6F9fAKG2gjXZ8whUS1dkY2Le3_xV6hV0Eg">
> ### Additional Context(mandatory)
> #### Are you contributing under any open-source program ?
> Kwoc 2023

**Comment by Souvik34** [comment]
Where to add my code??

**Comment by shruti-sen2004** [comment]
> Where to add my code??

Please read the CONTRIBUTING.md file to know how to contribute

**Comment by apu52** [comment]
> Where to add my code??

@Souvik34 Welcome to METAVERSE!!!!!!
I Have assigned you this issue. Now you can submit your PR.
Please go through contributing.md before contributing.

**Comment by Souvik34** [comment]
@apu52 ok got it

**Comment by Souvik34** [comment]
Is the pull request closed??

**Comment by shruti-sen2004** [comment]
> Is the pull request closed?? Please check @apu52 @shruti-sen2004

Yes @Souvik34 ,your previous PR was closed. Please make a new PR for this issue.
