### ISSUE TITLE
Website Count Down Page Background invisible 

### ISSUE THREAD

**Issue by Preeti8021** [apu52/METAVERSE#221]
**Describe the bug**

Need to fix the website count down page background as content is'nt visible.

**Expected behavior**

The background image must be visible.

**Screenshots (Mandatory)**

<img width="960" alt="image" src="https://github.com/apu52/METAVERSE/assets/103981488/1da3260c-5bf6-432a-803f-2d319917a8be">

**Additional context (Mandatory )**
Please assign this issue to me. 

***Are you contributing under any open-source program ?***

CodePeak'23

**Comment by PraveenShinde3** [comment]
Where is the background image stored?

**Comment by Preeti8021** [comment]
images of that project

**Comment by apu52** [comment]
I Have assigned you @Preeti8021 .
Happy coding!!!!!
