### ISSUE TITLE
Speakify- Translator App

### ISSUE THREAD

**Issue by Souvik34** [apu52/METAVERSE#223]
### Project title

Speakify

### Project Description

A custom language translator app with audio translation embedded.

### Web stack

HTML, CSS, JavaScript

### Screenshot(mandatory)

![image](https://github.com/apu52/METAVERSE/assets/98397984/cb8c6fa4-f628-4e77-b04c-d01b11502522)
![image](https://github.com/apu52/METAVERSE/assets/98397984/4475acac-d807-4bbf-a1e4-f84c47301a20)

#### Are you contributing under any open-source program ?

KWOC 2023

<hr/>

**Comment by Souvik34** [comment]
@apu52 @shruti-sen2004  As said I created a new issue. 
Please open the pull request so that I can push my code

**Comment by shruti-sen2004** [comment]
@Souvik34 I think there was a misunderstanding.....no need to open a new issue ....just make a new PR for your previous issue.
