### ISSUE TITLE
Add new project

### ISSUE THREAD

**Issue by AaadityaG** [apu52/METAVERSE#225]
### Project title
Text Encrypter 

### Project Description
This is the simple text encryptor which will work with your desired key. 

How to use it - 
1. Write the text in input to encrypt 
2. Write any key-text you want 
3. click on Encrypt
4. You will get encrypted key 
5. To decrypt you just need to add the decripted text in input
6. add the same key you have used to encrypt 
7. hit decrypt to decrypt the text

### Web stack
HTML5 / CSS3 / JS
 
### Screenshot(mandatory)
Encryption
![encrypt](https://github.com/apu52/METAVERSE/assets/114663382/14a27993-442b-4ecb-b7ad-1a0efd99d20d)

Decryption
![decrypt](https://github.com/apu52/METAVERSE/assets/114663382/3b30494b-d54c-434c-b8bf-996f21b90d31)

### Additional Context(mandatory)
Live link - https://text-encryptor-wheat.vercel.app/

#### Are you contributing under any open-source program ?
Yes (Codepeak)
<hr/>

**Comment by apu52** [comment]
@AaadityaG Welcome to METAVERSE!!!!!!!!!!!
Please go through contributing.md before contributing.

**Comment by apu52** [comment]
@AaadityaG It's really a good project . But from next time please refrain from mentioning a deployment link in the issues.
I have already assigned you. Start contributing.
Happy Coding!!!

**Comment by AaadityaG** [comment]
Am I eligible to bonus point...🤞🏽

**Comment by apu52** [comment]
> Am I eligible to bonus point...🤞🏽

It totally depends on the review of the project

**Comment by AaadityaG** [comment]
> > Am I eligible to bonus point...🤞🏽
> 
> It totally depends on the review of the project

Ok
