### ISSUE TITLE
Track_Mobile_Phone

### ISSUE THREAD

**Issue by paulsuryanshu** [apu52/METAVERSE#23]
**Describe the project you want to add with tech stack**
_This is project based on python and HTML ,helps us to know the basic details about a mobile number_

**Expected behavior**
_My expectation was to know the specific location of any mobile number but doing this project I know the country location of any mobile number_ 

**Screenshots (optional)**

**Additional context (optional )**

**Comment by apu52** [comment]
@paulsuryanshu Welcome to Metaverse!!!!!!!!!🥳
Thanks For raising the Issue. 👍

**Comment by apu52** [comment]
Please follow contributing.md file for the contribution details.

**Comment by paulsuryanshu** [comment]
thank you
