### ISSUE TITLE
Feature_Request: Adding an About page in Hack among us website.

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#235]
**Is your feature request related to a problem? Please describe.**

The website does not have an About page.

**Describe the solution you'd like**

I am going to add an About page with the help of HTML, CSS and, JS.
Kindly assign me for this issue.
<br>
![Screenshot (13)](https://github.com/apu52/METAVERSE/assets/127030695/cc78f316-c15f-4c1a-92ca-1512d98e8209)
<br>
***Are you contributing under any open-source program ?***

Yes under KWOC.

**Comment by apu52** [comment]
@Abhishek-465 Please don't raise more than 2 issues at a time.
I have already assigned u 2 issues. Try to work on those.
After the completion of those PR's I will assign you this.

**Comment by apu52** [comment]
@Abhishek-465 I have assigned you now!!
You can work on this issue
