### ISSUE TITLE
FIX: The toggle button in the Calendar web app is not visible properly.

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#236]
**Describe the bug**

The toggle button in the Calendar web app is not visible properly .It needs some adjustments.

**Expected behavior**
The toggle button should be clearly visible.

**Screenshots (Mandatory)**
![Screenshot (16)](https://github.com/apu52/METAVERSE/assets/127030695/b4d59c80-f794-40b2-b145-153004643ab1)
<br>

**Additional context (Mandatory )**
I am going to rectify the problem with the help of CSS.
Kindly assign me for this issue.
Thank you.

***Are you contributing under any open-source program ?***

Yes under KWOC.

**Comment by apu52** [comment]
@Abhishek-465 Please don't raise more than 2 issues at a time.
I have already assigned u 2 issues. Try to work on those.
After the completion of those PR's I will assign you this.

**Comment by Abhishek-465** [comment]
Ok Thank you @apu52 i am working on the other issues and after completion kindly assign me this one.

**Comment by apu52** [comment]
@Abhishek-465 I have assigned you now!!
You can work on this issue
