### ISSUE TITLE
Add new project : AI image generator

### ISSUE THREAD

**Issue by AaadityaG** [apu52/METAVERSE#238]
### Project title
AI Image Generator

### Project Description
This is a AI image generator which generators images according to given prompts

### Web stack
HTML5 / CSS3 / JS

### Screenshot(mandatory)

![AI Image Generator - 2](https://github.com/apu52/METAVERSE/assets/114663382/e14e9791-df08-4cf9-85b0-589953d15f5f)

### Additional Context(mandatory)
This is the AI image generator as its name suggests it is made with AI(huggingfaces api). And it generates images based on prompts...
A user can download the images just with the single click.
<hr/>

**Comment by apu52** [comment]
@AaadityaG are you contributing under any open-source programme?
Codepeak/KWOC

**Comment by AaadityaG** [comment]
Yes Codepeak

**Comment by AaadityaG** [comment]
I am participating in KWoC also!

**Comment by apu52** [comment]
> I am participating in KWoC also!
Please clearly mention it in the issue template as it is already mentioned there

**Comment by AaadityaG** [comment]
I think another contri is also not success.

Should I delete fork repo and start new pr❔

**Comment by apu52** [comment]
> I think another contri is also not success.
> 
> Should I delete fork repo and start new pr❔

okay.try to do that

**Comment by apu52** [comment]
> > I think another contri is also not success.
> > Should I delete fork repo and start new pr❔
> 
> okay.try to do that

@AaadityaG Actually in your previous 2 PR , I can't see the codes of that project . There is only the img folder in the pr

**Comment by AaadityaG** [comment]
😑
