### ISSUE TITLE
adding flappy bird game

### ISSUE THREAD

**Issue by sarthakvermaa** [apu52/METAVERSE#239]
### Project title
Flappy Bird game

### Project Description
Famous Flappy bird game made with the web stacks given below.

### Web stack
HTML, CSS and JS

### Screenshot(mandatory)
<img width="502" alt="Screenshot 2023-12-13 141929" src="https://github.com/apu52/METAVERSE/assets/114106172/90c5c30d-a166-4933-9a5d-213a372f6b55">

#### Are you contributing under any open-source program ?
Yes, under CodePeak'23.

<hr/>

**Comment by apu52** [comment]
@sarthakvermaa Welcome to METAVERSE!!!!!!!
Please go through contributing.md before contributing.
