### ISSUE TITLE
Feature_Request: Enhancing the overall User Interface of the Temperature Convertor Project

### ISSUE THREAD

**Issue by agrawal-yash** [apu52/METAVERSE#247]
I've noticed that the current UI design feels outdated, less appealing and the CSS could use some enhancements to improve overall user experience. 

I am capable of contributing to the following enhancements:
1. Enhancing the website design to achieve a more minimalist appearance. 
2. Introducing a more refined color theme throughout the website.
3. Elevating the styling of input fields and buttons for a more polished interface. 
4. Rearrange the input field and drop down buttons for a more user-appealing look. 
5. Changing the font to a more modern & elegant font for a better user experience. 

I am contributing these changes under the KOSS - KWOC 2023. 

Please assign me if I can work on these changes

**Comment by apu52** [comment]
@agrawal-yash welcome to METAVERSE!!!!!!!
Please go through contributing.md before contributing.
& please try to raise farther issues through Issue templates only.
Happy Coding!

**Comment by agrawal-yash** [comment]
Thanks a lot! 
And yes, I'll keep that in mind. 
Also just to communicate further, the discord channel link mentioned in the KWOC page is invalid, so can you please provide me with it?

**Comment by apu52** [comment]
> Thanks a lot! And yes, I'll keep that in mind. Also just to communicate further, the discord channel link mentioned in the KWOC page is invalid, so can you please provide me with it?

https://discord.gg/D72Rbbp6
