### ISSUE TITLE
Someone accedentaly didn't changed the number of his project data...

### ISSUE THREAD

**Issue by AaadityaG** [apu52/METAVERSE#251]
As Below...

![Capture](https://github.com/apu52/METAVERSE/assets/114663382/52ede619-6955-4e94-974a-b71edda1d38c)

I am particiapting in Codepeak and KWoC..

**Comment by abdqudus** [comment]
Hello, I'd like to take on this issue

**Comment by AaadityaG** [comment]
> Hello, I'd like to take on this issue

Its done already

**Comment by AaadityaG** [comment]
Its Ok..!😄
