### ISSUE TITLE
MUSIC PLAYER

### ISSUE THREAD

**Issue by GAGANRAGHAV** [apu52/METAVERSE#253]
### Project title
MUSIC PLAYER

### Web stack
HTML ,CSS ,JAVASCRIPT

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/120806356/19b5c233-bed4-4f84-934d-c9306944248b)

### Additional Context(mandatory)
application which can run on mobile as well as on laptop.
#### Are you contributing under any open-source program ?
codepeak 23

<hr/>

**Comment by apu52** [comment]
@GAGANRAGHAV this project is already present in or repo.
