### ISSUE TITLE
Feature_Request: Improve UI of To-Do List App

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#254]
**Is your feature request related to a problem? Please describe.**

The To-do List app looks very plain. I intend to elevate its design by adding animations etc
**Describe the solution you'd like**

Use bootstrap and gsap for interactive UI
Add Pricing window
Create Features page 

**Describe alternatives you've considered**

Adding topic wise segregation to do-list app

**Additional context (Mandatory )**
A robust to-do list app should include intuitive task creation and organization, due date and priority settings, synchronization across devices, reminders, subtasks, collaboration options, and a user-friendly interface. Additionally, features like progress tracking, customizable categories, and integration with calendars enhance productivity. Accessibility and offline functionality contribute to a comprehensive task management experience. 
***Are you contributing under any open-source program ?***

CodePeak 2023

**Comment by apu52** [comment]
@aindree-2005 Welcome to METAVERSE!!!!!!
I will assign you this issue. But can you provide some SS of the features you want to add??

**Comment by aindree-2005** [comment]
![Screenshot (271)](https://github.com/apu52/METAVERSE/assets/68018372/dc8cfb1f-ba3d-418b-92ec-c9b11cdd6194)

![Screenshot (272)](https://github.com/apu52/METAVERSE/assets/68018372/45d8439c-a96a-4598-b642-bd6efbb059b3)

These are from Todoist app. But the to-dolist app here has tabs for pricing and features but no pricing and features provided, that is the navbar links are invalid. So first I wish to add those pages and change the frontend and then add a Done page for completed tasks. Also, add time and date functionality for the tasks to be done

**Comment by apu52** [comment]
> ![Screenshot (271)](https://private-user-images.githubusercontent.com/68018372/290546044-dc8cfb1f-ba3d-418b-92ec-c9b11cdd6194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzIwNzgsIm5iZiI6MTcwMjU3MTc3OCwicGF0aCI6Ii82ODAxODM3Mi8yOTA1NDYwNDQtZGM4Y2ZiMWYtYmEzZC00MThiLTkyZWMtYzliMTFjZGQ2MTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE2MzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZmY4YjVmMTlmMjhkY2ZjNDdhMTFlZGRmZmM1MDYzYzYxMGRmYjMyZmQyNDUxYWFmOGY4OGQwMzc5OTBkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KtyqoI2VPpgCRe_W1bbsgxwdNRm_loVZ7lomzLMUpwM)
> 
> ![Screenshot (272)](https://private-user-images.githubusercontent.com/68018372/290546178-45d8439c-a96a-4598-b642-bd6efbb059b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzIwNzgsIm5iZiI6MTcwMjU3MTc3OCwicGF0aCI6Ii82ODAxODM3Mi8yOTA1NDYxNzgtNDVkODQzOWMtYTk2YS00NTk4LWI2NDItYmQ2ZWZiYjA1OWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE2MzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZTUzYWU3YjAwMGMxYzhkYTA0YjM2MzQ0Y2EyMWFlZGJkZDE0MzFlN2VjOWUwMTMzYTk4MmU0YmUyOTFlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rEV8zEBxusIOR6p-5m2oeNKSIZ8cJUzbUNROp0ynBUo)
> 
> These are from Todoist app. But the to-dolist app here has tabs for pricing and features but no pricing and features provided, that is the navbar links are invalid. So first I wish to add those pages and change the frontend and then add a Done page for completed tasks. Also, add time and date functionality for the tasks to be done

That's really impressive. I am assigning you
happy coding!!!!!!

**Comment by aindree-2005** [comment]
@apu52 #263 fixes this
-Adds animated Navbar
-Dummy pricing and features created
