### ISSUE TITLE
Sentence Sweetener AI

### ISSUE THREAD

**Issue by bhanu-dev82** [apu52/METAVERSE#261]
### Project title
Sentence Sweetener AI

### Project Description
Enhance your sentences with a touch of humor! This web application leverages hugging face API to generate fresh humor.

### Web stack
HTML, CSS, JavaScript

### Screenshot(mandatory)
![Screenshot 2023-12-14 at 23-28-35 Sentence Sweetener AI](https://github.com/apu52/METAVERSE/assets/130910873/d9db282f-73b5-4eb6-b792-048b88a2b485)

#### Are you contributing under any open-source program ?
yes, Kwoc 2023

<hr/>

**Comment by apu52** [comment]
@bhanu-dev82 Welcome to METAVERSE!!!!!
Please go through contributing.md before contributing.
