### ISSUE TITLE
Apple-Website Clone

### ISSUE THREAD

**Issue by Dhammashree23** [apu52/METAVERSE#262]
### Project title 
Apple-Website Clone

### Project Description
Developed a website cloning project where the objective is to replicate the functionality and design of an existing Apple website. 

### Web stack
HTML,CSS,JavaScript

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/94229397/be6b453e-6a69-463a-9731-4ab38ba8cb5d)

#### Are you contributing under any open-source program ?
Yes, KWOC 2023

<hr/>

**Comment by apu52** [comment]
@Dhammashree23 Welcome to METAVERSE!!!!!
please go through contributing.md before contributing
