### ISSUE TITLE
Add new project: Detect Device Battery

### ISSUE THREAD

**Issue by Aritra203** [apu52/METAVERSE#273]
### Project title
Detect Device Battery

### Project Description
It's a project based on JavaScript which will detect your device battery health.

### Web stack
HTML
CSS
JavaScript

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/120680424/22b06fae-e9a0-402b-b931-efe53e2d6031)
![image](https://github.com/apu52/METAVERSE/assets/120680424/2ca4b9dc-cef1-4a3f-82b9-40873413b71c)

#### Are you contributing under any open-source program ?
KWOC 2023

<hr/>

**Comment by apu52** [comment]
@Aritra203 Welcome to METAVERSE!!!!!
Please go through contributing.md before contributing.

**Comment by apu52** [comment]
@Aritra203 your previous PR is closed. Now I have assigned you. You can submit your PR now.
