### ISSUE TITLE
Zoom Clone Using HTML,CSS 

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#278]
### Project title

I wish to create a Zoom  landing page clone using HTML, CSS Javascript
### Project Description

The project will have sign in, sign up and landing page. I will add functionality after learning more about backend development
### Web stack

HTML,CSS, Javascript

### Screenshot(mandatory)

N/A (Will work on project)
#### Are you contributing under any open-source program ?

CodePeak
<hr/>

**Comment by apu52** [comment]
@aindree-2005 I have assigned you. You can start working.
If you need any help you can reach out us in DC

**Comment by aindree-2005** [comment]
> @aindree-2005 I have assigned you. You can start working. If you need any help you can reach out us in DC

On it ! Glad to be able to contribute to this repo
