### ISSUE TITLE
A Book Review Website

### ISSUE THREAD

**Issue by RAGHAVS1304** [apu52/METAVERSE#28]
**Describe the project you want to add with tech stack**
A Book Review Website for students preparing for competitions or the general book readers also; the old readers of a book can post their reviews on this website and the new students will get help from this; I will be making the frontend of the website for now; Tech Stack :HTML, CSS, Javascript 

**Expected behavior**
 The website(responsive) will display the reviews submitted by various readers on it along with the book name and reviewer's name. Any user can read the review from the website and he/she will know about the book. The website will also show the famous books trending at present or
![Screenshot 2023-10-15 111827](https://github.com/apu52/METAVERSE/assets/119474871/54eaaebe-b96a-44e1-864d-3cdbe4d00171)
![Screenshot 2023-10-15 111845](https://github.com/apu52/METAVERSE/assets/119474871/9e358fe9-4844-42b8-b6d2-126f22808106)
![Screenshot 2023-10-15 111912](https://github.com/apu52/METAVERSE/assets/119474871/76bc6225-4d81-4106-9fcd-657682caa9d4)
 reviewed already, and much more. 

**Screenshots (optional)**
 I have added some screenshots of how it should look. Please review it.

**Additional context (optional )**
This problem has future scope as well; for example we can add a login page so that a user will register (or login) and then submit the review.

**Comment by apu52** [comment]
@RAGHAVS1304 Welcome to Metaverse!!!!!!!!!🥳
Thanks For raising the Issue. 👍

**Comment by apu52** [comment]
Please go through contribution.md file before contributing your project

**Comment by RAGHAVS1304** [comment]
Thanks sir for assigning this project.

**Comment by RAGHAVS1304** [comment]
> Please go through contribution.md file before contributing your project

Yes sir sure.

**Comment by apu52** [comment]
> Thanks sir for assigning this project.

hey bro @RAGHAVS1304 I am not a sir, only a fellow developer.
Please make more contributions in this repo & also make the PR accordingly

**Comment by RAGHAVS1304** [comment]
> hey bro @RAGHAVS1304 I am not a sir, only a fellow developer. Please make more contributions in this repo & also make the PR accordingly

😅Oh okay bro...

**Comment by RAGHAVS1304** [comment]
Bro in the development section(at right) of this issue, i am unable to see create branch option.
i have forked it already.

**Comment by apu52** [comment]
> Bro in the development section(at right) of this issue, i am unable to see create branch option. i have forked it already.

in your fork portion just click on brach (main) ----> then click on view all branches ---> then create tour branch clicking on the "New Branch" portion

**Comment by RAGHAVS1304** [comment]
Thanks bro👍

**Comment by RAGHAVS1304** [comment]
bro in the README file, i am just writing the description of this website, is it fine?
i have already sent the screenshots and other details

**Comment by apu52** [comment]
> bro in the README file, i am just writing the description of this website, is it fine? i have already sent the screenshots and other details

Please try to attach the ss in the readme file also, So that it will be helpful for other developers also.

**Comment by RAGHAVS1304** [comment]
> Please try to attach the same ss in the readme file also, So that it will be helpful for other developers also.

okay bro, i will do it

**Comment by RAGHAVS1304** [comment]
Bro first i am adding the home page section, and will keep adding other features after this PR, so please don't close the issue after first PR.

**Comment by RAGHAVS1304** [comment]
Thanks bro for your guidance and accepting the PR ,
now this issue is closed but i have to add other features as well soon, so please guide about it

**Comment by apu52** [comment]
> Thanks bro for your guidance and accepting the PR , now this issue is closed but i have to add other features as well soon, so please guide about it

try to raise another PR this time & don't hesitate to add features in your PR .
