### ISSUE TITLE
Add new project

### ISSUE THREAD

**Issue by Yash-Ainapure** [apu52/METAVERSE#280]
### Project title
Transactions Management website

### Project Description
A website created for tracking business of a wholesale seller. which helps tracking the transactions done. also could edit and delete the transactions and sort the transactions with specific dates

### Web stack
React , Firebase 

### Screenshot(mandatory)
![Screenshot (124)](https://github.com/apu52/METAVERSE/assets/136250383/98c33bfd-6b18-481a-9fa0-b6f5d168aea1)
![Screenshot (125)](https://github.com/apu52/METAVERSE/assets/136250383/786fb39a-a00f-4491-9f5b-1b74ca963626)
![Screenshot (126)](https://github.com/apu52/METAVERSE/assets/136250383/97b73fd2-d318-4631-843a-3f0f44fd9bd9)

#### Are you contributing under any open-source program ?
Codepeak '23

<hr/>

**Comment by apu52** [comment]
@Yash-Ainapure Welcome to METAVERSE!!!
Please go through contributing.md before contributing.
