### ISSUE TITLE
Feature_Request:Redesign Metaverse Contact Us Page

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#281]
**Is your feature request related to a problem? Please describe.**

The current Contact Us page lacks proper css. I wish to work on it and make it look similar to home page

**Describe the solution you'd like**

A proper detail of the repo founder and the maintainer along with social media handles and a form to submit querries

**Describe alternatives you've considered**

Use HTML, CSS, Javascript 

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

CodePeak/KWOC

**Comment by apu52** [comment]
@aindree-2005 I am assigning you .
Can you also work on the about page ??

**Comment by aindree-2005** [comment]
> @aindree-2005 I am assigning you . Can you also work on the about page ??

Sure! I'll do both then . I can get the design for Contact Us confirmed first and use it as reference for About Us?

**Comment by apu52** [comment]
> > @aindree-2005 I am assigning you . Can you also work on the about page ??
> 
> Sure! I'll do both then . I can get the design for Contact Us confirmed first and use it as reference for About Us?

you can do that. I have assigned you
Happy coding!!!
