### ISSUE TITLE
Chess Board Game

### ISSUE THREAD

**Issue by Mayank77maruti** [apu52/METAVERSE#286]
### Project title
Chess board game.

### Project Description
A multiplayer chess game.

### Web stack
1.HTML
2.CSS
3.JAVASCRIPT

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

<hr/>

**Comment by shruti-sen2004** [comment]
please provide a screenshot of the project.

**Comment by Mayank77maruti** [comment]
![chess](https://github.com/apu52/METAVERSE/assets/125661248/494af8f6-7196-43ff-b230-f030969edb2c)

**Comment by shruti-sen2004** [comment]
@Mayank77maruti  Welcome to METAVERSE!!!!!!
Please go through contributing.md before contributing.
