### ISSUE TITLE
Temparature_Converter

### ISSUE THREAD

**Issue by paulsuryanshu** [apu52/METAVERSE#29]
**Describe the project you want to add with tech stack**
This is the project which helps us to convert the temperature...

**Expected behavior**
convert any kind of temperature

**Screenshots (optional)**

**Additional context (optional )**

**Comment by apu52** [comment]
The repo is already present in this repo. So , I can't be able to assign it!
Please try to add another contribution!!
Happy Coding

**Comment by paulsuryanshu** [comment]
ossum
