### ISSUE TITLE
Feature_Request: Battery Detector UI design

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#292]
**Is your feature request related to a problem? Please describe.**

Add "time remaining" to battery detector
**Describe the solution you'd like**

Use HTML, CSS, Javascript to add "Time remaining to battery detector" for better use
**Describe alternatives you've considered**

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

CodePeak, KWOC

**Comment by apu52** [comment]
@aindree-2005 Can you provide some of the prototype SS/video of the implementations you want to add??

**Comment by aindree-2005** [comment]
![Add a subheading (2)](https://github.com/apu52/METAVERSE/assets/68018372/9328829a-44e3-4ea9-bb74-a9597f2563ea)
@apu52 this is kind of the idea for what I want to add. Currently only the battery percentage is shown
