### ISSUE TITLE
UNSPLASH API PROJECT

### ISSUE THREAD

**Issue by GAGANRAGHAV** [apu52/METAVERSE#293]
### Project title
UNSPLASH API PROJECT

### Web stack
1.html
2.css
3.javascript
4.api handling

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/120806356/b63d9e13-3373-462f-87ee-5a6ed390c76f)

### Additional Context(mandatory)
project which can fetch you infinite images from unsplash .

#### Are you contributing under any open-source program ?
COdepeak'23

<hr/>

**Comment by apu52** [comment]
Sorry @GAGANRAGHAV we already have API image generator in this repo.
See you soon with new projects
Happy coding!!!!!

**Comment by GAGANRAGHAV** [comment]
i don't see any...it is ai image generator😢

**Comment by apu52** [comment]
> i don't see any...it is ai image generator😢

as it was similar to Image generator . I have closed this issue. Ok I am assigning you.
