### ISSUE TITLE
Google_Drive_Clone

### ISSUE THREAD

**Issue by paulsuryanshu** [apu52/METAVERSE#30]
**Describe the project you want to add with tech stack**
This is a clone of a google drive

**Expected behavior**
Perfectly looks like a google drive

**Screenshots (optional)**

**Additional context (optional )**

**Comment by apu52** [comment]
@paulsuryanshu Thanks For raising the Issue. 👍

**Comment by apu52** [comment]
Please go through contribution.md file before contributing your project
