### ISSUE TITLE
Tetris Game

### ISSUE THREAD

**Issue by Mayank77maruti** [apu52/METAVERSE#304]
### Project title
Tetris Game

### Project Description
Tetris is a classic tile-matching puzzle video game.As the game progresses, the tetrominoes fall at an increasing speed, making it more challenging to place them strategically.

### Web stack
HTML , CSS AND JavaScript

### Screenshot(mandatory)
![tetrispic](https://github.com/apu52/METAVERSE/assets/125661248/b6c0803f-48cb-4ce7-b563-a4f19434928d)

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

**Comment by apu52** [comment]
@Mayank77maruti Welcome to METAVERSE!!!!!!
Please go through cntributing.md before contributing.
