### ISSUE TITLE
Ping Pong Game

### ISSUE THREAD

**Issue by Mayank77maruti** [apu52/METAVERSE#308]
### Project title
Ping Pong Game

### Project Description
Ping pong, also known as table tennis, is a popular indoor sport in which two or four players hit a lightweight ball back and forth across a table using small, handheld rackets.

### Web stack
HTML , CSS AND JavaScript.

### Screenshot(mandatory)

![Screenshot 2023-12-18 143255](https://github.com/apu52/METAVERSE/assets/125661248/c3f0e18d-a47c-45da-a3ed-96662b980150)

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

**Comment by Mayank77maruti** [comment]
Hey @shruti-sen2004 , I have open a pull request regarding this project please do check it out. Thank You.

**Comment by shruti-sen2004** [comment]
> Hey @shruti-sen2004 , I have open a pull request regarding this project please do check it out. Thank You.

@Mayank77maruti your PR has a merge confict please resolve it. Then the assigned moderator will merge it.

**Comment by Mayank77maruti** [comment]
Hey @shruti-sen2004 , I have resolved the merge conflict.

**Comment by shruti-sen2004** [comment]
@Mayank77maruti your PR is under @5h0ov please consut with him. Also I can see he has mentioned some issues with your PR. For any other quarries consult with your PR moderator. It will be much helpfull for you.
