### ISSUE TITLE
Add new project / Blogging Website

### ISSUE THREAD

**Issue by AaadityaG** [apu52/METAVERSE#312]
### Project title
The Blogging Website

### Project Description
This is the blogging website which gets in use to write a blogs. It is multipage blogging website.

### Web stack
HTML5 / CSS3 / JS

### Screenshot(mandatory)

![p9](https://github.com/apu52/METAVERSE/assets/114663382/2eb2e50b-b62c-47ab-a888-020fb256e44c)

### Additional Context(mandatory)
This is specially made for practising html / css and multipage structure of websites.
#### Are you contributing under any open-source program ?

YES / Codepeak and KWoC
<hr/>

**Comment by apu52** [comment]
@AaadityaG Don't make more than 2 issues at a time. Please follow the rules mentioned in contributing.md

**Comment by AaadityaG** [comment]
Will never do again..

**Comment by apu52** [comment]
> @AaadityaG Don't make more than 2 issues at a time. Please follow the rules mentioned in contributing.md

I will assign you this issue after the completion of previous 2 PR

**Comment by AaadityaG** [comment]
Ok

**Comment by AaadityaG** [comment]
Now you can assign this one!

**Comment by apu52** [comment]
> Now you can assign this one!

I have assigned you.
You can work on this now.
Happy Coding!!!!!
