### ISSUE TITLE
Add new project / Business Website with Parallex Effect

### ISSUE THREAD

**Issue by AaadityaG** [apu52/METAVERSE#313]
### Project title
Business Website with Parallex Effect

### Project Description
This website is ready to use for business with super cool parallex effect.

### Web stack
HTML5 CSS3 JS

### Screenshot(mandatory)

![Parallex Website - Google Chrome 18-12-2023 06_13_45 PM](https://github.com/apu52/METAVERSE/assets/114663382/8e63043a-cf22-451f-8a6f-c6306a375c9d)

### Additional Context(mandatory)
This is made for practising the traditional parallex effects for website but with usage of it.
#### Are you contributing under any open-source program ?

YES / Codepeak + KWoC
<hr/>

**Comment by apu52** [comment]
@AaadityaG Don't make more than 2 issues at a time. Please follow the rules mentioned  in contributing.md

**Comment by apu52** [comment]
& PARALLAX based website is already present in this repo.
