### ISSUE TITLE
new project as Farmers Services Website

### ISSUE THREAD

**Issue by Sami3160** [apu52/METAVERSE#319]
### Project title
Farmers services website

### Project Description
I want to add a project which is related to farmers services which i recently made...Well services are like calculating fertilizer amount, getting current news, getting known to farming knowledge, access to recent government schemes, a map which would locate to nearby shops related to farming and information page which shows crops information based on locality of specific region etc. And website also have many cards that can make user understand about controls, instructions for calculation are mentioned, very simplistic design with some custom made photoshopped images as banners. Language of page can be changed into 4 languages like english, hindi, marathi and kannada.

### Web stack
js, html, custom css, bootstrap, nodejs, Pug as alternative of classic html, express for routing, youtube api, google language api, nivo css, and much more 

### Screenshot(mandatory)
![Screenshot (138)](https://github.com/apu52/METAVERSE/assets/110652247/81679528-0cce-4840-b0f3-dc9068efe181)
![Screenshot (137)](https://github.com/apu52/METAVERSE/assets/110652247/f458768c-6c8d-4ca4-98e0-123ec2859b06)
![Screenshot (136)](https://github.com/apu52/METAVERSE/assets/110652247/c9e4d476-6216-4584-a4b5-e1e013844ab3)
![Screenshot (135)](https://github.com/apu52/METAVERSE/assets/110652247/35a723ee-8444-4110-8477-4eeec2573d5a)
![Screenshot (134)](https://github.com/apu52/METAVERSE/assets/110652247/89bdb64b-e658-4698-b263-5dc1166ecc35)

### Additional Context(mandatory)
Total their are 5 or more major modules, the project quit big in size, and it is in node js, so i still dont know how to integrate it with your project, UI is quiet mid, coz I'm not a frontend specialist, but most of work is done in backend like transferring request and crops data, and other send statics and etc.

#### Are you contributing under any open-source program ?
code peak 2023

<hr/>

**Comment by Sami3160** [comment]
> > hey @apu52 can u tell me how can i integrate my nodejs project here?
> 
> no need to upload the module file as that can't be deployed. But try to add a prototype video of your project & follow all the guidelines mentioned in CONTRIBUTING.md

ok sir

**Comment by apu52** [comment]
> > > hey @apu52 can u tell me how can i integrate my nodejs project here?
> > 
> > 
> > no need to upload the module file as that can't be deployed. But try to add a prototype video of your project & follow all the guidelines mentioned in CONTRIBUTING.md
> 
> ok sir

Don't call me sir bro. Waiting to see your project
