### ISSUE TITLE
Footer with wave animation

### ISSUE THREAD

**Issue by singhcoder694** [apu52/METAVERSE#322]
### Project title
Wavy Footer

### Project Description
Footer background is made like waves of river to make UI expericence better.

### Web stack
HTML,CSS

### Screenshot(mandatory)
<img width="960" alt="Screenshot 2023-12-19 091045" src="https://github.com/apu52/METAVERSE/assets/114601400/bd106292-2a16-4b90-937e-ccae247fb605">

### Additional Context(mandatory)

Footer with Waves in background.
#### Are you contributing under any open-source program ?

CodePeak'23
<hr/>

**Comment by shruti-sen2004** [comment]
@singhcoder694 can be a little more specific where do you want to add the footer ....As our main website already has it ....do you want to add it to any specific projects?? please mention that....

**Comment by singhcoder694** [comment]
Yes, I have added this project so that if anyone wants to add animation to website's footer they can use or create footer like this (for purpose of use in other website project)
