### ISSUE TITLE
QR Id Card Generator

### ISSUE THREAD

**Issue by ashish-bazad** [apu52/METAVERSE#33]
**Describe the project you want to add with tech stack**
I will code the project in HTML, CSS and, JS

**Expected behavior**
Users will be able to input their name and id and a ID card with updated QR will be generated

**Screenshots (optional)**

**Additional context (optional )**

@apu52 Please assign this issue to me.

**Comment by apu52** [comment]
@ashish-bazad Welcome to Metaverse!!!!!!!!!🥳
Thanks For raising the Issue. 👍

**Comment by apu52** [comment]
Please go through contibution.md file before contributing

**Comment by ashish-bazad** [comment]
> Please go through contibution.md file before contributing

@apu52 Sir I have gone through contribute.md file and generated a Pull Request, please accept 😊
