### ISSUE TITLE
A website made for delivering food orders

### ISSUE THREAD

**Issue by Sami3160** [apu52/METAVERSE#335]
### Project title
Omnifood an imaginary company who delivers food in mass order

### Project Description
This website is about providing food delivery services, acting as an interface between restaurants and customers, Its is a static website, it displays the information about the akp of the omnifoods and accept login.

### Web stack
js, html, css

### Screenshot(mandatory)
![Screenshot (160)](https://github.com/apu52/METAVERSE/assets/110652247/8697296c-a39e-43a5-b4b1-0e03cef3fd1e)

### Additional Context(mandatory)
Well it is a static website, made in first year so it isnt that interactive and doesnt have much logic but the UI is pretty decent. I tried my best to have a professional look to website.
#### Are you contributing under any open-source program ?

codepeak 2023
<hr/>

**Comment by apu52** [comment]
@Sami3160 We already have food ordering website in this repo
Thank you for raising this issue but it can't be assigned.
