### ISSUE TITLE
Realignment of Dark mode toggle button

### ISSUE THREAD

**Issue by KeyurGK** [apu52/METAVERSE#340]
**Describe the bug**

The dark mode toggle button for mobile viewport is seen to be overlapping HOME button, which troubles the user in selecting the latter.

**Expected behavior**

The toggle button should be positioned in the top most row, followed by the nav buttons.

**Screenshots (Mandatory)**

<img width="170" alt="image" src="https://github.com/apu52/METAVERSE/assets/56074740/24489039-2e51-4b8f-aa7c-0ae27bafdcb1">

**Additional context (Mandatory )**
The overlapping of the toggle button, creates a bad UX. When the user is in about page, it is difficult to navigate to home as clicking in it leads to just mode toggling.
***Are you contributing under any open-source program ?***

KWOC

**Comment by apu52** [comment]
@KeyurGK Welcome to METAVERSE!!!!!
Please go through contributing.md before contributing.
