### ISSUE TITLE
stone paper scissors game

### ISSUE THREAD

**Issue by Sami3160** [apu52/METAVERSE#342]
### Project title

stone paper scissors game
### Project Description

it will be a game in html, css and for logic building js will be used or ts
### Web stack
html, css, ts, js

### Screenshot(mandatory)

NA. it is not completed yet so i have no screenshot

### Additional Context(mandatory)
A webpage with a game in it called stone, paper scissor 
#### Are you contributing under any open-source program ?

codepeak 2023
<hr/>

**Comment by apu52** [comment]
@Sami3160 It is already present in our repo.
Sorry to close this issue.
