### ISSUE TITLE
Feature_Request:Dark mode toggle feature in Quote generator

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#349]
**Is your feature request related to a problem? Please describe.**

Having a toggle button for switching between dark and light mode will be great for the users.

**Describe the solution you'd like**

I want to add a toggle button and dark mode with the help of CSS and JS.
Kindly assign me.
![Screenshot (36)](https://github.com/apu52/METAVERSE/assets/127030695/e36f1239-f551-40e4-9ef9-e758e6b2ce3f)

***Are you contributing under any open-source program ?***

Yes under KWOC.

**Comment by Albert-2** [comment]
hey @Abhishek-465 
I would like to contribute to this issue 
can you please assign me the same
thank you...!!

**Comment by apu52** [comment]
> hey @Abhishek-465 I would like to contribute to this issue can you please assign me the same thank you...!!

The issue is already assigned. You can create a new Issue you want to work on.
