### ISSUE TITLE
Tindog: A startup Website

### ISSUE THREAD

**Issue by RAGHAVS1304** [apu52/METAVERSE#35]
**Describe the project you want to add with tech stack**
Tindog, a startup website; it has best priced plans for entertainment of dogs of different breeds; it has matches, messeges etc.
![Screenshot 2023-10-16 143401](https://github.com/apu52/METAVERSE/assets/119474871/cbbde600-f782-45bf-88c5-5a38b4788ae3)
![Screenshot 2023-10-16 143420](https://github.com/apu52/METAVERSE/assets/119474871/dae4e9a4-e5f2-45fb-b893-ac9ee8dcb9cb)
![Screenshot 2023-10-16 143431](https://github.com/apu52/METAVERSE/assets/119474871/712e4765-18dc-4027-a2bb-fc92d8304686)

Tech stack: Bootstrap is used and CSS animations are added

**Expected behavior**
The website will have separate sections for title, features, testimonial, pricing, footer, along with animations using css.

**Screenshots (optional)**
I have added some screenshots.

**Additional context (optional )**
This can be taken as a project and can be build upon in future; many more features can be added.

**Comment by RAGHAVS1304** [comment]
Bro, please assign this project to me.
Thanks

**Comment by apu52** [comment]
@RAGHAVS1304 thank you for raising the issue

**Comment by apu52** [comment]
It will be considered as a valuable contribution in HACTOBERFEST'23
If it's not considered then let me know I will add the label again...

**Comment by RAGHAVS1304** [comment]
Okay bro👍, thanks for confirmation

**Comment by apu52** [comment]
> I Love Dogs nothing better than dog tinder I am fairly new to contributing to open source and this would be a good beginning for me . I would like to be assigned this issue and a guide to help me through the process

@Atheke you can simply raise another issue on which you want to work on & try to gather the ideas from the open source.
