### ISSUE TITLE
Candy Crush

### ISSUE THREAD

**Issue by Mayank77maruti** [apu52/METAVERSE#350]
### Project title

Candy Crush

### Project Description

Candy Crush is a popular mobile puzzle game that challenges players to match colorful candies in various combinations to progress through hundreds of levels.

### Web stack

HTML , CSS AND JAVASCRIPT

### Screenshot(mandatory)

![Screenshot 2023-12-20 124943](https://github.com/apu52/METAVERSE/assets/125661248/5c448d9c-cb1c-4d52-99f1-934153297aed)

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

**Comment by apu52** [comment]
@Mayank77maruti Please don't make any PR until & unless you get assigned . Now you can submit your PR.

**Comment by Mayank77maruti** [comment]
@apu52 , so sorry for doing so , it would not be repeated.
