### ISSUE TITLE
GitHub API to fetch Contributors Detail of Folks

### ISSUE THREAD

**Issue by singhcoder694** [apu52/METAVERSE#351]
### Project title
GitHub API

### Project Description
It is a project useful in getting list of Contributors and details of their folked repos.

### Web stack
HTML, CSS, JS, API(GitHub API)

### Screenshot(mandatory)
<img width="360" alt="Screenshot 2023-12-20 125220" src="https://github.com/apu52/METAVERSE/assets/114601400/11786721-aa88-4deb-8038-4375e6e0c2cd">
<img width="358" alt="Screenshot 2023-12-20 125303" src="https://github.com/apu52/METAVERSE/assets/114601400/0f6f25bd-fd79-4e06-a8d5-33cf346484f7">

#### Are you contributing under any open-source program ?
CodePeak'23

<hr/>

**Comment by apu52** [comment]
@singhcoder694 That's really a nice idea to work on!
