### ISSUE TITLE
Hangman game

### ISSUE THREAD

**Issue by GAGANRAGHAV** [apu52/METAVERSE#352]
### Project title
HANGMAN GAME

### Web stack
HTML, CSS , JAVASCRIPT

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/120806356/37c664e7-70e8-40ad-889d-24385e3fa561)

### Additional Context(mandatory)

A game to guess the word
#### Are you contributing under any open-source program ?
codepeak23

**Comment by anuragsingh132200** [comment]
can i take this up

**Comment by apu52** [comment]
> can i take this up

No. This issue is already assigned. You can raise a new issue on a new topic you want to work on
