### ISSUE TITLE
Feature_Request: Improve UI of Country Guide

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#354]
**Is your feature request related to a problem? Please describe.**

The current  country guide looks very plain. I wish to design it to create a design in sync with the theme
**Describe the solution you'd like**

Use HTML, CSS, Javascript to improve style
**Describe alternatives you've considered**

None as such

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***
Codepeak

**Comment by apu52** [comment]
@aindree-2005 Can you share the SS of the features you want to work on?

**Comment by aindree-2005** [comment]
![Screenshot (333)](https://github.com/apu52/METAVERSE/assets/68018372/06e9f152-1233-4001-8ef2-30fde6a8af39)
@apu52 the background of this page
