### ISSUE TITLE
Clock Animation

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#355]
### Project title

Clock Animation using HTML,CSS, Javascript
### Project Description

I wish to create an animated clock that's functional using html, css, javascript
### Web stack

html,css, js
### Screenshot(mandatory)

N/A (haven't started work yet)

#### Are you contributing under any open-source program ?

Codepeak
<hr/>

**Comment by apu52** [comment]
@aindree-2005 Thank u for raising this issue.
But we already have this project in our repo.
