### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#358]
### Project title

BMI calculator based on height and weight input
### Project Description

project calculates bmi of user
### Web stack

html,css, js

### Screenshot(mandatory)

N/A (not done yet)

#### Are you contributing under any open-source program ?

Codepeak, kwoc
<hr/>

**Comment by apu52** [comment]
@aindree-2005 Share some SS when you complete the enhancement.

**Comment by aindree-2005** [comment]
![Uploading Screenshot (340).png…]()
@apu52 here's the ss
