### ISSUE TITLE
Add new project / Qr Code Generator

### ISSUE THREAD

**Issue by AaadityaG** [apu52/METAVERSE#363]
### Project title
Qr Code Generator

### Project Description
This is the tool through with user can generate its qr code for any text, links or passwords

### Web stack

HTML / CSS / JS

### Screenshot(mandatory)
![Qr Code Generator](https://github.com/apu52/METAVERSE/assets/114663382/af61974d-a6ee-448e-b6d9-772bfbbe2399)

### Additional Context(mandatory)
A user can also get this color in different size and colors.
#### Are you contributing under any open-source program ?

YES / Codepeak & KWoC

<hr/>

**Comment by apu52** [comment]
@AaadityaG We already have this kind of generator in our repo.
Sorry for closing this issue.

**Comment by AaadityaG** [comment]
@apu52 But it is a QR Card Generator, also there is no way a user can use cause it has no download of print btn. Also it specifically only generating a name not even a id of an userID of url that we are giving. But its Ok!

**Comment by apu52** [comment]
> @apu52 But it is a QR Card Generator, also there is no way a user can use cause it has no download of print btn. Also it specifically only generating a name not even a id of an user of url that user is giving. But its Ok!

you can add those features in that project

**Comment by AaadityaG** [comment]
ok will create new issue
