### ISSUE TITLE
Upcoming CodeForces Contests Website

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#380]
### Project title

Code-Force Contests
### Project Description

uses codeforces api to fetch list of next contests
### Web stack

html,css, js, codeforces api

### Screenshot(mandatory)

Not done yet

#### Are you contributing under any open-source program ?

codepeak, kwoc
<hr/>

**Comment by apu52** [comment]
@aindree-2005 can you please give us the SS of the the project you want to work on?

**Comment by aindree-2005** [comment]
> @aindree-2005 can you please give us the SS of the the project you want to work on?

I haven't started working on it yet. I'll send it when it's done then

**Comment by aindree-2005** [comment]
![Uploading Screenshot (348).jpg…]()


It'll be like this but with added features @apu52

**Comment by apu52** [comment]
> ![Screenshot (348)](https://private-user-images.githubusercontent.com/68018372/292256492-65408342-e6e1-4256-b42a-7e47157f30c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzUxODYsIm5iZiI6MTcwMzE3NDg4NiwicGF0aCI6Ii82ODAxODM3Mi8yOTIyNTY0OTItNjU0MDgzNDItZTZlMS00MjU2LWI0MmEtN2U0NzE1N2YzMGMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE2MDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZmFiN2M1Nzg4MzhkOTZmZjkxZDgzNDU5MjhiODVlNzVkZmFmNjY2OTI0NmViYWE0ZDBjZWJmNGMxNTJjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D0-WQSJbbZRNJUgLId4qY2mRE3c_5exCdoJKjAP2YV0)
> 
> It'll be like this but with added features @apu52

ok you can work on this .I have already assigned you
