### ISSUE TITLE
Furniture website with cart feature

### ISSUE THREAD

**Issue by drockparashar** [apu52/METAVERSE#384]
### Project title
Furniture Website

### Project Description
It is a shopping website with cart feature.

### Web stack
HTML, CSS, Javascript

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/118686637/11805b72-ea68-4df5-ab51-6f4ed84f507b)

#### Are you contributing under any open-source program ?
Codepeak 23

<hr/>

**Comment by apu52** [comment]
@drockparashar the whole code is copied.
All points regarding this PR will be deducted.
