### ISSUE TITLE
GitHub Profile Finder

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#393]
### Project title

Github profile finder
### Project Description

Uses api to fetch github user profile info with stats
### Web stack

html, css, js, api

### Screenshot(mandatory)

 
 Not finished designing yet, but will be done ASAP

#### Are you contributing under any open-source program ?

Codepeak, KWOC
<hr/>

**Comment by apu52** [comment]
@aindree-2005 Don't raise more than 2 issues at a time.
Please follow the rules mentioned in Contributing.md
I will assign you this issue after the completion of  your last PR.

**Comment by aindree-2005** [comment]
> @aindree-2005 Don't raise more than 2 issues at a time. Please follow the rules mentioned in Contributing.md I will assign you this issue after the completion of your last PR.

@apu52 can I work on this now?

**Comment by apu52** [comment]
> > @aindree-2005 Don't raise more than 2 issues at a time. Please follow the rules mentioned in Contributing.md I will assign you this issue after the completion of your last PR.
> 
> @apu52 can I work on this now?

you can definitely start working on this project. But I will assign you this after your last PR got merged.

**Comment by aindree-2005** [comment]
> > > @aindree-2005 Don't raise more than 2 issues at a time. Please follow the rules mentioned in Contributing.md I will assign you this issue after the completion of your last PR.
> > 
> > 
> > @apu52 can I work on this now?
> 
> you can definitely start working on this project. But I will assign you this after your last PR got merged.

Got it!

**Comment by jatking03** [comment]
@aindree-2005 could you assign me this issue?

**Comment by apu52** [comment]
@aindree-2005 I have assigned you

**Comment by apu52** [comment]
> @aindree-2005 could you assign me this issue?

This issue is already assigned. you can work on a new issue
