### ISSUE TITLE
Health Dashboard

### ISSUE THREAD

**Issue by aindree-2005** [apu52/METAVERSE#394]
### Project title

Health Dashboard App
### Project Description

Dashboard to keep track of user's health stats
### Web stack

html,css, javascript

### Screenshot(mandatory)

(not started yet, but inspired by this design for student dashboard I made)
[Welcome_Name (3).pdf](https://github.com/apu52/METAVERSE/files/13745097/Welcome_Name.3.pdf)

#### Are you contributing under any open-source program ?

Codepeak 2023
<hr/>

**Comment by apu52** [comment]
@aindree-2005 Don't raise more than 2 issues at a time.
Please follow the rules mentioned in Contributing.md
I will assign you this issue after the completion of  your last PR.

**Comment by aindree-2005** [comment]
> @aindree-2005 Don't raise more than 2 issues at a time. Please follow the rules mentioned in Contributing.md I will assign you this issue after the completion of your last PR.
Oh sorry I missed it. My bad. Thank you for considering these as Pending!
