### ISSUE TITLE
Codeforces API to fetch Contsests, Questions and User Detail

### ISSUE THREAD

**Issue by singhcoder694** [apu52/METAVERSE#411]
### Project title
Codeforces API

### Project Description
It is a website with full use of API provided by codeforces. It contains detail of future as well as past contests. It also has section to filter question on basis of tags, difficulty, question code. It is also able to find users detail based on their username.

### Web stack
- HTML, CSS
- EJS
- NODE and EXPRESS
- Codeforces API
- API call using AXIOS

### Screenshot(mandatory)

#  CONTEST PAGE
<img width="946" alt="Screenshot 2023-12-22 192504" src="https://github.com/apu52/METAVERSE/assets/114601400/a2c9d628-2e50-4a04-b6a8-e751a0d0f85f">
<img width="960" alt="Screenshot 2023-12-22 192512" src="https://github.com/apu52/METAVERSE/assets/114601400/20851088-9583-4bcf-a340-6ef943b22a0e">
<img width="960" alt="Screenshot 2023-12-22 192521" src="https://github.com/apu52/METAVERSE/assets/114601400/aba1de7c-1afc-4377-96f5-e7198275f872">

#  QUESTION FILTER PAGE
<img width="960" alt="Screenshot 2023-12-22 192528" src="https://github.com/apu52/METAVERSE/assets/114601400/3b31e3ac-ddc6-4dbf-8d9f-28ba5aa11c6f">

<img width="960" alt="Screenshot 2023-12-22 192602" src="https://github.com/apu52/METAVERSE/assets/114601400/2fe42261-1a91-4ca4-bfbe-af65605c1c38">

#  QUESTION FILTER RESULT 
<img width="958" alt="Screenshot 2023-12-22 192630" src="https://github.com/apu52/METAVERSE/assets/114601400/b57e7d36-2459-49a0-a6c5-17e7b2fc2318">
<img width="958" alt="Screenshot 2023-12-22 192636" src="https://github.com/apu52/METAVERSE/assets/114601400/15c68d9b-696d-447e-b99f-63da7f651354">

#  USER SEARCH PAGE
<img width="960" alt="Screenshot 2023-12-22 192546" src="https://github.com/apu52/METAVERSE/assets/114601400/1ef7d8ff-b84d-4dcf-a7a0-c175e7756113">

### Additional Context(mandatory)

**It is full fledged website which can be made using the data from codeforces and can be used by any person using codeforces for all kind of work without even going to main site.**

#### Are you contributing under any open-source program ?
CodePeak'23

<hr/>

**Comment by singhcoder694** [comment]
@apu52 @ Can we submit full fledged website codes written in XML  language?

**Comment by apu52** [comment]
> @apu52 Can we submit website codes written in XML language?

Yes you can
