### ISSUE TITLE
Adding Navbar, About Section and Menu Page and Contact Us Page for Food Ordering Website

### ISSUE THREAD

**Issue by PSS2134** [apu52/METAVERSE#413]
Implementing New Navbar, Adding About Section, Contact Us page, Menu Page @apu52

**Comment by apu52** [comment]
@PSS2134 Welcome to METAVERSE!!!!!
Please Raise your issue with proper Issue template which is already there with all the fields properly filled.

**Comment by PSS2134** [comment]
Please Assign me this issue @apu52

**Comment by apu52** [comment]
> Please Assign me this issue @apu52 Under Codepeak 23

Please Raise your issue with proper Issue template which is already there with all the fields properly filled.
