### ISSUE TITLE
Chat Application

### ISSUE THREAD

**Issue by NandishM0618** [apu52/METAVERSE#421]
### Project title

An Chat App

### Project Description

An chat app with a real time messaging, user Authentication, media sharing, search user functionality etc.
### Web stack

React js
Tailwind css
firebase 

### Screenshot(mandatory)

![issue29](https://github.com/apu52/METAVERSE/assets/100901899/9e5bfe72-cb5b-48e1-8190-7f8157155bbb)

### Additional Context(mandatory)
an chat app with real time messaging and sharing media etc.
#### Are you contributing under any open-source program ?

Yes, codepeak'23
<hr/>

**Comment by NandishM0618** [comment]
@apu52 I didn't receive any points for this pull request please see to that https://github.com/apu52/METAVERSE/pull/404#event-11329333585

**Comment by apu52** [comment]
> @apu52 I didn't receive any points for this pull request please see to that [#404 (comment)](https://github.com/apu52/METAVERSE/pull/404#event-11329333585)

Point already given. Please check it.

**Comment by NandishM0618** [comment]
Thank you
