### ISSUE TITLE
Dental Website

### ISSUE THREAD

**Issue by Mayank77maruti** [apu52/METAVERSE#427]
### Project title
Dental Website

### Project Description
A website for dentist to promote their shop .

### Web stack

HTML , CSS AND JAVASCRIPT

### Screenshot(mandatory)
![DENTISTWEB](https://github.com/apu52/METAVERSE/assets/125661248/05d817b2-2dbf-4561-bf32-40bd1cfce99d)

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

**Comment by Dhaneshwar7** [comment]
can i contribute in this project .. i have read contributing document(litte bit confused) , first time contributing in others project ,, how can i do .

**Comment by apu52** [comment]
> can i contribute in this project .. i have read contributing document(litte bit confused) , first time contributing in others project ,, how can i do .

@Dhaneshwar7 Welcome to METAVERSE!!!!!!!!
You can easily contribute in this repo by fixing bugs , enhance the existing projects or can easily contribute your front-end web projects here.
All the rules are properly mentioned in CONTRIBUTING.md file
