### ISSUE TITLE
Daily Diary Entry WebApp

### ISSUE THREAD

**Issue by HemantKumar01** [apu52/METAVERSE#429]
### Project title
Daily Diary Entry Website

### Project Description
A website with minimalist eye soothing frontend where you can log your daily life, like a diary entry. 
The logs will be stored in the form of json and will be shown when you come back.

### Web stack
HTML,
CSS
JS
Nodejs

### Screenshot(mandatory)
![Screenshot 2023-12-23 200607](https://github.com/apu52/METAVERSE/assets/71439585/76796551-b276-4024-a0a6-a1b8ec654c49)

#### Are you contributing under any open-source program ?
Yes, Codepeak 2023

<hr/>

**Comment by Dhaneshwar7** [comment]
how i can contribute on this project ???

**Comment by apu52** [comment]
> how i can contribute on this project ???

You can enhance the project or fix the bugs after this PR is properly merged in this repo
