### ISSUE TITLE
Add a Food Ordering Website

### ISSUE THREAD

**Issue by kshitizvardhan** [apu52/METAVERSE#43]
**Describe the project you want to add with tech stack**
It is a website where you can order your food from nearest outlets in your area. Tech Stack used in this is only HTML and CSS.

**Comment by kshitizvardhan** [comment]
Please assign this issue to me.
Thank you.

**Comment by apu52** [comment]
Hello @kshitizvardhan ... welcome to Metaverse !!!!!🙏🎉

**Comment by apu52** [comment]
Please go through contributing.md
