### ISSUE TITLE
NETFLIX CLONE

### ISSUE THREAD

**Issue by itsmeabhishek03** [apu52/METAVERSE#436]
### Project title
NETFLIX CLONE

### Project Description
NETFLIX CLONE APP - It is a web app clone of netflix frontend with smooth slider and dark/ligth mode functionalities

### Web stack
HTML, CSS, JAVASCRIPT

### Screenshot(mandatory)
Dark Mode
![image](https://github.com/apu52/METAVERSE/assets/104294494/fcdeaaab-d2c9-480a-9ace-76533dc02d04)

Light Mode
![image](https://github.com/apu52/METAVERSE/assets/104294494/bfb811aa-158c-4eb1-9067-0987a78c2774)

### Additional Context(mandatory)
Its is frontend project with pleasing ui/ux

#### Are you contributing under any open-source program ?
codepeak'23 and JWOC

<hr/>

**Comment by apu52** [comment]
@itsmeabhishek03 Welcome to METAVERSE!!!!!!
But we already have this project in our repo. Sorry this issue can't be assigned.
Instead you can add more features in the existed project.
