### ISSUE TITLE
Online Gym (Excercise Guide)

### ISSUE THREAD

**Issue by maadi7** [apu52/METAVERSE#442]
### Project title
Excercise Guide

### Project Description
Its a excercise guide for every age group who cannot or do not to hire a trainer. making it convienet by integrating gifs, youtube video links and user-friendly UI/UX.

### Web stack
React
CSS
Material-UI
Javascript
Rapid-API

### Screenshot(mandatory)

![gymsite1](https://github.com/apu52/METAVERSE/assets/95737654/f1c022dd-363a-49cc-b58b-5d6db7c4d03a)

![gymsite2](https://github.com/apu52/METAVERSE/assets/95737654/27fdae64-a84e-408c-9483-608c775c7e48)

![gymsite3](https://github.com/apu52/METAVERSE/assets/95737654/c0ed748a-525a-419f-8c4f-937dcb8e243e)

![gymsite4](https://github.com/apu52/METAVERSE/assets/95737654/7e1945ea-e75f-4b58-9cfd-d97b1fe9afe0)

### Additional Context(mandatory)
Its a project which extensively uses the Rapid-API and MateralUI making pleasing UI/UX.

#### Are you contributing under any open-source program ?
Codepeak23

<hr/>

**Comment by apu52** [comment]
@maadi7 Welcome to METAVERSE!!!!!!!
We already have a gym website in our repo. But your prototype looks really good. So excited to see your PR.
