### ISSUE TITLE
Math-Sprint-app is not working in desktop.

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#443]
**Describe the bug**

The start round button is not visible in desktops due to restriction in overflow.  

**Expected behavior**

The start round button should be visible to start the game.

**Screenshots (Mandatory)**

![Screenshot (47)](https://github.com/apu52/METAVERSE/assets/127030695/716e7967-d5c8-4790-953c-cf718c589df7)

**Additional context (Mandatory )**
I want to work on this issue and make it perfect with some adjustments in CSS and JS.
Kindly assign me.

***Are you contributing under any open-source program ?***

Yes under KWOC.

**Comment by apu52** [comment]
@Abhishek-465 Thanks for raising the issue.

**Comment by Abhishek-465** [comment]
> @Abhishek-465 Thanks for raising the issue.

Welcome @apu52
