### ISSUE TITLE
Bubble burst game

### ISSUE THREAD

**Issue by GAGANRAGHAV** [apu52/METAVERSE#449]
### Project title
bubble burst game

### Web stack
html ,css , javascript

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/120806356/9e8b03d8-f715-4dcf-9947-102993e9b08c)

### Additional Context(mandatory)
a game to strong your javascript concepts and enjoy also

#### Are you contributing under any open-source program ?
Codepeak 23

**Comment by apu52** [comment]
@GAGANRAGHAV Can you attach a video prototype of the project like the gameplay??

**Comment by GAGANRAGHAV** [comment]
https://www.loom.com/share/825fbe984dde4001b432e9e04c036d07
