### ISSUE TITLE
Hotstar clone project is not loading thumbnails

### ISSUE THREAD

**Issue by dhwanish-3** [apu52/METAVERSE#45]
**Describe the bug**
In the Hotstar clone project the website is not loading the images & video thumbnails

**Expected behavior**
The thumbnails should have been properly rendered

**Screenshots**
![image](https://github.com/apu52/METAVERSE/assets/108540722/1dc400bf-34b0-4372-84b8-08f80b23cc09)

**Additional context**
I can try to fix the bug if needed

**Comment by apu52** [comment]
@dhwanish-3 please go through contributing.md
& thanks for raising an issue
