### ISSUE TITLE
CHATGPT- MERN

### ISSUE THREAD

**Issue by Mayank77maruti** [apu52/METAVERSE#451]
### Project title
CHATGPT

### Project Description
This clone is made with MERN and uses OpenAI API.

This project is clone of chatGPT , chatGPT is an AI . It's allows you to have human-like conversations.

### Web stack
MERN STACK.

### Screenshot(mandatory)
![Uploading CHATGPT.png…]()

#### Are you contributing under any open-source program ?
I ma working under codepeak'23.

**Comment by Mayank77maruti** [comment]
![CHATGPT](https://github.com/apu52/METAVERSE/assets/125661248/d4b6c556-2c90-4249-a632-4d7de1788043)

**Comment by CAPTAINRAJ19** [comment]
This project is copied from the following repo :- https://github.com/ansonbenny/ChatGPT

<img width="803" alt="image" src="https://github.com/apu52/METAVERSE/assets/115424327/0ee50ae8-80f3-482d-8f34-c33977f1d9a7">

**Comment by apu52** [comment]
> This project is copied from the following repo :- https://github.com/ansonbenny/ChatGPT
> 
> <img alt="image" width="803" src="https://private-user-images.githubusercontent.com/115424327/292686629-0ee50ae8-80f3-482d-8f34-c33977f1d9a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDY2OTgsIm5iZiI6MTcwMzQ0NjM5OCwicGF0aCI6Ii8xMTU0MjQzMjcvMjkyNjg2NjI5LTBlZTUwYWU4LTgwZjMtNDgyZC04ZjM0LWMzMzk3N2YxZDlhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxOTMzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjM2ZjI0N2E4OWUyNDg5MTMzOGVlNDljNGM5MDE3ZDQ3ZjcwNjExNDgxMDQ5YjRjYWRkNDEwNjY2NGMzNTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DIlLGDRD_kCj3MiSR1WooPIrFPpji2LjL4og8svECvk">

@CAPTAINRAJ19 Thanks for the concern.

**Comment by apu52** [comment]
@Mayank77maruti Don't contribute the copied code from other's projects to this repo. It has highly violated the rules of this repo.

**Comment by CAPTAINRAJ19** [comment]
> > This project is copied from the following repo :- https://github.com/ansonbenny/ChatGPT
> > <img alt="image" width="803" src="https://private-user-images.githubusercontent.com/115424327/292686629-0ee50ae8-80f3-482d-8f34-c33977f1d9a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDY2OTgsIm5iZiI6MTcwMzQ0NjM5OCwicGF0aCI6Ii8xMTU0MjQzMjcvMjkyNjg2NjI5LTBlZTUwYWU4LTgwZjMtNDgyZC04ZjM0LWMzMzk3N2YxZDlhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxOTMzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjM2ZjI0N2E4OWUyNDg5MTMzOGVlNDljNGM5MDE3ZDQ3ZjcwNjExNDgxMDQ5YjRjYWRkNDEwNjY2NGMzNTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DIlLGDRD_kCj3MiSR1WooPIrFPpji2LjL4og8svECvk">
> 
> @CAPTAINRAJ19 Thanks for the concern.

Happy to help...👍
