### ISSUE TITLE
EAT FOOD GAME

### ISSUE THREAD

**Issue by GAGANRAGHAV** [apu52/METAVERSE#461]
### Project title
EAT FOOD GAME

### Web stack
HTML ,CSS , JAVASCRIPT

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/120806356/35864461-bacf-4d0d-9adf-49923f06a9a0)

### Additional Context(mandatory)
A game interesting to play

#### Are you contributing under any open-source program ?
codepeak 23

**Comment by apu52** [comment]
@GAGANRAGHAV can you attach a prototype video of the gameplay??

**Comment by GAGANRAGHAV** [comment]
https://www.loom.com/share/e352aa058e8b474088d44663ad4f30e3
