### ISSUE TITLE
Add new project: News App

### ISSUE THREAD

**Issue by YashSachan2** [apu52/METAVERSE#466]
### Project title
News App

### Project Description
A news app with search bar  and category wise news feature

### Web stack
React

### Screenshot(mandatory)
![news](https://github.com/apu52/METAVERSE/assets/122620769/37fe6628-347c-48f0-bc9d-2ae662e832af)

#### Are you contributing under any open-source program ?
Codepeak-23

<hr/>

**Comment by apu52** [comment]
@YashSachan2 Welcome to METAVERSE!!!!
Please go through contributing.md before contributing.

**Comment by YashSachan2** [comment]
@apu52 I have made the pr for news app.Please look into it.

**Comment by YashSachan2** [comment]
Please assign me the points
