### ISSUE TITLE
METALINK WEBSITE

### ISSUE THREAD

**Issue by GAGANRAGHAV** [apu52/METAVERSE#475]
### Project title
METALINK_NFT

### Project Description
A WEBSITE MADE FOR NFT AND ARTS

### Web stack
HTML , CSS , JAVASCRIPT

### Screenshot(mandatory)
![image](https://github.com/apu52/METAVERSE/assets/120806356/720b4830-1663-4150-bc08-8e663b801483)

#### Are you contributing under any open-source program ?
CODEPEAK 23

**Comment by apu52** [comment]
@GAGANRAGHAV We already have a NFT website in this repo .So sorry this issue can't be assigned.
