### ISSUE TITLE
Video to Audio Converter and store info in database

### ISSUE THREAD

**Issue by PSS2134** [apu52/METAVERSE#480]
### Project title
Video-Audio Converter

### Project Description

A webapp to convert the video file to audio file and storing the relevant information of audio into database

### Web stack

ReactJs, NodeJs, ffmpeg, ExpressJs, MongoDB

#### Are you contributing under any open-source program ?

Codepeak'23
<hr/>

@apu52

**Comment by apu52** [comment]
@PSS2134 Please properly fill up the Issue template. Your issue is not clear at all.
