### ISSUE TITLE
Add new project: Password Generator App

### ISSUE THREAD

**Issue by YashSachan2** [apu52/METAVERSE#489]
### Project title
Password Generator

### Project Description
Generates random and strong password depending upon number of special character, upper case and lower case character entered by user. 

### Web stack
HTML, CSS, JavaScript

### Screenshot(mandatory)

![IMG-20231225-WA0012](https://github.com/apu52/METAVERSE/assets/122620769/4ab112ad-8f71-41c9-a0dd-e533808c2c5c)

#### Are you contributing under any open-source program ?
Codepeak

<hr/>

**Comment by apu52** [comment]
@YashSachan2 We already have this project in our repo.
This issue can't me assigned . Sorry!
