### ISSUE TITLE
Add new project / Multi step form 

### ISSUE THREAD

**Issue by AaadityaG** [apu52/METAVERSE#519]
### Project title

Multi step form 

### Project Description

It is the form where user can fill his/her information through multiple steps 

### Web stack

HTML / CSS / JS

### Screenshot(mandatory)

![Day #15 - Multi Step Form _ NaeuCode — Mozilla Firefox 26-12-2023 12_08_35 PM](https://github.com/apu52/METAVERSE/assets/114663382/7d74a6f6-41d3-4b27-9dda-3e24bf99fbb0)

#### Are you contributing under any open-source program ?

Yes / Codepeak & KWoC
<hr/>

**Comment by apu52** [comment]
@AaadityaG We already have a form project in our repo.
Sorry , but this issue can't be assigned.
