### ISSUE TITLE
Facebook Clone

### ISSUE THREAD

**Issue by singhcoder694** [apu52/METAVERSE#526]
### Project title
Facebook Clone

### Project Description
Facebook clone using REACTJS

### Web stack
- HTML, CSS, JS
- REACTJS

### Screenshot(mandatory)
<img width="818" alt="Screenshot 2023-12-26 173051" src="https://github.com/apu52/METAVERSE/assets/114601400/42f0f91f-1c40-4046-bb08-9340e7ae92f5">
<img width="936" alt="Screenshot 2023-12-26 173058" src="https://github.com/apu52/METAVERSE/assets/114601400/cfe9126e-51f1-4d8a-aecc-7d1265ea2d79">

#### Are you contributing under any open-source program ?
CodePeak'23

<hr/>

**Comment by hemant933** [comment]
assign it to me plz.

**Comment by singhcoder694** [comment]
@hemant933 I am working on this project...
