### ISSUE TITLE
Coffee Website

### ISSUE THREAD

**Issue by Mayank77maruti** [apu52/METAVERSE#542]
### Project title
Coffee Website

### Project Description
A website where users can see various coffees and buy coffee.

### Web stack

HTML ,CSS AND JAVASCRIPT

### Screenshot(mandatory)
![coffee website](https://github.com/apu52/METAVERSE/assets/125661248/ec694796-18c9-4f28-856d-4127a71df5dd)

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

**Comment by hemant933** [comment]
assign it to me plz
