### ISSUE TITLE
Electric Evehicle website

### ISSUE THREAD

**Issue by Mayank77maruti** [apu52/METAVERSE#544]
### Project title
Electric Evehicle website

### Project Description
A website where users see and buy various electric evehicle.

### Web stack

HTML ,CSS AND JAVASCRIPT.

### Screenshot(mandatory)
![ELECTRIC](https://github.com/apu52/METAVERSE/assets/125661248/c01e3824-b1bf-45fc-ad68-57ee714a6186)

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

**Comment by apu52** [comment]
@Mayank77maruti Is this project also copied from another project?
If yes, Please close it .
