### ISSUE TITLE
Hamburg-menu not visible in Hostel management website.

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#555]
**Describe the bug**

Hamburg-menu not visible in Hostel management website in medium screen sized devices.

**Expected behavior**

Hamburg-menu should be visible in the Hostel management website.

**Screenshots (Mandatory)**

![Screenshot (49)](https://github.com/apu52/METAVERSE/assets/127030695/c868f4aa-7f12-4069-be15-afa76aaed942)

**Additional context (Mandatory )**
I want to solve the problem.Kindly assign me.
Thank you.

***Are you contributing under any open-source program ?***

Yes under KWOC.

**Comment by Tonykimanthi** [comment]
Hey! there,
I would like to solve the problem.Kindly assign me.

**Comment by apu52** [comment]
> Hey! there, I would like to solve the problem.Kindly assign me.

This issue is already assigned & merged
