### ISSUE TITLE
AudioExtract

### ISSUE THREAD

**Issue by PSS2134** [apu52/METAVERSE#564]
### Project title
AudioExtract

### Project Description
AudioExtract, converts or extracts audio from a video file  and stores the information
It has user authentication,
audio extraction 
audio information storage
Dark and Light mode feature

### Web stack

MERN,(full stack),  ffmpeg

### Screenshot(mandatory)

![Screenshot 2023-12-27 222933](https://github.com/apu52/METAVERSE/assets/101321904/4b1796ed-da57-438e-964c-1cf08086f0ce)

#### Are you contributing under any open-source program ?

Codepeak'23
<hr/>
This is the same as issue #480 but in detailed way. I have closed that issue

**Comment by apu52** [comment]
@PSS2134 Please don't make any type of PR until & unless you get assigned.
Now , I have assigned you. You can start on this project.
Please follow the rules mentioned in contributing.md
