### ISSUE TITLE
CyberWise

### ISSUE THREAD

**Issue by Mayank77maruti** [apu52/METAVERSE#569]
### Project title
Cyberwise

### Project Description
A project where the users get aware of cybercrime and can be saved from them.

### Web stack

html ,css and javascript.

### Screenshot(mandatory)
![cyberwiseee](https://github.com/apu52/METAVERSE/assets/125661248/4bd13803-7edc-4976-ba78-d4f9932fb1f7)

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

**Comment by NavalMahajan** [comment]
Hey i really want to work on this project can you assign me this one

**Comment by apu52** [comment]
@Mayank77maruti Is this project also copied from another project?
If yes, Please close it .

**Comment by Mayank77maruti** [comment]
Nope this is my project which I made 3 days ago you can check https://mayank77maruti.github.io/CyberWise/

**Comment by apu52** [comment]
> Nope this is my project which I made 3 days ago you can check https://mayank77maruti.github.io/CyberWise/

I have assigned you. But if this PR is also found copied from other's project , then you will not get any points
