### ISSUE TITLE
A Netflix-Clone-Project

### ISSUE THREAD

**Issue by Jatingupta9120** [apu52/METAVERSE#57]
**Describe the project you want to add with tech stack**
hey arpan , I want to contribute my Netflix clone project under hacktoberfest 2023 label .I have made a netflix clone project by using  Html,Css, javascript

**Expected behavior**
It will be a front end website.I have used in this website  api.It will help to fetch new movies daily

**Screenshots (optional)**
I have added you can go through it 
1.
![image](https://github.com/apu52/METAVERSE/assets/114533828/280826db-9314-4b05-aab5-f9ceb95c2ac3)

2. ![image](https://github.com/apu52/METAVERSE/assets/114533828/8cf8afc7-eb29-450d-8474-d487c4a6dd6c)

**Additional context (optional )**

my hosted link:-https://netflix-clone-by-jatin.netlify.app/

**Comment by apu52** [comment]
@Jatingupta9120 Welcome to METAVERSE!!!!
Happy coding!
