### ISSUE TITLE
Codewithdhruv

### ISSUE THREAD

**Issue by Dhruv127** [apu52/METAVERSE#577]
### Project title
codewithdhruv

### Project Description
coding website to solve dsa questions

### Web stack
Css, Javascript, Node.js, express, cors

### Screenshot(mandatory)

![Screenshot (248)](https://github.com/apu52/METAVERSE/assets/92450489/f4c2fbc0-10a7-4e68-9338-7dfb8e4a4661)
![Screenshot (246)](https://github.com/apu52/METAVERSE/assets/92450489/04e46025-6a95-43d0-9e9d-0844258a0f89)
![Screenshot (247)](https://github.com/apu52/METAVERSE/assets/92450489/2f0c5b05-cee6-437e-9486-da17be1a191c)

#### Are you contributing under any open-source program ?
codepeak '23

<hr/>

**Comment by shruti-sen2004** [comment]
@Dhruv127 Thank you for showing your interest to work on the issue but our deadline for raising new issues for codepeak 2023 have been closed.

**Comment by Dhruv127** [comment]
@shruti-sen2004 , i didn't know about the deadline . i have already made the project and it took a lot of my efforts and time . Can i just raise a pr please?

**Comment by shruti-sen2004** [comment]
> @shruti-sen2004 , i didn't know about the deadline . i have already made the project and it took a lot of my efforts and time . Can i just raise a pr please?

I am sorry but its not in my hands in the decision of the mentor @apu52 .

**Comment by Dhruv127** [comment]
@apu52  please can i ?

**Comment by Dhruv127** [comment]
@apu52  can i ?
