### ISSUE TITLE
Bug_Report: Age Calculator Project

### ISSUE THREAD

**Issue by agrawal-yash** [apu52/METAVERSE#580]
**Describe the bug**
1. The reset button in the site does not work. It does not do anything when it is pressed. 
2. The calculated age entered doesn't show the units in the results. 

**Expected behavior**
1. The reset button must reset the date in the input field as well as clear the result field. 
2. There must be units after the result according to the ones entered by the user.  

**Screenshots (Mandatory)**
![image](https://github.com/apu52/METAVERSE/assets/139786074/882765f5-7aad-49be-9b38-f279926c0b30)

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes, under KOSS - KWOC 2023 

Please assign me on the above issue so that I can fix the above problems.

**Comment by apu52** [comment]
@agrawal-yash Welcome to METAVERSE!!!!!!
Please go through contributing.md before contributing.
