### ISSUE TITLE
Feature_Request: Enhancing the User Interface of the Age Calculator Project

### ISSUE THREAD

**Issue by agrawal-yash** [apu52/METAVERSE#581]
**Is your feature request related to a problem? Please describe.**
I've noticed that the current UI design feels less appealing and the CSS could use some enhancements to improve overall user experience. The positioning & sizing of the input fields & result also feels somewhat less attractive. The result of the calculator is also very small and isn't located as per its priority. There should also be an option to display the age of the user in exact years, months and days from the date of birth till the date user is using the site. 

**Describe the solution you'd like**

I am capable of contributing to the following enhancements: 
1. Adding an option to display the age of the user in exact years, months and days together, along with the current options of days, months and years individually. 
2. Elevating the styling of input fields and buttons for a more polished interface.
3. Rearrange the input fields & buttons for a more user-appealing look. 
4. Relocate & resize the result section to a more prioritized position and size due to its importance. 

**Describe alternatives you've considered**

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes, under the KOSS - KWOC 2023 program. 

Please assign me if I can contribute the above changes.

**Comment by apu52** [comment]
@agrawal-yash Can you provide a SS of the feature/ enhancement you want to add

**Comment by agrawal-yash** [comment]
I haven't made the enhancements yet, but I have all the necessary code with me for the features so I'll start working on it as soon as I get assigned. I hope you understand.

**Comment by apu52** [comment]
> I haven't made the enhancements yet, but I have all the necessary code with me for the features so I'll start working on it as soon as I get assigned. I hope you understand.

I have assigned you. You can start working on it.
