### ISSUE TITLE
Feature_Request:Imprtoving the UI of the Github profile viewer.

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#585]
**Is your feature request related to a problem? Please describe.**

The UI of the Github profile generator is not good.

**Describe the solution you'd like**

It needs some improvements in CSS and JS.
Screenshot:
![Screenshot (53)](https://github.com/apu52/METAVERSE/assets/127030695/8e045947-761e-4b06-be82-bbf6879dcee7)

**Additional context (Mandatory )**
I want to work on this issue.Kindly assign me.

***Are you contributing under any open-source program ?***

Yes under KWOC.

**Comment by cjstyles6** [comment]
@apu52 can i work on this issue

**Comment by apu52** [comment]
> @apu52 can i work on this issue

The issue is already assigned. you can raise a new issue on a new topic in which you want to work on
