### ISSUE TITLE
[ Feature ]  - Add Scroll Reveal effect to the main website

### ISSUE THREAD

**Issue by sambitsingha** [apu52/METAVERSE#587]
### The scroll reveal effect will reveal each element of the website one after the other on scrolling through it. This can be customised according to the UI

- I would like to work on this issue under KWoC

**Comment by apu52** [comment]
@sambitsingha Welcome to METAVERSE!!!!
Can you please try to raise your Issue with the proper templates so that it will include all the details.

![image](https://github.com/apu52/METAVERSE/assets/114172928/56ca9799-7f19-442e-a873-88b525bee52f)

**Comment by sambitsingha** [comment]
Alright @apu52 I am opening a new issue
