### ISSUE TITLE
Feature_Request  - Add Scroll Reveal effect to the main website

### ISSUE THREAD

**Issue by sambitsingha** [apu52/METAVERSE#588]
**Is your feature request related to a problem? Please describe.** -- 
The feature requested is not related to any problem. I am looking forward to add Scroll Reveal effect to the website

**Describe the solution you'd like** -- 
The Scroll Reveal effect will reveal each element one by one on scrolling through the website. The effects can also be customised according to the need of the UI.

**Describe alternatives you've considered** -- 

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes I am contributing under KWoC

**Comment by sambitsingha** [comment]
@apu52  Here is the issue with proper templates :)

**Comment by apu52** [comment]
Can you please add a prototype SS??

**Comment by sambitsingha** [comment]
### A demo scroll reveal effect

https://github.com/apu52/METAVERSE/assets/110420002/48832742-8d20-4f2a-a18b-e6b81a7d0ce1

**Comment by apu52** [comment]
@sambitsingha I have assigned you. You can start working

**Comment by apu52** [comment]
closing this issue
