### ISSUE TITLE
Platformer Game

### ISSUE THREAD

**Issue by Subhrangsu90** [apu52/METAVERSE#589]
### Project title
Platformer Game

### Project Description
Jump, run, and conquer levels in this exciting platformer game, mastering checkpoints for ultimate success!

### Web stack
HTML, CSS, JavaScript

### Screenshot(mandatory)
[Platformer Game.webm](https://github.com/apu52/METAVERSE/assets/76052002/23b3b12a-ec9f-4613-a984-1433bd711cf8)

#### Are you contributing under any open-source program ?
KWOC

<hr/>

**Comment by apu52** [comment]
@Subhrangsu90 Welcome to METAVERSE!!!!!
Please go through contributing.md before contributing.
