### ISSUE TITLE
A-Weather-Application

### ISSUE THREAD

**Issue by Jatingupta9120** [apu52/METAVERSE#59]
**Describe the project you want to add with tech stack**
A weather application is a software application that provides information about the weather. 
Weather applications can be used to: 
- Get the current weather conditions for a specific location
- Get the weather forecast for a specific location
- Track the weather conditions in multiple locations

**Expected behavior**

It will tell us the temperature of a particular location You can see in the screenshot available below.
It will tell us like example:-
**City: Lucknow
Conditions: haze
Temperature: 21.14 C
Wind Speed: 0 km/h**

**Screenshots (optional)**

![image](https://github.com/apu52/METAVERSE/assets/114533828/eb53e172-af00-4c9e-97cd-56fad9d67237)

**Additional context (Mandatory )**
 
- [X ] I am a contributor in OSEN open source programme

 
- [ X] I am a contributor in HACTOBERFEST 2023

**Comment by apu52** [comment]
@Jatingupta9120 we already have a weather application project in this repo

**Comment by apu52** [comment]
Please try to add new projects or new enhancements
