### ISSUE TITLE
Theme Toggle Button Disappears in Large Monitor Screen(24inch Monitors)

### ISSUE THREAD

**Issue by Sumonta056** [apu52/METAVERSE#592]
**Describe the bug**

Theme Toggle Button Disappears in Large Monitor (24inch Monitors).. Mainly the button is gets hidden due to little bit bug in code...

Device : Samsung F24T350FHW 24 INCH IPS LED Monitor

**Expected behavior**

Button Should be in a visible position with screen responsive.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/METAVERSE/assets/61287791/e4cda31b-c36e-4fb2-95ba-2ad08b332717)

![image](https://github.com/apu52/METAVERSE/assets/61287791/6191f327-00ec-4f8e-8aec-6fad8967623f)

**Comment by apu52** [comment]
@Sumonta056 Are you contributing under any open source programme?

**Comment by Sumonta056** [comment]
@apu52  No..

**Comment by Sumonta056** [comment]
@apu52  can you assign me the issue?

**Comment by Tonykimanthi** [comment]
Hi! Sumonta056,
I'm interested in helping you fix the "Theme toggle button."

**Comment by apu52** [comment]
> @apu52 can you assign me the issue?

@Sumonta056 Welcome to METAVERSE!!!!!!!!
I have assigned you
Please go through contributing.md before contributing.

**Comment by apu52** [comment]
> Hi! Sumonta056, I'm interested in helping you fix the "Theme toggle button."

@Tonykimanthi This issue is already assigned. You can raise a new issue on a new topic you want to work on this Repo.
