### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by OkenHaha** [apu52/METAVERSE#6]
**Is your feature request related to a problem? Please describe.**
Some UI enhancement was required when I looked at the page
https://github.com/apu52/METAVERSE/tree/main/Projects/Career-Crafters

**Describe the solution you'd like**
I'd like to improve the UI look

**Describe alternatives you've considered**
Minor UI improvement could be done

**Additional context**
None

**Comment by OkenHaha** [comment]
can you please assign this task to me? I'm already working on it.

**Comment by apu52** [comment]
@OkenHaha Welcome to Metaverse!!!!!!!!!🥳
Thanks For raising the Issue. 👍

**Comment by apu52** [comment]
Please follow contributing.md file for the contribution details
