### ISSUE TITLE
Add new project: Amazon Clone(Front-End).

### ISSUE THREAD

**Issue by Ritwika-14** [apu52/METAVERSE#602]
### Project title
Amazon Clone(Front-End)

### Project Description
This project is a frontend clone built using HTML and CSS. It aims to replicate the user interface and design of a specified website or application. By studying the target website(amazon.com), you can recreate its frontend using HTML for structure and CSS for styling.

### Web stack
HTML , CSS

### Screenshot(mandatory)
![Screenshot (47)](https://github.com/apu52/METAVERSE/assets/119119223/8ddfbdb5-07e1-459e-82da-1da1b2beb5f1)
![Screenshot (48)](https://github.com/apu52/METAVERSE/assets/119119223/6ce1e13b-1cbb-4bb4-a47d-4bd8f2bd04fe)

### Additional Context(mandatory)
I crafted a front-end clone project with precision, mirroring the design of a popular website. Leveraging HTML, CSS. I ensured a seamless user interface that replicates the original's aesthetics. Through responsive design, my clone adapts gracefully to diverse devices, providing a consistent and engaging experience. This project showcases my proficiency in front-end development and attention to detail.

#### Are you contributing under any open-source program ?
KWOC

**Comment by apu52** [comment]
@Ritwika-14 Welcome to METAVERSE!!!!!!!!!!
Please go through contributing.md before contributing.
