### ISSUE TITLE
Feature_Request:Display of Highest score in Car racing game

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#610]
**Is your feature request related to a problem? Please describe.**

The highest score in the game should be displayed.

**Describe the solution you'd like**

With the help of local storage i am going to display the highest score.

![Screenshot (71)](https://github.com/apu52/METAVERSE/assets/127030695/2dd7cd11-5799-409a-b90b-d9dc702b6b81)

**Additional context (Mandatory )**
Kindly assign me.

***Are you contributing under any open-source program ?***

Yes under KWOC.

**Comment by Abhishek-465** [comment]
@apu52 Kindly assign me this issue.

**Comment by apu52** [comment]
> @apu52 Kindly assign me this issue.

You have been assigned.

**Comment by Abhishek-465** [comment]
> > @apu52 Kindly assign me this issue.
> 
> You have been assigned.

Thanks a lot
