### ISSUE TITLE
change the ui of cards 

### ISSUE THREAD

**Issue by Vishnu1804K** [apu52/METAVERSE#613]
I want to change the ui of cards so that the cards look more attractive for the users in your website

**Comment by nishant0708** [comment]
hey i can fix this.. please assign it to me

**Comment by Vishnu1804K** [comment]
Hey @nishant0708 it is my issue you raise your own issue

**Comment by apu52** [comment]
> I want to change the ui of cards so that the cards look more attractive for the users in your website

@Vishnu1804K Welcome to METAVERSE!!!!!!!!!!
Please try to make raise issue with the proper Issue templates mentioned in the repo so that it will clarify all the things.

**Comment by apu52** [comment]
![image](https://github.com/apu52/METAVERSE/assets/114172928/c3db159f-9d87-4116-ab3c-99ffdf97b779)
use this templates to raise your issue .
Make a proper issue with this .
Sorry to close this issue right now.
Happy coding!!!!!!!!!
