### ISSUE TITLE
Footer UI improvements

### ISSUE THREAD

**Issue by VedantAnand17** [apu52/METAVERSE#615]
**Is your feature request related to a problem? Please describe.**
 ![Screenshot_2024-05-10-13-26-18-72_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/apu52/METAVERSE/assets/136731196/5ed3b150-a9bd-47f7-8602-f2720c11f500)

In this image you can see the buttons and text fonts are not very appealing and the icon logo is not showing 

**Describe the solution you'd like**
The text and buttons interface should be changed in such a way that it looks appealing and the icon logo can be shown

**Describe alternatives you've considered**
For the solution I can change the look of the footer texts and buttons which will match the great footer animation such that it looks very appealing hence leading to a great User Interface and I can fix the icon logo problem. 

**Additional context (Mandatory )**
I'd like if you could assign this issue to me as I have made several projects and would love to contribute in this too…

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by VedantAnand17** [comment]
Please assign this issue to me

**Comment by apu52** [comment]
@VedantAnand17 Welcome to METAVERSE!!!!!!
I have assigned you .
You can start working on this issue , I will add the labels(e.g level 1 ,2 or 3) after the review of the PR
Happy Coding !!!!!!!!!!

**Comment by Satuti99** [comment]
Hello sir @apu52  I would lie to work on this issue. Please assign me this task.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me. 
@apu52

**Comment by apu52** [comment]
@Satuti99 @TheNikhilRaj this issue is already assigned. but u can still work on new issues looking at the existing issues.
