### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by TerminatorSS24** [apu52/METAVERSE#617]
**Is your feature request related to a problem? Please describe.**

- _When I hover my mouse on the search bar, the 'search' word is not at the center, which looks odd._
- _This is not a problem, but I can change font style or font family of the METAVERSE_
- _In the contact section, the name of the repo owner is overlapping_
- 
![Screenshot 2024-05-11 093246](https://github.com/apu52/METAVERSE/assets/125677043/22894550-d142-4c0a-9f61-e136058d43e2)

**Describe the solution you'd like**

1. _I would change some code to adjust the position of the 'search' word._
2. _Changing the font style can attract user's attention._
3. _The overlapping the name can be fixed quickly_

**Describe alternatives you've considered**
_As an alternative, I can create a search icon, and when a user clicks on it, it will expand with the same animations._

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***
_This will be my first contribution_

https://github.com/apu52/METAVERSE/assets/125677043/062be322-baff-4476-bd9c-0c85effc012a

like this

**Comment by apu52** [comment]
@TerminatorSS24 welcome to METAVERSE
I have assigned you .
You can start working on this issue , I will add the labels(e.g level 1 ,2 or 3) after the review of the PR
Happy Coding !!!!!!!!!!

**Comment by nandita27iitp** [comment]
Can I work on it

**Comment by apu52** [comment]
@nandita27iitp  this issue is already assigned. but u can still work on new issues looking at the existing issues.
