### ISSUE TITLE
[Feature_Request] Adding a Discord icon in the readme

### ISSUE THREAD

**Issue by Sibam-Paul** [apu52/METAVERSE#624]
**Is your feature request related to a problem? Please describe.**
### I want to add a discord icon in the readme section See Image reference

**Image Reference**
![image](https://github.com/apu52/METAVERSE/assets/158052549/cf0d650f-dcf7-40c0-893a-4047fb8c6813)

**Additional context (Mandatory )**
_please assign me this issue so that I can work on this_ 

***Are you contributing under any open-source program ?***
_Under GSSOC'24 Please Give GSSOC'24 tags and  documentation tags and Level 1 tags and good first issue_

Thank u

**Comment by Sibam-Paul** [comment]
@apu52 here is the issue

**Comment by apu52** [comment]
@Sibam-Paul Welcome to METAVERSE!!!!!!!!!
Thanks for raising the issue .
I have assigned you . Start working on this issue .
Happy Coding
