### ISSUE TITLE
[Feature_Request] Add Animation to Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by thevijayshankersharma** [apu52/METAVERSE#625]
Is your feature request related to a problem? Please describe.
The current dark/light mode toggle lacks animation, resulting in a sudden change in appearance that can be jarring for users.

Describe the solution you'd like
Implement animation effects to smoothly transition between dark and light modes when toggling. This could involve a fade effect, sliding animation, or similar transition to enhance the user experience.

Describe alternatives you've considered
One alternative would be to leave the toggle as it is without animation. However, adding animation can significantly improve user experience and aesthetic appeal.

Additional context (Mandatory)
I am an open-source contributor and would like to contribute this feature enhancement to the project.

Are you contributing under any open-source program?
Yes, I am contributing under the GSsoC'24.

**Comment by apu52** [comment]
@thevijayshankersharma Welcome to METAVERSE!!!!!!!!!!!!
Thanks for raising the issue.
I have assigned you . start working on this issue.
Happy Coding!!!!!!!!!!

**Comment by nandita27iitp** [comment]
@apu52 I think this issue is done
