### ISSUE TITLE
Adding a Toggle button Digital Clock to toggle between 12H and 24H format

### ISSUE THREAD

**Issue by AtharvKasar04** [apu52/METAVERSE#626]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
I would like to add a button to toggle the time which is currently displayed in only 24Hour format.
I will add a toggle to display it in 12Hour format.

**Describe alternatives you've considered**
Toggle button

@apu52 Can you please assign me this issue under GSSoC'24.
Thank You!

***Are you contributing under any open-source program ?***
I am contributing under the GSSoC'24 Program.

**Comment by apu52** [comment]
@AtharvKasar04 Welcome to METAVERSE!!!!!!!
I have assigned you. Start working on this issue.
Happy Coding !!!!!!!!!!!!

**Comment by nandita27iitp** [comment]
@apu52 Can I work on this
