### ISSUE TITLE
Finance Tracker

### ISSUE THREAD

**Issue by thanmaisai** [apu52/METAVERSE#63]
**Describe the project you want to add with tech stack**
A react app which is used to track all tranctions, you can over look at the expences and even the savings

Tech Stack
* react
* crypto-js
* firebase
* mantine

**Expected behavior**
The React app is expected to provide a user-friendly interface for tracking financial transactions, including expense and savings management. Utilizing crypto-js ensures data security, while Firebase enables real-time updates, creating a seamless and responsive user experience.

**Additional context (Mandatory )**
 
- [x] I am a contributor in OSEN open source programme

 
- [x] I am a contributor in HACTOBERFEST 2023

**Comment by thanmaisai** [comment]
Please assign me this issue, and do add the labels for the issue/PR raised in order to make it a valuable contribution for hacktoberfest 2023 and OSEN open source program.

**Comment by apu52** [comment]
@thanmaisai Welcome to METAVERSE!!!!!
Please go through contributing.md file before raising the PR
