### ISSUE TITLE
Food Website styles and items are not loading

### ISSUE THREAD

**Issue by Hassaan68** [apu52/METAVERSE#631]
**Describe the bug**
The food website is not loading in MacOS browsers, see the screenshot for more info

**Screenshots (Mandatory)**
<img width="1707" alt="Screenshot 2024-05-14 at 14 14 31" src="https://github.com/apu52/METAVERSE/assets/35756574/a7935aeb-62d1-421b-a363-5a11476735ae">

**Comment by Hassaan68** [comment]
@apu52 , can you please assign this one to me ?

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by apu52** [comment]
@Hassaan68 Can you make this food website  working well???
I am assigning you this issue . Start working on it

**Comment by Hassaan68** [comment]
sure @apu52

**Comment by Hassaan68** [comment]
@apu52 , Pull Request added :)
