### ISSUE TITLE
Feature_Request: A number of issues with the current websites

### ISSUE THREAD

**Issue by Stiffpixels** [apu52/METAVERSE#632]
**Is your feature request related to a problem? Please describe.**
- First the home button does not work on the about page because of the link text is out of anchor element.
- footer does not cover the width of the desktop layout.
- The achievement can be improved and centered on mobile as well as desktop.

**Describe the solution you'd like**
- Moving the span element with home text inside anchor tag on about page.
- removing min-width from main container or moving footer out of main container.

**Additional context (Mandatory )**

Screenshots:
as you can see "METAVERSE as secured a position in top 50 maintainer repositories in QUINE HACTOBERFEST challenge" container is not displayed well on mobile.
![image](https://github.com/apu52/METAVERSE/assets/32983571/5173c4e0-e46d-4b9e-9d8c-32791c5d17a0)

The footer doesn't cover the width on desktop: 
![image](https://github.com/apu52/METAVERSE/assets/32983571/17d2effa-a39e-4ba2-b8e8-9d93b74f651d)

***Are you contributing under any open-source program ?***
- GSSOC24'

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by apu52** [comment]
@Stiffpixels I have assigned you . you can start working on it.

**Comment by apu52** [comment]
@Kalyan9064 this issue is already assigned. So I want to recommend you to raise new issues which you want to work on

**Comment by Stiffpixels** [comment]
> @Stiffpixels I have assigned you . you can start working on it.

can you add the level label as well?
