### ISSUE TITLE
Feature_Request   Enhance User Experience with Hover Effects on Links

### ISSUE THREAD

**Issue by Kalyan9064** [apu52/METAVERSE#634]
Adding hover effects to links can significantly improve user engagement and navigation experience on the website. Implementing hover effects such as color change, underline, or transition can provide visual feedback to users

I would like to work on this . Please could you assign me this issue under GSSOC'24

![Uploading Screenshot 2024-05-15 215351.png…]()

**Comment by apu52** [comment]
@Kalyan9064 Please use the issue templates to raise the issues properly . as the SS is still uploading . 
Please use the issue templates to make your issue more under standing.

![image](https://github.com/apu52/METAVERSE/assets/114172928/9f5baeb7-fc2f-4e96-bbb1-0bb6d9d4d515)

**Comment by apu52** [comment]
Sorry to close this issue for now.
