### ISSUE TITLE
Want to add a Image generator using prompt by AI.

### ISSUE THREAD

**Issue by Zedoman** [apu52/METAVERSE#635]
**Is your feature request related to a problem? Please describe.**

Many users face challenges when seeking image generation services online. They often encounter a plethora of websites, some offering free image generation initially but requiring payment for continued use. This creates uncertainty and inconvenience for users, especially those on a tight budget or looking for a sustainable solution.

**Describe the solution you'd like**

"chroma dreams" addresses this issue by providing a seamless and accessible image generation feature. Unlike other platforms that offer limited free services or require payment for extended use, "chroma dreams" offers 1 to 2 AI-powered image generators completely free of charge. This ensures that users can generate images without worrying about hidden fees or sudden payment demands. By prioritizing accessibility and affordability, "chroma dreams" aims to enhance the user experience and provide a reliable solution for image generation needs.

**Describe alternatives you've considered**

the decision to provide 1 to 2 AI-powered image generators for free within "chroma dreams" was chosen as it offers a balance between accessibility and sustainability, ensuring that users can access image generation services without barriers or financial constraints.

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

GSSOC (Girlscript Summer of Code)

**Comment by apu52** [comment]
@Zedoman Do you want to add new project in the Website ?? But sorry to say adding new project is not a valid contribution in this repo.
Btw the idea of the project is really good . Carry on with your idea.

I am not closing this issue . Just reply So that I can decide

**Comment by Zedoman** [comment]
yes its like in metaverse website there should be a place for ai image generator too ig. So every user can get better experience also. So if possible please allow me work under GSSOC. 
Thank you

**Comment by apu52** [comment]
@Zedoman Thanks for the issue. But Adding new project is not a valid contribution now in this repo . Sorry but all the best with your project .
I am closing this issue.
