### ISSUE TITLE
Feature_Request: No Results Found

### ISSUE THREAD

**Issue by SrinivasDevolper** [apu52/METAVERSE#637]
**Is your feature request related to a problem? Please describe.**
If the User enters the wrong name in the search bar then it should be show the **text No Results Found**
**Describe the solution you'd like**.

I want to show the **No Results Found** text in the search bar section

**Describe alternatives you've considered**

I want to add the **No Results Found** text with an illustration image also as it user friendly.

**Additional context (Mandatory )**
Actual

![metaverse 1](https://github.com/apu52/METAVERSE/assets/121508628/8e950c1e-6c67-43d6-9ee0-b5809f63fd51)

expected

![METAVERSE2](https://github.com/apu52/METAVERSE/assets/121508628/cd88e29a-1baa-4aa8-b6dd-3bad31a10f65)

***Are you contributing under any open-source program ?***

I would like to work on this. Please could you assign me this issue under GSSOC'24

**Comment by apu52** [comment]
@SrinivasDevolper I have assigned you . You can start working on this issue.

**Comment by SrinivasDevolper** [comment]
Thank you for assigned this issue, I try to solve it better
