### ISSUE TITLE
Enhancement in the UI of Amazon clone

### ISSUE THREAD

**Issue by sahithinandikula** [apu52/METAVERSE#640]
**Is your feature request related to a problem? Please describe.**
The Amazon clone on the website must be improved
**Describe the solution you'd like**
-> The cards must be properly aligned
-> Hover effects on the navbar elements should be added

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***
yes, I am a contributor at gssoc`24

**Comment by apu52** [comment]
@sahithinandikula I have assigned you . You can start working

**Comment by sahithinandikula** [comment]
@apu52 Sure! Please assign a level label to this issue
