### ISSUE TITLE
Feature_Request:User-Authentication in Book Review website

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#641]
**Is your feature request related to a problem? Please describe.**
 The book review option should be only applicable for the authorised users.

**Describe the solution you'd like**

I would like to add email and google authentication  to this website.

**Additional context (Mandatory )**
I would like to work on this issue .Kindly assign me.

***Are you contributing under any open-source program ?***

Yes under GSSOC 24

**Comment by apu52** [comment]
@Abhishek-465 Which book review option you are suggesting?? Can you please explain with some SS so that I can understand more clearly

**Comment by Abhishek-465** [comment]
![Screenshot 2023-10-15 111845](https://github.com/apu52/METAVERSE/assets/127030695/1f45c6db-3a28-4f5b-a46c-fdc69dca615f)

 Here in navbar signup and sign buttons are there but they are not functional. I want to make the signup and signin pages and also add the user authentication using Firebase.

**Comment by apu52** [comment]
@Abhishek-465 really good issue you have identified . thanks for raising the issue . You are assigned . You can start working on this issue.
