### ISSUE TITLE
Contact us page content not displayed properly in mobile devices

### ISSUE THREAD

**Issue by naim195** [apu52/METAVERSE#646]
**Describe the bug**

Content in 'contact us' section of the website is not displayed properly in mobile devices(the text overlaps). In addition to this, the dark/light theme slider is not positioned properly for mobile devices and appears on the home button.

**Expected behavior**

Some adjustments in CSS will fix the issue of responsiveness in different devices. The content in the 'about us' tab should be visible clearly and should not overlap. I want to fix these minor issues so that the website is perfectly readable even in mobile devices.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/METAVERSE/assets/119221365/b886ced1-ebd6-46cc-8266-84b205d1d079)

**Additional context (Mandatory )**
Kindly assign me the issue so that I can make the website responsive.

***Are you contributing under any open-source program ?***

No.

**Comment by Seba-Aguero** [comment]
Hello!
Could you assign me the issue please? I would like to work on it.

**Comment by apu52** [comment]
#617 is already assigned on the same issue. Sorry I can't assign this issue right now. But you can still raise other new issues on which you want to work on. 
Sorry to close this issue right now.
Happy Coding!!!!!!!!!!!!!!
