### ISSUE TITLE
Modification in Brick Breaker Game

### ISSUE THREAD

**Issue by nilamkumari11** [apu52/METAVERSE#647]
**Is your feature request related to a problem? Please describe.**
The game does not give the user any time to get ready. There is no "Start Game" or any display at the beginning. Additionally, as soon as the player loses, the game restarts without displaying any message.

**Describe the solution you'd like**
Before starting to play, there should be a "Start" button.
 After the player loses or completes the game, the score should be displayed along with option to play again.

***Are you contributing under any open-source program ?***
yes, I am a contributor at gssoc`24

**Comment by apu52** [comment]
@nilamkumari11 Can you please mention the name of the Particular project/game on which you want to contribute??? 
So that I can assign you . Additionally please add some SS on the changes you want to add

**Comment by nilamkumari11** [comment]
The name of the game on which I want to contribute is Brick Breaker Game https://apu52.github.io/METAVERSE/Projects/Brick_Breaker_Game/ 

In the beginning, I want to add start game button .
https://github.com/apu52/METAVERSE/assets/114328962/93f5a9d5-653a-41d9-b341-58cd4c915bc1

Then displaying the score and play again option after a player loses
https://github.com/apu52/METAVERSE/assets/114328962/a1e48d63-6dfe-4186-9931-14a8f0fc14d3

I will also add a proper background design relevant to the game

**Comment by apu52** [comment]
@nilamkumari11 great Ideas . Carry on with this . I have assigned you you can start working on this issue
