### ISSUE TITLE
Improving Contact page in Hackathon project page

### ISSUE THREAD

**Issue by SuhainaFathimaM** [apu52/METAVERSE#651]
**Describe the bug**

Improving Contact page in Hackathon project page

**Expected behavior**

**Screenshots (Mandatory)**

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

I have been contributing under GSSoC'24

**Comment by SuhainaFathimaM** [comment]
@apu52 Please assign me this issue under GSSoC'24

**Comment by SuhainaFathimaM** [comment]
@apu52  I have resolved the previous issue.. Please assign me this issue

**Comment by apu52** [comment]
@SuhainaFathimaM I have assigned you . You can start working.
