### ISSUE TITLE
Age calculator is not interactive in phone veiw  i.e not responsive 

### ISSUE THREAD

**Issue by agastya3636** [apu52/METAVERSE#654]
**Describe the bug**
Age calculator is not interactive in phone veiw  i.e not responsive 

**Expected behavior**
It should be responsive 

**Screenshots (Mandatory)**

![Screenshot_20240521_230707](https://github.com/apu52/METAVERSE/assets/124435030/d538df98-7c79-4609-805c-416529caf7d6)

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes I am gssoc24 contributor

**Comment by agastya3636** [comment]
@apu52 Please assign me this issue under GSSoC'24

**Comment by apu52** [comment]
@agastya3636 Welcome to the METAVERSE!!!!!!!
Thanks for raising the issue . I have assigned you . you can start working on this issue.
