### ISSUE TITLE
Feature_Request Memory Game using Javascript

### ISSUE THREAD

**Issue by Damini2004** [apu52/METAVERSE#655]
**Is your feature request related to a problem? Please describe.**
The feature request for a Memory Game using Javascript is not related to a specific problem, but rather an idea to create an engaging and interactive game for users.

**Describe the solution you'd like**
The solution I would like is to develop a Memory Game using Javascript that challenges users to find matching pairs of cards in a grid. The game would have the following features:

A grid of cards with various images or symbols, shuffled and facing down.
Users click on two cards to reveal their images.
If the images match, they remain face-up and the user earns a point.
If the images do not match, they turn back over after a short delay.
The game continues until all pairs have been matched.
The user's score is displayed at the end of the game.

**Describe alternatives you've considered**
Developing the game using a different programming language or framework, such as React or Angular.
Adding additional features to the game, such as timed rounds or different difficulty levels.
Creating a multiplayer version of the game where users can compete against each other.
Incorporating the game into a larger web application or website as a fun and interactive feature.

**Additional context (Mandatory )**
Here by is the image of project that may lead to enhancement in your project.
![image](https://github.com/apu52/METAVERSE/assets/119414762/d84f96f5-7f47-4b47-8def-c5082239e857)

***Are you contributing under any open-source program ?***
Yes under GSSOC

**Comment by apu52** [comment]
@Damini2004 Welcome to METAVERSE
Thanks for raising the issue!!!!!!!!!!!!

**Comment by apu52** [comment]
I just want to ask you one thin, Do you want to add new projects to the repo as you have mentioned a MEMORY GAME you want to add???

**Comment by apu52** [comment]
@Damini2004 Sorry to say , but adding a new project in this repo is not a valid contribution in this repo . You can instead fix bugs or enhance the codes of the existing projects or the repo website itself. 

Sorry to close this issue . Hope to see more of your contributions .
HAAPY CODING!!!!!!!!!
