### ISSUE TITLE
Feature_Request: Complete Backend for the AI Image Generator

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#660]
**Is your feature request related to a problem? Please describe.**

The AI-Image Generator has a good responsive UI and it fetches AI generated images very efficiently. I just want to add a cherry on top.

**Describe the solution you'd like**

I want to show the Recent Searches which the user made as well as add the complete authentication system.

![Screenshot (57)](https://github.com/apu52/METAVERSE/assets/127030695/b8c3693f-c87c-46b5-a498-db7139738f1d)

**Additional context (Mandatory )**
Kindly assign me this issue.

***Are you contributing under any open-source program ?***

Yes under GSSOC

**Comment by apu52** [comment]
@Abhishek-465 you are assigned.
