### ISSUE TITLE
Icon of the food website and footer 

### ISSUE THREAD

**Issue by jayanththalla** [apu52/METAVERSE#661]
The footer is not hovered and the alignment is not good.
Add a favicon to the title of the page
please assign @pa
![image](https://github.com/apu52/METAVERSE/assets/121346142/1cbe7c5a-cb4e-43ff-89bb-231a3dd9f37f)

**Comment by apu52** [comment]
@jayanththalla please try to use Issue templates which are already present in this repo to raise your issues. So that it will be helpful for me to understand . Sorry to close this issue for now . 
Just make your issue with the help of the templates
