### ISSUE TITLE
Quote of the day is not responsive

### ISSUE THREAD

**Issue by agastya3636** [apu52/METAVERSE#663]
**Describe the bug**

Quote of the day is not responsive

**Expected behavior**

Quote of the day should be responsive

**Screenshots (Mandatory)**

![image](https://github.com/apu52/METAVERSE/assets/124435030/3af85760-a562-4448-8237-4044f369b173)

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes I am contributing under GSSOC24

**Comment by kagrawal29** [comment]
Hey! Can you assign this issue?

**Comment by apu52** [comment]
@agastya3636 you are assigned. but first please try to complete the earlier issue .
