### ISSUE TITLE
Feature_Request:Adding light mode to contact us page

### ISSUE THREAD

**Issue by agastya3636** [apu52/METAVERSE#665]
**Is your feature request related to a problem? Please describe.**

Contact us page does not have light mode

**Describe the solution you'd like**

Adding light mode to contact us page

**Describe alternatives you've considered**

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes I am contributing under GSSOC24

**Comment by apu52** [comment]
@agastya3636 this is a good issue .but as per the rule of this repo .Please don't raise more than 1 issue at a time.
Sorry to close this issue for now . But after completing the earlier 2 issues you can again open this issue .
Please try to maintain the rules mentioned in CONTRIBUTING.md
