### ISSUE TITLE
Auto Commenting when a PR is merged

### ISSUE THREAD

**Issue by suhanipaliwal** [apu52/METAVERSE#667]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by apu52** [comment]
@suhanipaliwal  please try to use Issue templates which are already present in this repo to raise your issues. So that it will be helpful for me to understand . Sorry to close this issue for now .
Just make your issue with the help of the templates
