### ISSUE TITLE
Feature_Request of the food website  footer 

### ISSUE THREAD

**Issue by jayanththalla** [apu52/METAVERSE#670]
**Is your feature request related to a problem? Please describe.**
The footer is not hovered and the alignment is not good.
Add a favicon to the title of the page
**Describe the solution you'd like**
The footer section of the food website is not enhanced.
By adding new features like animations and others.
![image](https://github.com/apu52/METAVERSE/assets/121346142/712cec16-6201-4107-bab9-abe8d88a3f6e)

**Additional context (Mandatory )**
please assign me @pa
***Are you contributing under any open-source program ?***
Gssoc

**Comment by apu52** [comment]
@jayanththalla WELCOME to METAVERSE!!!!!!
You are assigned .you can start working on this issue.
