### ISSUE TITLE
Auto commenting on issues and self assign

### ISSUE THREAD

**Issue by MohanRamSridhar** [apu52/METAVERSE#675]
I'll create a workflow for auto commenting on issues and self assigning the issue to the contributor if he or she wants to contribute to the issue.
This will give updates to the user and will give him green flag to start working on the issue.
This will be very helpful for the project manager too.

**Comment by MohanRamSridhar** [comment]
please assign this issue to me under gssoc

**Comment by apu52** [comment]
Actually I don' want this Self assigning workflow in my repo.
But you can instead make a Github action greeting which will show/pop up whenever the contributor will open an issue or PR

**Comment by MohanRamSridhar** [comment]
Yesh sorry about that 
and the level label?
