### ISSUE TITLE
Enhancing the design of the Meme Generator 

### ISSUE THREAD

**Issue by Suvendu-UI** [apu52/METAVERSE#677]
**Is your feature request related to a problem? Please describe.**

The page of  the Meme Generator is dark and dull.

**Describe the solution you'd like**

I am changing the look of the button and adding design to the image.
![Screenshot 2024-05-26 180202](https://github.com/apu52/METAVERSE/assets/144688422/7a912836-90a2-45a1-80ef-07aea58ea745)

I have changed it to look like this.
![Screenshot 2024-05-26 181041](https://github.com/apu52/METAVERSE/assets/144688422/776d7c38-7696-4b93-b0e3-fa1bac3d1740)

**Describe alternatives you've considered**

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

I am contributing for GSSoC 2024.

**Comment by apu52** [comment]
@Suvendu-UI you are assigned. Now you can submit your PR.
I have closed your previous PR As per the rules of the repo
