### ISSUE TITLE
In light mode the headings are not clearlt visible

### ISSUE THREAD

**Issue by agastya3636** [apu52/METAVERSE#680]
**Describe the bug**

In light mode the headings are not clearlt visible.

**Expected behavior**

It should be clearly visible.
**Screenshots (Mandatory)**

![image](https://github.com/apu52/METAVERSE/assets/124435030/9f6eb648-de0b-466f-898f-fc79bcea44ee)
![image](https://github.com/apu52/METAVERSE/assets/124435030/abacc26e-b1c6-4a4a-8622-0ab230f54e81)

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes I am contributing under GSSOC24

**Comment by TheMystic07** [comment]
sir i am working on this issue

**Comment by apu52** [comment]
@agastya3636 now you are assigned.
