### ISSUE TITLE
URL Shortener Button Effects and Essential Modifications

### ISSUE THREAD

**Issue by sonakshisonkusare** [apu52/METAVERSE#686]
I would like to change the effects of url shortner button and other necesssary changes. 
![url](https://github.com/apu52/METAVERSE/assets/133730255/0be1ad3f-3bf0-4ec6-bf40-cda48bf820ca)
please assign me this issue

**Comment by apu52** [comment]
@sonakshisonkusare Welcome to METAVERSE!!!!!!!!!!
But Please try to raise the issues from next time with the help of the issue templates which are already present in this REPO. Sorry to close this issue for now as it does not follow the format.

**Comment by sonakshisonkusare** [comment]
I apologize for not using the issue template this time. I'll make sure to follow the correct format and use the templates provided in the repo for any future issues.
