### ISSUE TITLE
Play again button not apperaring in break breaker game

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#687]
**Describe the bug**

When you open the break breaker game and lose at the starting without any score, the play again button is not apperaring after the game ends. And also the favicon is not present for the break breaking game.

**Expected behavior**

Play again button should be visible after the game ends in the first attempt ( without any score ).

**Screenshots (Mandatory)**

![Screenshot (57)](https://github.com/apu52/METAVERSE/assets/131477601/4bcfb8e8-1fdf-47c9-ae8f-3614579580cc)

**Additional context (Mandatory )**

I would like to solve this bug.

***Are you contributing under any open-source program ?***

gssoc

**Comment by apu52** [comment]
@chaanakyaaM really good issue. you are assigned.

**Comment by chaanakyaaM** [comment]
Could you add level1 label, thank you

**Comment by apu52** [comment]
> Could you add level1 label, thank you

I will add the "lavel1/2/3" labels after the PR submission on the basis of the review . Don't worry . it's my responsibility.
