### ISSUE TITLE
Title and icon to code editor

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#688]
**Is your feature request related to a problem? Please describe.**

There is no title and icon to the code editor section.

**Describe the solution you'd like**

I would like to add the title and icon for the code editor

![image](https://github.com/apu52/METAVERSE/assets/131477601/b884f075-2a8e-4e84-9f63-baf9cd334f56)

**Describe alternatives you've considered**

**Additional context (Mandatory )**

I would like to add the title and icon to the code editor using html.

***Are you contributing under any open-source program ?***

gssoc

**Comment by apu52** [comment]
@chaanakyaaM Already you are assigned to an issue. & as per the rules of this REPO I can't assign you this issue right now. until you complete the previous issue

**Comment by apu52** [comment]
I am not closing this issue right now. After Submission of the previous issue just ping me here so that I can assign you this issue.

**Comment by chaanakyaaM** [comment]
Okay

**Comment by apu52** [comment]
@chaanakyaaM you are assigned.
