### ISSUE TITLE
Hover effect not working properly to myntra clone website

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#689]
**Describe the bug**

The hover effect on the nav bar links are not working properly 

**Expected behavior**

The bottom line should expand 100% to total text while hovered on it.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/METAVERSE/assets/131477601/c2bd2608-79c8-4971-b3d5-2e89c1e7d3c4)

**Additional context (Mandatory )**

I would like to fix this bug.

***Are you contributing under any open-source program ?***

gssoc

**Comment by chaanakyaaM** [comment]
apologies, i dont know that.

**Comment by apu52** [comment]
> apologies, i dont know that.

no matter. Just go through Contributing.md file before contributing fromnext time

**Comment by chaanakyaaM** [comment]
Sure
