### ISSUE TITLE
Add Audio Visualizer Project

### ISSUE THREAD

**Issue by fdciabdul** [apu52/METAVERSE#69]
Hello , i'm making some project called "Audio Visualizer" yes , of course that's visualizing audio from remote url , built by Html , css , and Javascript

**Expected behavior**

When a user inputs a remote URL, the Audio Visualizer should generate and display a visual representation of the audio from that URL.
For making this 

**Screenshots (optional)**

**Additional context (Mandatory )**

- [X] I am a contributor in OSEN open source programme

- [X] I am a contributor in HACTOBERFEST 2023

**Comment by apu52** [comment]
@fdciabdul Welcome to METAVERSE!
Please go through contributing.md file before PR
