### ISSUE TITLE
Social Media Icons not navigating to their respectives handles

### ISSUE THREAD

**Issue by Samridhi002** [apu52/METAVERSE#690]
### Description:
When I click on the social media icons (GitHub, Twitter and LinkedIn) at the bottom of the About page, they do not navigate to their respective social media pages. And moreover the old logo of Twitter should be replaced by new one.

### Steps to Reproduce:

1. Open the home page of the Metaverse website and navigate to About page.
2. Scroll down to the bottom in the footer section where the social media icons are located.
3. Click on any of the social media icons (e.g., GitHub, Twitter).

### Expected Behavior:
Clicking on a social media icon should navigate to the corresponding social media page.

### Attachment:

![Screenshot (24)](https://github.com/apu52/METAVERSE/assets/169380578/afb24528-e0d8-4e6a-9c73-afe2a06847c8)

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***
GSSoC'24

Hii @apu52 
I can solve this issue once you assign me under GSSoC'24. Thank You!

**Comment by apu52** [comment]
@Samridhi002 you are assigned.

**Comment by Samridhi002** [comment]
> @Samridhi002 you are assigned.

Thank You!
