### ISSUE TITLE
Able to change year in calendar

### ISSUE THREAD

**Issue by Chelseasingla1** [apu52/METAVERSE#691]
**Is your feature request related to a problem? Please describe.**
User cant change year in calendar directly

**Describe the solution you'd like**
I would like to add a feature where user can directly change year.

**Describe alternatives you've considered**

**Additional context (Mandatory )**
![image](https://github.com/apu52/METAVERSE/assets/129886894/0ca98aa3-ac4f-4e06-94b0-b42258e77d5c)

***Are you contributing under any open-source program ?***
Please assign me this issue under GSSoC'24.

**Comment by apu52** [comment]
@Chelseasingla1 you are assigned.

**Comment by nandita27iitp** [comment]
@apu52 can i work on it
