### ISSUE TITLE
Change the twitter icon to X

### ISSUE THREAD

**Issue by AkhilaSunesh** [apu52/METAVERSE#692]
Project number 15 (Login page)
![image](https://github.com/apu52/METAVERSE/assets/140897461/b8833b21-e1ed-4be3-9602-745aac4e6bcc)

**Describe the bug**

The twitter icon is incorrect the application is renamed as 'X'.

**Expected behavior**
Replace the icon

**Screenshots (Mandatory)**
![image](https://github.com/apu52/METAVERSE/assets/140897461/2bb9b6a2-f02f-4a54-a2e4-c84f81ad2621)
it should be changed to
![image](https://github.com/apu52/METAVERSE/assets/140897461/63de0de3-fe0c-48b0-8f7b-c5a614a7169f)

Kindly assign this issue to me

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***
yes 
Gssoc'24

**Comment by apu52** [comment]
@AkhilaSunesh you are assigned.
