### ISSUE TITLE
Feature_Request Forgot password form

### ISSUE THREAD

**Issue by AkhilaSunesh** [apu52/METAVERSE#693]
**Is your feature request related to a problem? Please describe.**
Project #15
Login page

**Describe the solution you'd like**
A forgot password page is important incase a user forgets his/her password

![image](https://github.com/apu52/METAVERSE/assets/140897461/5444d5c7-6c91-4ad1-a06d-77929e78e665)

along with that a Reset password form is also required
![image](https://github.com/apu52/METAVERSE/assets/140897461/7271b564-9a50-421e-92bd-3ff3436d6d86)

**Additional context (Mandatory )**
kindly assign this issue to me
***Are you contributing under any open-source program ?***

Gssoc'24

**Comment by apu52** [comment]
@AkhilaSunesh Already you are assigned to an issue. & as per the rules of this REPO I can't assign you this issue right now. until you complete the previous issue

**Comment by apu52** [comment]
I am not closing this issue right now. After Submission of the previous issue just ping me here so that I can assign you this issue.

**Comment by AkhilaSunesh** [comment]
@apu52 I have completed the previous task. Kindly assign me this issue

**Comment by apu52** [comment]
@AkhilaSunesh you are assigned.
