### ISSUE TITLE
Hover button in project #20

### ISSUE THREAD

**Issue by AkhilaSunesh** [apu52/METAVERSE#694]
**Describe the bug**
Project #20 
Popup Window
There is no hover feature for both the 'submit' button and 'ok' button. It makes it difficult for the user to navigate.

**Expected behavior**
A proper button which will change its feature when the user hovers over.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/METAVERSE/assets/140897461/9ac4ab18-1e15-43e8-a161-5b16f1abbf2c)
![image](https://github.com/apu52/METAVERSE/assets/140897461/75369326-c88d-46d0-8460-f399ffa38b4d)

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

Gssoc'24

**Comment by sohail0khan** [comment]
I want to work on this project plz assign this to me..

**Comment by apu52** [comment]
@AkhilaSunesh Please don't raise more than 2 issues at a time . I am closing this issue for now.

**Comment by apu52** [comment]
> Hello,
> 
> I am new to open source and very excited to contribute. I would love to work on this project. Could you please assign this issue to me?

This issue is already closed . But you can raise new issues on which you want to work on  in this repo .
HAPPY CODING!!!!!!!!!!!!!!!!
