### ISSUE TITLE
BUG: Repo owner text overlaps on mobile

### ISSUE THREAD

**Issue by Stiffpixels** [apu52/METAVERSE#695]
**Describe the bug**
The repo owner name and text overlaps the profile picture and social media links.

**Expected behavior**
the heading and name should always be above the profile picture

**Screenshots (Mandatory)**
mobile:
![Screen Shot 2024-05-31 at 19 54 35](https://github.com/apu52/METAVERSE/assets/32983571/31299e46-705a-42e5-bc0f-dcb60902f526)

desktop and tablet:
![Screen Shot 2024-05-31 at 19 56 58](https://github.com/apu52/METAVERSE/assets/32983571/ca7a7470-9257-46a3-b67a-9758b3639637)

**Additional context (Mandatory )**

Contributing under gssoc 24'

**Comment by apu52** [comment]
@Stiffpixels you are assigned.

**Comment by Stiffpixels** [comment]
> @Stiffpixels you are assigned.

Can you add the level label as well

**Comment by apu52** [comment]
> > @Stiffpixels you are assigned.
> 
> Can you add the level label as well

I have added
