### ISSUE TITLE
Feature_Request add Food website logo

### ISSUE THREAD

**Issue by jayanththalla** [apu52/METAVERSE#696]
**Is your feature request related to a problem? Please describe.**

Add logo to the food ordering website

**Describe the solution you'd like**

Add the logo favicon to the website and also in the navbar of the food website 

**Additional context (Mandatory )**
please assign me @apu52 
***Are you contributing under any open-source program ?***

gssoc

**Comment by apu52** [comment]
@jayanththalla you are assigned.
