### ISSUE TITLE
Adding Login and Signup page in Myntra Clone

### ISSUE THREAD

**Issue by RithikaSundaram** [apu52/METAVERSE#697]
**Is your feature request related to a problem? Please describe.**
By adding the signup and login features will helps to keep track of the users .It is very important for a website to have an login and sign up based user authentication.

**Describe the solution you'd like**
User Signup: Allow new users to create accounts by providing necessary information such as username, email, and password.
User Login: Enable existing users to log in to their accounts using their email and password.
Session Management: Implement session management to keep users logged in across different pages and visits, with options for users to log out.

**Describe alternatives you've considered**
Third-Party Authentication Services: Using third-party authentication providers like Google, Facebook, or GitHub for user login.

**Additional context (Mandatory )**
Implementing user authentication is crucial for the website's growth and security. It will enable features such as personalized content, user-specific settings, and a better overall user experience.

***Are you contributing under any open-source program ?***
Yes

**Comment by RithikaSundaram** [comment]
I am very interested in working on this issue pleas assign this to me.

**Comment by apu52** [comment]
@RithikaSundaram you are assigned.

**Comment by RithikaSundaram** [comment]
hello @apu52 i am not able to clone your repo as the size is large what to do?

**Comment by apu52** [comment]
> hello @apu52 i am not able to clone your repo as the size is large what to do?

if you really can't clone the repo , Then after forking the repo try to clone it through HTTPs or SSH or u can simply download the ZIP file of the repo to download the repo

**Comment by RithikaSundaram** [comment]
Ok let me try this
