### ISSUE TITLE
Adding alarm clock in Digital Clock

### ISSUE THREAD

**Issue by RithikaSundaram** [apu52/METAVERSE#698]
**Is your feature request related to a problem? Please describe.**
The current digital clock application does not include an alarm feature. Adding an alarm clock will enhance the functionality of the digital clock, allowing users to set and manage alarms for various purposes, such as waking up, reminders, or scheduling tasks.

**Describe the solution you'd like**
Alarm Setup: Provide an interface for users to set multiple alarms. Users should be able to specify the time, label the alarm, and choose if it repeats on specific days.
Alarm Notifications: When an alarm goes off, the application should notify the user with a sound and a visual alert.
Snooze Option: Include a snooze option that allows users to delay the alarm for a customizable amount of time.
Alarm Management: Allow users to view, edit, and delete existing alarms easily.
Customization: Enable customization of alarm tones and volume.

**Describe alternatives you've considered**
Third-Party Alarm Apps: Relying on external alarm clock applications, but this requires users to switch between apps.

**Additional context (Mandatory )**
Implementing an alarm clock feature will make the digital clock application more versatile and useful for everyday tasks. It can help users manage their time better and ensure they don't miss important events or reminders.

***Are you contributing under any open-source program ?***
Yes

**Comment by RithikaSundaram** [comment]
Please assign me this issue.

**Comment by apu52** [comment]
@RithikaSundaram  Already you are assigned to an issue. & as per the rules of this REPO I can't assign you this issue right now. until you complete the previous issue

**Comment by apu52** [comment]
I am not closing this issue .Just complete the previously assigned issue & after that ping me here , then I will assign you this issue

**Comment by nandita27iitp** [comment]
@apu52 Can I work on it

**Comment by RithikaSundaram** [comment]
@apu52 I have completed and have raised the PR for the previous assigned issue. Can I work on it now?

**Comment by apu52** [comment]
@RithikaSundaram I have assigned you .now u can submit your PR & start working on this issue.
