### ISSUE TITLE
Adding the Search Bar in Book review

### ISSUE THREAD

**Issue by RithikaSundaram** [apu52/METAVERSE#699]
**Is your feature request related to a problem? Please describe.**
Currently, the book review application lacks a search functionality, making it difficult for users to find specific book reviews. Users must scroll through a large number of reviews, which is time-consuming and inefficient.

**Describe the solution you'd like**
I propose adding a search bar to the book review application with the following features:

Search Functionality: Users should be able to type in keywords (e.g., book titles, authors, genres) to find relevant book reviews quickly.
Auto-Suggestions: As users type, the search bar should provide auto-suggestions to help them find what they are looking for faster.
Filters: Allow users to filter search results by criteria such as rating, date, and review length.
Highlighting Search Terms: Highlight the keywords in the search results to help users easily identify relevant information.
Responsive Design: Ensure the search bar is accessible and functional across different devices and screen sizes.

**Describe alternatives you've considered**
Category Navigation: Implementing a category-based navigation system where users can browse reviews by predefined categories, but this may still require a lot of navigation and may not be as efficient as a search bar

**Additional context (Mandatory )**
Adding a search bar will significantly improve the user experience by making it easier and faster for users to find specific book reviews. It will enhance the overall usability of the application and encourage users to spend more time reading and engaging with the content.

***Are you contributing under any open-source program ?***
Yes

**Comment by RithikaSundaram** [comment]
Please assign this issue to me.

**Comment by apu52** [comment]
@RithikaSundaram this is a good issue .But as per the rule of the repo . I have to close this issue .
Please don't raise more than 2 issues at a time. You can raise this issue again after completion of the previous 2 issues.
