### ISSUE TITLE
Add project- Tip Calculator

### ISSUE THREAD

**Issue by Aditi22Bansal** [apu52/METAVERSE#701]
**Is your feature request related to a problem? Please describe.**

It involves building a simple interface where users can input their bill amount, select a tip percentage, and then see the calculated tip and total amount. 

**Describe the solution you'd like**

 input fields for the bill amount and tip percentage, a button to trigger the calculation, and elements to display the results.

**Describe alternatives you've considered**

tip, bmi, weight, expense,etc calculators

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes, GSSOC'24

**Comment by apu52** [comment]
@Aditi22Bansal you are assigned.

**Comment by apu52** [comment]
@Aditi22Bansal welcome to METAVERSE!!!!!!!!!!!!
But adding a project in this repo is not a valid contribution . Sorry to close this issue.
