### ISSUE TITLE
Add project- Bill-Splid

### ISSUE THREAD

**Issue by vaibhav211002** [apu52/METAVERSE#703]
**Is your feature request related to a problem? Please describe.**
Involves building  a Bill-splid where people can add their group members names and the money they spend along with on which and it would have suggested payments . Would also contain a summary of their payments .

**Describe the solution you'd like**
Would contain a input name field , input money spend , and would contain the suggested payments that wouyld be calculated simultaneously.

**Describe alternatives you've considered**
Bill-tracker , Bill-splid or anything related to Bill calculation

**Additional context (Mandatory )**
This application will be very usesull for calculation of the bill or any trip payments that is made by many people and then divide among everyone .

***Are you contributing under any open-source program ?***
Yes Contributing in Gssoc'24

**Comment by vaibhav211002** [comment]
Please assign me this It Will be great to work on this .

**Comment by apu52** [comment]
@vaibhav211002  welcome to METAVERSE!!!!!!!!!!!!
But adding a project in this repo is not a valid contribution . Sorry to close this issue.
