### ISSUE TITLE
Bug:The achievements are not visible on mobile

### ISSUE THREAD

**Issue by Stiffpixels** [apu52/METAVERSE#705]
**Describe the bug**
On mobile the achievements of the repo owner are not visible properly as they don't have enough space

**Expected behavior**
On mobile the layout should be split into columns instead of rows

**Screenshots (Mandatory)**
![Screen Shot 2024-06-01 at 08 45 31](https://github.com/apu52/METAVERSE/assets/32983571/5410f8d2-aadd-4f27-b120-c979d351b0c3)

**Additional context (Mandatory )**
fixed would look like:
![Screen Shot 2024-06-01 at 08 57 01](https://github.com/apu52/METAVERSE/assets/32983571/c869d453-9533-455f-8af9-cfd02bdf7fc5)

***Are you contributing under any open-source program ?***
Gssoc 24'

**Comment by apu52** [comment]
@Stiffpixels you are assigned. But please Complete the previous PR
