### ISSUE TITLE
The mouse cursor on mobile

### ISSUE THREAD

**Issue by Stiffpixels** [apu52/METAVERSE#706]
**Describe the bug**
The mouse cursor is not needed on mobile and tablet devices.

**Expected behavior**
It should be set to display none for tablet and mobile screens.

**Screenshots (Mandatory)**
![Screen Shot 2024-06-01 at 09 03 27](https://github.com/apu52/METAVERSE/assets/32983571/4e0df49c-98f7-4cbb-8bed-be68684d6e05)

***Are you contributing under any open-source program ?***
gssoc 24'

**Comment by apu52** [comment]
@Stiffpixels I am not assigning you this issue right now . First complete the previous PR & then only I will assign you this issue.

**Comment by Stiffpixels** [comment]
can you assign it now @apu52

**Comment by apu52** [comment]
@Stiffpixels u are assigned.
