### ISSUE TITLE
Adding BMR calculator in project

### ISSUE THREAD

**Issue by agastya3636** [apu52/METAVERSE#707]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Calculates the Basal Metabolic Rate of a person using height, weight & age.

**Describe alternatives you've considered**

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes I am contributing under gssoc24.

**Comment by apu52** [comment]
@agastya3636 Adding a project in this repo is not a valid contribution in this repo . Sorry to close this repo.
