### ISSUE TITLE
Adding Light mode in contact us page

### ISSUE THREAD

**Issue by agastya3636** [apu52/METAVERSE#709]
**Describe the bug**

Every page has light dark mode except contact us

**Expected behavior**

**Screenshots (Mandatory)**

![image](https://github.com/apu52/METAVERSE/assets/124435030/0793bdc2-78ed-4e30-bd11-47f05197cf09)

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes I am contributing under gssoc24

**Comment by agastya3636** [comment]
@apu52 Please assign it to me

**Comment by apu52** [comment]
@agastya3636 you are assigned.
