### ISSUE TITLE
URL SHORTENER

### ISSUE THREAD

**Issue by Geeks-Arpan** [apu52/METAVERSE#71]
**URL SHORTENER**
A URL shortener is a website that shortens a long URL (Uniform Resource Locator) into a shorter, unique link. The shortened URL redirects to the original long URL when clicked.

I have completed this project by using html, css and javascript.

**Screenshots (optional)**
![Screenshot 2023-10-27 112438](https://github.com/apu52/METAVERSE/assets/99377659/b7919e28-b351-4b30-987a-3416008b5144)

- I am a contributor in OSEN open source programme
- I am a contributor in HACTOBERFEST 2023

**Comment by apu52** [comment]
@Geeks-Arpan please fill up the issue properly

**Comment by Geeks-Arpan** [comment]
@apu52 ok

**Comment by apu52** [comment]
@Geeks-Arpan Welcome to Metaverse!!!!!!!
Please go through contributing.md before contributing
