### ISSUE TITLE
Adding back to top icon to food ordering website

### ISSUE THREAD

**Issue by SuhainaFathimaM** [apu52/METAVERSE#712]
**Is your feature request related to a problem? Please describe.**

Adding back to top icon to food ordering website

![image](https://github.com/apu52/METAVERSE/assets/153417476/57ddba87-be6c-46d1-bae2-c872b7986ecb)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

I am contributing under GSSoC 2024
I would like to work on this issue

**Comment by apu52** [comment]
@SuhainaFathimaM you are assigned.
