### ISSUE TITLE
Feature_Request adding the cotributors profile in the about us page

### ISSUE THREAD

**Issue by CoderSwarup** [apu52/METAVERSE#714]
**Is your feature request related to a problem? Please describe.**

in the about us page their is give the Details about the project

i want to add the contributors profile on the About us page where the others can see the the contributors of the project

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

i want to work on this issue please assign m this issue

**Comment by apu52** [comment]
@CoderSwarup you are assigned.

**Comment by CoderSwarup** [comment]
> @CoderSwarup you are assigned.

Ok
