### ISSUE TITLE
[Feature Request]: ADD The PROJECT MAINTAINERS in the CONTACT US PAGE

### ISSUE THREAD

**Issue by apu52** [apu52/METAVERSE#716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the contact us page there is only present the description of the Repo owner .
There are also 3 other Co-project maintainer in this repo . I want to add their details also in the contact us page 

### Use Case

Use the current style to add their sections in the contact us page

- collect the details of the contributors  from the README md file
- make the style same as it is in the Contact us page
- Also add their Achievements , social(linkedin link) 

### Benefits

The contact us page should be dedicated to all the project  maintainers . So contributors will also be able to have a good idea about the repo

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/114172928/e3360d63-17f1-4fa9-918f-ec6b61bb7f07)

these are 3 co-maintainers of the repo

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
### This issue is Under GSSOC'24 . Whoever wants to contribute in this ISSUE Comment first as well as FAST. Whoever comments first she/he will be assigned. So HURRY UP!!!!!!

**Comment by Tirth-chokshi** [comment]
Hey @apu52 I can add their details in contact us page. can you please assign me this issue under gssoc-24

**Comment by apu52** [comment]
okay @Tirth-chokshi welcome to METAVERSE!!!!!!
You are assigned .Complete this PR following the rules mentioned in the issue properly & try to submit your PR within 5 days.
