### ISSUE TITLE
[Bug]: No icon for food delivery website

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no icon present for the food delivery website.

### Expected behavior

There has to be a icon for the food delivery website

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/131477601/6cb80663-2c15-4bd5-9401-f531e15cfca3)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by TheMystic07** [comment]
can u please assign this issue to me

**Comment by apu52** [comment]
@chaanakyaaM this issue has already been resolved & now we have a favicon icon in the website now 

![image](https://github.com/apu52/METAVERSE/assets/114172928/de2409a1-9dac-4f32-87c7-23951c7bc30d)

So Thanks for raising this issue but I have to close it for now as completed.
