### ISSUE TITLE
Partially Logo hidden in the website

### ISSUE THREAD

**Issue by harsh02mishra** [apu52/METAVERSE#721]
The logo of the food website is partially hidden .

![HiddenLogo](https://github.com/apu52/METAVERSE/assets/144336311/5ce1e167-d12a-4873-b7b9-57c5a2df6bdf)

@ apu52 Please assign this task to me I would like to resolve it.

**Comment by TheMystic07** [comment]
@apu52  can u please assign this issue to to me 🥺

**Comment by apu52** [comment]
@harsh02mishra please try to raise the issues with the help of the issue templates which are already present in the repo , so that the issue will be more understandable 
Sorry to close this issue for now.

**Comment by apu52** [comment]
> @apu52 can u please assign this issue to to me 🥺

This

**Comment by harsh02mishra** [comment]
@apu52 may I raise the same issue with the issue template?
