### ISSUE TITLE
Add logo in the website of Spotify Clone.

### ISSUE THREAD

**Issue by harsh02mishra** [apu52/METAVERSE#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It makes the website look unique and stand out from others.
A logo makes your website look serious.

### Use Case

It makes your store look nice and professional.
It helps attract employers or clients by showing you are serious about your work.

### Benefits

A good logo makes your website look better than others, helping you stand out.

### Add ScreenShots

![Adding Logo](https://github.com/apu52/METAVERSE/assets/144336311/6f77a193-2421-4a3d-b7ee-c432f145e22f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@harsh02mishra I have already assigned you .But first can you please share which logo you want to add in this project??

**Comment by harsh02mishra** [comment]
![SpotifyLogo](https://github.com/apu52/METAVERSE/assets/144336311/65f817bb-7128-4371-99f3-bbd92edeb040)
Spotify Logo
