### ISSUE TITLE
[Bug]: Adding Styles and hovering effect and animations to the travel website

### ISSUE THREAD

**Issue by SuhainaFathimaM** [apu52/METAVERSE#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Adding Styles and hovering effect and animations to the travel website

1. Adding styles to navbar
2. Hovering effects for cards
3. Adding styles to buttons
4. Adding styles to newsletter input
5. Adding styles to footer

### Expected behavior

1. Adding styles to navbar
2. Hovering effects for cards
3. Adding styles to buttons
4. Adding styles to newsletter input
5. Adding styles to footer

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/153417476/0e8829e7-7faa-4a07-8c83-ae7240ca5880)

![image](https://github.com/apu52/METAVERSE/assets/153417476/0ea2c803-fc25-4678-8f89-d1eb1209d863)

![image](https://github.com/apu52/METAVERSE/assets/153417476/0eccb9a9-b24d-41e9-a2f9-74fabb97d825)

![image](https://github.com/apu52/METAVERSE/assets/153417476/0bc4ac6e-273b-40ba-ac73-3908f7bf9bf5)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SuhainaFathimaM** [comment]
@apu52 I would like to work on this issue. Please assign me this issue under GSSoC

**Comment by apu52** [comment]
@SuhainaFathimaM you are assigned. you can start working on this issue.
