### ISSUE TITLE
[Feature Request]: Added visibility to Burger Logo in Food Ordering website in dark mode.

### ISSUE THREAD

**Issue by Suvendu-UI** [apu52/METAVERSE#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I have added the visibility of the Burger logo and added a clicking animation to the buttons and added glow to the menu .

### Use Case

This would make the website more creative.

### Benefits

This is the video of website before changes

https://github.com/apu52/METAVERSE/assets/144688422/4b8b0056-a09a-4d9b-a014-b22a654b929a

This is the video after the changes made to the website

https://github.com/apu52/METAVERSE/assets/144688422/2ca949c2-4364-4b71-aa58-3d119ac4e8f4

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Suvendu-UI you are assigned.
