### ISSUE TITLE
[Feature Request]:Dockerize the app

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [apu52/METAVERSE#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to tell you that we have to dockerize the app because when in future anyone want to clone our app and use our app in different operating system then our project dont run in their system so for removing this problem we have to dockerize the app so that everyone can easily use our app 

### Use Case

when someone clone or run app in different operating system
 when someone use different version of package in own system 
 in future when this version in corrupted then someone want to use this app

### Benefits

i

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@agarwalhimanshugaya thanks for raising the issue . you are assigned.
