### ISSUE TITLE
Add Virtual Piano

### ISSUE THREAD

**Issue by VaishnaviMankala19** [apu52/METAVERSE#729]
As a GSSoC'24 Contributor, I am excited to propose the addition of a Virtual Piano Game to our open-source repository. This project will offer an interactive and accessible piano-playing experience, designed for users of all skill levels. Key features of the Virtual Piano Game include:
-> Adjustable Volume Controls
-> Intuitive User Interface

**Comment by apu52** [comment]
@VaishnaviMankala19 adding a new project is not a valid contribution in this repo .
So I have to close this issue .
Hope to see more of your contributions.
