### ISSUE TITLE
[Feature Request]: Adding functionality to add your own joke.

### ISSUE THREAD

**Issue by Abhishek-465** [apu52/METAVERSE#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add an extra feature to add our own jokes. 

### Use Case

This will have an additional feature implementing backend and database.

### Add ScreenShots

![Screenshot (59)](https://github.com/apu52/METAVERSE/assets/127030695/3e7c59e2-1f2e-4e4f-a89f-cf552f3c4243)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Abhishek-465 you are assigned
