### ISSUE TITLE
[Feature Request]:   Add Cut Off Calculator  New Project 

### ISSUE THREAD

**Issue by SuhainaFathimaM** [apu52/METAVERSE#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding engineering and medical cut off calculator

The calculator would input 3 subject marks{
Physics, Chemistry, Maths/ Biology}
and will give the cut off as output..

(Physics/2+Chemistry/2)+(Maths)==Output
(Physics/2+Chemistry/2)+(Biology)==Output

@apu52 I would like to work on this under GSSoC

### Use Case

Adding engineering and medical cut off calculator

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@SuhainaFathimaM adding a new project in this repo is not a valid contribution .thanks for raising the issue but I have to close the issue .
