### ISSUE TITLE
[Documentation Update]: 

### ISSUE THREAD

**Issue by Abhishek-Sood** [apu52/METAVERSE#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

i d like to make a static documentation site using markdown files

### Suggested Change

i ll be using mkdocs platform for this static documentation site

### Rationale

i documentation site is neccessary for any project 

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [x] I have starred the repository

**Comment by apu52** [comment]
@Abhishek-Sood I have assigned you . But can you please elaborate about the changes in the documentation you wan to add using mkdocs???

**Comment by Abhishek-Sood** [comment]
ya basically a static documentation site will be there so that if anyone want to study documentation of the project they can go to the site built using mkdocs which will be much more convinient and somewhat interacting rather than studying pages. i ll assemble all the markdown files and arrange them onto the site. If something new would be required then ill write the content down for that particular tab if needed ..also id make sure that if any change in markdown files are made then they are automatically made on the final site that will be deployed in the future.

also i wanted to ask if there is a documentation already done of this project?
