### ISSUE TITLE
[Feature Request]: Enhancing the overall User Interface of the Metaverse Website

### ISSUE THREAD

**Issue by agrawal-yash** [apu52/METAVERSE#739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I've noticed that the current UI design feels outdated, less appealing and the CSS could use some enhancements to improve the overall user experience of the Metaverse website. The positioning & sizing of the navbar buttons also feels somewhat less appealing. The background, fonts, colour scheming could be updated to a more classic and minimalist look. The projects list could also be displayed in a more modern and elegant way. 

### Use Case

I am capable of contributing to the following enhancements:

1. Enhancing the website design to achieve a more minimalist appearance.
2. Introducing a more refined colour scheme throughout the website.
3. Elevating the styling of input fields and buttons for a more polished interface.
4. Changing the font to a more modern & elegant font for a better user experience.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@agrawal-yash you are assigned. Can you please give me some ss/pics that which UI enhancement you want to add in this website as I have already found that the website is really cool & working well

You can still start work on this issue .

**Comment by agrawal-yash** [comment]
Absolutely @apu52, the website looks cool but I think if it becomes more minimal, it might look cool. I have attached an image, consider it just a reference, because I will definitely work more on it and it might come out different. 
Also can you assign a level label for gssoc in this issue? 

![image](https://github.com/apu52/METAVERSE/assets/139786074/5c5b25db-b551-472d-818b-5cb2503e16b3)
