### ISSUE TITLE
[Feature Request]: Add logo and title to insta_clone

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is no favicon and title to the instagram clone, i would like to add the icon and title to the insta clone.

### Use Case

This favicon and title are the most important aspects of the website (insta_clone).
These make the foundation of the website look(UI).

### Benefits

This makes the website look more like instagram clone.
This makes the website look more professional  and user friendly.

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/131477601/1819dadb-2b40-4838-9cfe-58fa50e6604b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@chaanakyaaM you are assigned.
