### ISSUE TITLE
[Bug]: Adding Styles and hovering effect and animations to the Organica

### ISSUE THREAD

**Issue by SuhainaFathimaM** [apu52/METAVERSE#742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding Styles and hovering effect and animations to the Organica website

![image](https://github.com/apu52/METAVERSE/assets/153417476/beff8994-7551-4a6e-8cfd-902a527d7138)

### Expected behavior

Adding transitions and animations to organica website

@apu52 Assign this issue under GSSoC

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@SuhainaFathimaM you are assigned.
