### ISSUE TITLE
[Feature Request]:  Update button click event in app.js and add new button in index.html  

### ISSUE THREAD

**Issue by Suvendu-UI** [apu52/METAVERSE#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am adding back button in sidebar and adding some details in the detail section , and also changing the app.js section for the back button.

### Use Case

The back button will help in closing the sidebar when not in use and the additional detail will help in details with the company. 

### Add ScreenShots

This is the website before changes
![Detail](https://github.com/apu52/METAVERSE/assets/144688422/9d512623-10b7-4c30-937a-f594e34ebc92)
![Sidebar](https://github.com/apu52/METAVERSE/assets/144688422/3185cdef-d18c-4991-a814-de049dd2ea6f)
This is after the changes 
![updatedDetail](https://github.com/apu52/METAVERSE/assets/144688422/de7ba6a1-72a0-44eb-a190-f39abec90bbc)
![updatedSidebar](https://github.com/apu52/METAVERSE/assets/144688422/23c6f109-29b8-4083-8f7c-2f038478a82f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Suvendu-UI assigned you .start working on it. good issue.
