### ISSUE TITLE
[Feature Request]: Consistent Theme toggle state across different pages

### ISSUE THREAD

**Issue by shubhammjha22** [apu52/METAVERSE#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The theme toggle switch should maintain its state (dark or light mode) consistently across different pages on the website. Currently, the state is not persistent, causing the theme to reset when navigating between pages.

### Use Case

It would make the UX better as the user won't have to set the theme manually for each page.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by shubhammjha22** [comment]
@apu52  Kindly assign this issue to me

**Comment by apu52** [comment]
@shubhammjha22 good issue . you are assigned. Start working on it.

**Comment by shubhammjha22** [comment]
@apu52 Hey i have made the PR , kindly review it
