### ISSUE TITLE
[Feature Request]: Automate greeting using Github bot 🤖

### ISSUE THREAD

**Issue by shubhammjha22** [apu52/METAVERSE#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As the contributor count rises on the repo, it becomes increasingly challenging for maintainers to personally greet and encourage each contributor for their valuable input. Equally important is the reminder for them to review the project's contribution guidelines.

I would like to add a github bot , which would greet the user whenever there is a PR request or a issue raised
with something like

### Use Case

For PR
"Awesome work, @username! 🎉 Thank you for submitting pull request.
We truly appreciate your contribution and efforts to enhance our project.
Please ensure that you have followed the contributing guidelines for a smooth review process"

For Issue
"Hello @userName,
Thanks for creating this issue and contributing to Tourism!
@admin will review your issue soon and provide feedback. In the meantime, feel free to join the discord community. Please ensure that you have followed the contributing guidelines for a smooth review process"

### Add ScreenShots

![Screenshot 2024-05-22 140602](https://github.com/apu52/METAVERSE/assets/68507333/bcb52136-f215-4c4a-b1a6-e760e517ede8)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@shubhammjha22 I have assigned you .But please at first try to complete the [previously assigned PR.

**Comment by shubhammjha22** [comment]
@apu52   i have made the PR , kindly review it . 

And also can i work on that Myntra Contact Page Error ? or you want to leave it as it is right now
