### ISSUE TITLE
[Bug]: Myntra Clone website 404 error on contact page

### ISSUE THREAD

**Issue by shubhammjha22** [apu52/METAVERSE#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is 404 error in the Myntra clone project when click on Contact in Nav bar.

### Expected behavior

The contact page should appear 

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/68507333/7275a91b-75fc-42dd-b5c4-90645b41d4a0)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@shubhammjha22 Please don't raise more than 2 issues at a time else I have to close this issue as it violates the contribution guidelines of the repo .please try to follow the CONTRIBUTING.md file before contributing in this repo .

I am closing this issue for now. At first complete the 2 previously assigned issues.
