### ISSUE TITLE
[Feature Request]: I want to add a Movie Recommender Website made in ReactJs and TailwindCSS. I want to contribute under GSSOC'24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [apu52/METAVERSE#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a Movie Recommender Website made in ReactJs and TailwindCSS. I have made this website from scratch. It will be an addition to the list of projects in the website.

### Use Case

It will be an addition to the list of projects in the website.

### Add ScreenShots

Here is an SS of my site : 

![movie1](https://github.com/apu52/METAVERSE/assets/123104247/bf76116b-809e-44bf-9d5d-b3a5af025ac3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ParnaRoyChowdhury777 adding a project in the repo is not a valid contribution . Please read all the rules mentioned in CONTRIBUTING.md before contributing.
Sorry to close this issue as unplanned.
