### ISSUE TITLE
add logo to the Book_review_website and title in the navbar

### ISSUE THREAD

**Issue by jayanththalla** [apu52/METAVERSE#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the Book_review_website page the logo is not present and title of the Book_review_website is not there in the navbar

### Use Case

add the logo in the main page and title

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/121346142/ee2875a7-05b8-4c2f-83d1-420b39be6372)

please assign me @apu52 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@jayanththalla u are assigned.
