### ISSUE TITLE
[Feature Request]: Add Scientific Calculator Project

### ISSUE THREAD

**Issue by komal-agarwal5** [apu52/METAVERSE#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I wish to add my project-Scientific Calculator.This simple and user-friendly calculator allows you to perform a variety of mathematical operations with ease.

### Use Case

The UI gives a replicatory image of a real world calculator

### Add ScreenShots

![scientific calculator](https://github.com/apu52/METAVERSE/assets/122633300/6b3605e6-7795-4af0-9ce3-a5c90dd8aa04)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@komal-agarwal5 adding a project is not a valid contribution in this repo . Please try to follow all the rules mentioned in CONTRIBUTING.md file before contributing. Sorry to close this issue .
