### ISSUE TITLE
[Feature Request]: i would like to add colour flipper project

### ISSUE THREAD

**Issue by veera6513** [apu52/METAVERSE#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 I would like to add color flipper project where user will have a option to change the project background color each time.

### Use Case

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by veera6513** [comment]
please suggestion this issue under Gssoc'24.

**Comment by veera6513** [comment]
please assign this issue on my name.

**Comment by apu52** [comment]
@veera6513 adding a project in this repo is not a valid contribution . please try to follow the rules mentioned in CONTRIBUTING.md before contributing. Sorry to close this issue  as unplanned.
