### ISSUE TITLE
[Feature Request]: Apple Vision Pro clone website

### ISSUE THREAD

**Issue by Archiesachin** [apu52/METAVERSE#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Apple Vision Pro website using HTML , CSS and JavaScript only. 

### Use Case

It will be a frontend project with scrolling animations and 3d objects. It will be a modern website which will be a valuable frontend tool. 

### Add ScreenShots

![Screenshot (1080)](https://github.com/apu52/METAVERSE/assets/103347688/1790749b-39f4-4236-9ad5-044efd7f97c0)

![Screenshot (1081)](https://github.com/apu52/METAVERSE/assets/103347688/1ca0c99c-03f1-4df2-b9c1-f00f4c451035)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Archiesachin   Adding a new Project in this repo is not a valid contribution in this repo . 
Sorry for any inconvenience .
But u can still make farther changes in the website(e.g - bug fix , feature add , documentation update ) & make new issues on this topics
