### ISSUE TITLE
[Bug]: Logos aren't visible in light mode

### ISSUE THREAD

**Issue by sristy17** [apu52/METAVERSE#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot from 2024-06-11 18-40-52](https://github.com/apu52/METAVERSE/assets/136837204/3f447584-134f-42d7-8a97-32bc12bd3ddb)

### Expected behavior

The logo must be of different colors in light mode(black).

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AnClicks** [comment]
Kindly assign this issue to me !

**Comment by aman7100** [comment]
Please assign this issue to me @apu52

**Comment by apu52** [comment]
@sristy17 u are assigned.
