### ISSUE TITLE
Add Animation in Cards and Text on Scroll

### ISSUE THREAD

**Issue by Skb08** [apu52/METAVERSE#770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add animations to cards and text that activate when the user scrolls down the page.

### Use Case

Adding animations to cards and text on scroll will enhance the user experience by providing a more engaging and interactive interface. This feature will make the website feel more dynamic and modern, improving user retention and satisfaction.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Skb08 u are assigned .But can u please provide some suggestions / some animation cards here which u want to add in the project??

**Comment by Skb08** [comment]
Link of aos animation: https://michalsnik.github.io/aos/

**Comment by apu52** [comment]
> Link of aos animation: https://michalsnik.github.io/aos/

That's great . Carry on with your PR waiting for your PR.
