### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by Skb08** [apu52/METAVERSE#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It's time-consuming and prone to errors when I need to manually convert currencies when dealing with international transactions or travel.

### Use Case

This feature aims to streamline currency conversion for users, eliminating the need for manual calculations or reliance on external tools. It enhances user experience by providing a convenient and accurate way to perform currency conversions within our platform.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Skb08 Adding a new Project in this PR is not a valid contribution in this repo . 
Sorry for any inconvenience .
But u can still make farther changes in the website(e.g - bug fix , feature add , documentation update ) & make new issues on this topics
