### ISSUE TITLE
[Bug]: Hover effect on the navbar

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello @ap
The navigation bar appears visually unappealing and cluttered, which negatively impacts the overall design and user experience. 

### Expected behavior

The goal should be to create a visually appealing and functional navigation system that enhances the overall user experience, rather than detracting from it with an overwhelming or disjointed design.

### Add ScreenShots

![Screenshot 2024-06-12 034114](https://github.com/apu52/METAVERSE/assets/129287425/ff03845f-a991-472d-81d3-7c616eb1e206)

Kindly assign this issue under GSSOC'24.
Thankyou

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@sakshiglaze You are GSSOC Contributor of SSOC Contributor ?

**Comment by sakshiglaze** [comment]
@anuragverma108 I am both. But there is something that you can mark only one then my priority would be GSSOC.
Thankyou.

**Comment by aman7100** [comment]
Can i work on this issue?
