### ISSUE TITLE
[Feature Request]: Adding RPS game 

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello  @apu52 
User will have one more option among the listed options. It just you can play Rock-Paper-Scissor Game. Try to win against computer and guess it's movements. AND LEARN TO BUILD ONE!!

### Use Case

A Rock-Paper-Scissor game--
Computer Opponent: Develop an opponent that can make intelligent choices, providing a challenging gameplay experience for the human player.
Autoplay Mode: Include an autoplay mode where the computer player competes against itself.
Real-time Scoring: Keep track of the scores for both the human player and the computer opponent in real-time. Display the scores prominently on the game interface to provide a sense of competition and progress.
Implementing persistent scoring in a rock-paper-scissors game, ensuring scores are not lost even after page reloads unless and until player resets the score.

### Benefits

It seems there is no game in the given list. 
Incorporating engaging games or interactive elements could significantly enhance user engagement and provide an even more effective learning experience.

### Add ScreenShots

![Screenshot 2024-05-15 155019](https://github.com/apu52/METAVERSE/assets/129287425/fda52022-7db2-4e64-92ce-88d2aa5d15a5)

I would like to add to this contribution under GSSOC'24.
Thankyou.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@sakshiglaze  Adding a new Project in this PR is not a valid contribution in this repo . 
Sorry for any inconvenience .
But u can still make farther changes in the website(e.g - bug fix , feature add , documentation update ) & make new issues on this topics
