### ISSUE TITLE
[Feature Request]: flight booking website

### ISSUE THREAD

**Issue by nagamukesh** [apu52/METAVERSE#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i already made a project which is essentially a flight booking website which have login/signup feature for user and for each user, he/she have a profile to see the details of his account, past transactions and user can select a flight, his/her desired class and then select available seats and can do payment(this section is made as a transaction) and there is also admin login so that the admin can change any details of the flights in the website(add,delete,change timings etc)
I made this website using HTML,CSS,js,node,express and MySQL as database

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@nagamukesh Adding a new Project in this PR is not a valid contribution in this repo . 
Sorry for any inconvenience .
But u can still make farther changes in the website(e.g - bug fix , feature add , documentation update ) & make new issues on this topics
