### ISSUE TITLE
[Bug]: Unnecessary Search Bar in About Us Section

### ISSUE THREAD

**Issue by aadii2504** [apu52/METAVERSE#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the About Us section of the website, there is a search bar that seems out of place and serves no clear purpose. Its presence detracts from the professional appearance of the page, making it look cluttered and less polished.

### Expected behavior

The About Us section should have a clean and professional layout. The search bar should be removed to enhance the page's aesthetic and usability, ensuring it aligns with the intended purpose and professional standard of the website.

### Add ScreenShots

![Screenshot (413)](https://github.com/apu52/METAVERSE/assets/119524954/624d2e0a-4c92-4e80-9ca7-a511c2d4b287)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by kom-senapati** [comment]
Its also in the contact us, have to remove that as well.

**Comment by aadii2504** [comment]
yup  , got it

**Comment by anuragverma108** [comment]
@aadii2504 You are GSSOC Contributor of SSOC Contributor ?

**Comment by aadii2504** [comment]
yup

**Comment by apu52** [comment]
> yup both

but @aadii2504 u have to choose on of the programmes as u can't be assigned in both of the programme . So please choose wisely so that mentors will assign u

**Comment by aadii2504** [comment]
GSSOC  is good to go
