### ISSUE TITLE
[Bug]: Style Issues with About Us page

### ISSUE THREAD

**Issue by kom-senapati** [apu52/METAVERSE#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. About Us Page:

    - Font Issues: The font used on the About Us page is not visually appealing or consistent with the rest of the website.
    - Text Size on Mobile: The text size on mobile devices is too small, making it difficult to read.

### Expected behavior

A good-looking about us page

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/92045934/dd7533fc-4579-455a-89ff-a15397428196)
![image](https://github.com/apu52/METAVERSE/assets/92045934/fddee613-49b0-4397-9de4-6b31796bf712)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@kom-senapati 
Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
