### ISSUE TITLE
[Feature Request]: Automatic Comment on Pull Request Raised

### ISSUE THREAD

**Issue by thevijayshankersharma** [apu52/METAVERSE#781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature requests the implementation of an automatic comment function that triggers whenever a new pull request is raised. The comment would contain pertinent context regarding the proposed changes, such as the purpose of the modifications, relevant issue or feature IDs, and any specific instructions for reviewers.

### Use Case

Enhancing Communication: The automatic comment would ensure that reviewers have all the necessary information upfront, facilitating a smoother and more efficient review process.
Improved Documentation: By providing essential context within the comment, this feature would enhance the documentation of each pull request, aiding in understanding the rationale behind the changes made.
Time Efficiency: Instead of relying solely on manual input for context, the automatic comment feature would save time for both the contributor and the reviewers by streamlining the process and reducing the need for back-and-forth clarification.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@thevijayshankersharma You are GSSOC Contributor of SSOC Contributor ?

**Comment by thevijayshankersharma** [comment]
@anuragverma108 actually I am both.

**Comment by apu52** [comment]
@thevijayshankersharma but  u have to choose on of the programmes as u can't be assigned in both of the programme . So please choose wisely so that mentors will assign u

**Comment by thevijayshankersharma** [comment]
@apu52 As of now please assign me GSSoc label

**Comment by apu52** [comment]
> @apu52 As of now please assign me GSSoc label

@thevijayshankersharma u are assigned.

**Comment by thevijayshankersharma** [comment]
> > @apu52 As of now please assign me GSSoc label
> 
> @thevijayshankersharma u are assigned.

Label ??
