### ISSUE TITLE
[Feature Request]: Add login and signup page in kitten page 

### ISSUE THREAD

**Issue by harsh02mishra** [apu52/METAVERSE#784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

By adding a login and signup page, users can buy products and record them in their account.

### Use Case

By creating an account, customers can save their preferences, view past orders, and receive personalized product recommendations.
Faster Checkout Process: Logged-in users can save their shipping and billing information for quicker checkouts, enhancing their shopping experience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
would you like to work on this ?  @harsh02mishra

**Comment by harsh02mishra** [comment]
Yes

**Comment by harsh02mishra** [comment]
Please assign it to me.

**Comment by heysagnik** [comment]
@harsh02mishra good to go 🥳
