### ISSUE TITLE
[UI Enhancement]: Enhance the UI for the food ordering website

### ISSUE THREAD

**Issue by meetalik8** [apu52/METAVERSE#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the menu is all cards lined up, by adding a hovering effect on the menu cards, it can increase the interactivity for the user.
The card can be made to pop out on hovered.

![image](https://github.com/apu52/METAVERSE/assets/102135323/19fc4a9f-5c33-4346-8794-cdf1bde26289)

### Use Case

It would improve not only the interactivity for the user, but also increase the overall appeal of the UI of the website.

Please assign this issue to me, I would love to work on this!

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
Assigned! @meetalik8 
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by meetalik8** [comment]
@heysagnik hello, can you label this under gssoc with levels please?
