### ISSUE TITLE
[Bug]: Adding Styles and hovering effect and animations to the Myntra clone Website 

### ISSUE THREAD

**Issue by SuhainaFathimaM** [apu52/METAVERSE#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding more styles to the cards hover effects can make them more attractive and visually appealing

@apu52 I am contributing under gssoc and ssoc also

### Expected behavior

Adding transitions and animations to myntra clone

### Add ScreenShots

[
![Screenshot 2024-06-15 011710](https://github.com/apu52/METAVERSE/assets/153417476/85eb37d0-9e64-4381-a9e3-5a6de53ca4b6)
![Screenshot 2024-06-15 011722](https://github.com/apu52/METAVERSE/assets/153417476/beae90cf-5693-4f48-b62d-f4e6a96a5f5e)
](url)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@SuhainaFathimaM You are GSSOC Contributor of SSOC Contributor ?

**Comment by SuhainaFathimaM** [comment]
@anuragverma108 I am contributing under both programs

**Comment by anuragverma108** [comment]
@SuhainaFathimaM It will be considered under one only. That you have to choose!

**Comment by SuhainaFathimaM** [comment]
@anuragverma108 Then I would like to contribute under GSSoC

**Comment by heysagnik** [comment]
@SuhainaFathimaM you are good to start 👍
