### ISSUE TITLE
[Feature Request]:  Add a alignment at About page

### ISSUE THREAD

**Issue by DevGajjar28** [apu52/METAVERSE#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In small devices an content not aligned well , it make worst to read the content.

### Use Case

by adding alignment the UI be should attractive.

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/145287513/11c6dc65-ede0-45fd-9b31-c4df2c61223d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@DevGajjar28 You are GSSOC Contributor of SSOC Contributor ?

**Comment by DevGajjar28** [comment]
> @DevGajjar28 You are GSSOC Contributor of SSOC Contributor ?

no , i am not

**Comment by apu52** [comment]
@DevGajjar28 u are assigned. Start working
