### ISSUE TITLE
[Feature Request]: UI enhancement for age calculator

### ISSUE THREAD

**Issue by HWKDS** [apu52/METAVERSE#795]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

**The UI is not satisfying  as some of the content is missing under css** 
![Screenshot from 2024-06-15 20-01-27](https://github.com/apu52/METAVERSE/assets/79627715/dc620f73-d4b7-4dab-90b9-9adcfc62d626)

**what content are missing** 
![Screenshot from 2024-06-15 20-02-12](https://github.com/apu52/METAVERSE/assets/79627715/8d193785-0884-45da-a340-63e3badacdc8)

### Use Case

make the user see the result 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@HWKDS Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by HWKDS** [comment]
Hey @anuragverma108, I have a suggestion, Should we maintain the UI with the white background as before and fix the CSS, or should we also include a dark mode toggle?

**Comment by anuragverma108** [comment]
@HWKDS You can also include a dark mode toggle !
