### ISSUE TITLE
I want to add Rock Paper Scissors Game.

### ISSUE THREAD

**Issue by subhasish-roy** [apu52/METAVERSE#8]
I wish to add a Rock Paper Scissors Game into this repository which i made using HTML, CSS and JavaScript.
Please assign it to me so that i can work on it.
Thank You...

**Comment by AbhishekMaurya2002** [comment]
can assign to me?

**Comment by apu52** [comment]
@subhasish-roy  Welcome to Metaverse!!!!!!!!!🥳
Thanks For raising the Issue. 👍

**Comment by apu52** [comment]
Please follow contributing.md file for the contribution details

**Comment by subhasish-roy** [comment]
thank you for assigning. will do that.
