### ISSUE TITLE
[Feature Request]: Change title and icon for gym website

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to change the title name and add icon for the gym website template.

### Use Case

This would add value to the website and make the website look more professional.

### Benefits

This helps the website to look bug free and attractive.

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/131477601/6b0d29f8-9981-4460-8a28-bed245a855a2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@chaanakyaaM you are set to work on this

**Comment by neetuyadav23** [comment]
Please assign this issue to me.
