### ISSUE TITLE
[Feature Request]: add icon and title to apple clone

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add icon and title to the apple clone webite.

### Use Case

This helps the website look more attractive and professional

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/131477601/f48eb994-40b8-4afa-9aa1-874cfc32db88)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@chaanakyaaM you are good to start 😀

**Comment by chaanakyaaM** [comment]
Would you please review this PR #812
