### ISSUE TITLE
[Feature Request]: add a logo to the career crafters

### ISSUE THREAD

**Issue by jayanththalla** [apu52/METAVERSE#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the main page of the career crafters logo is missing and also in the sidebar

### Use Case

By adding the logo it looks good 

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/121346142/6a0be2f1-5f4f-44c6-bd27-88f527f182a6)
please assign me @pa

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by jayanththalla** [comment]
> Hi, this issue is meant to participate either from one gssoc/ssoc So if you want to participate for gssoc I can assign you @jayanththalla

yes gssoc

**Comment by heysagnik** [comment]
@jayanththalla assigned you
