### ISSUE TITLE
[Bug]: no hover effect on about and contact button

### ISSUE THREAD

**Issue by sainathPatil09** [apu52/METAVERSE#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is no hover effect on about and contact button while there is hover effect on home button

https://github.com/apu52/METAVERSE/assets/155251909/2673e715-7a17-45ae-bcb8-2b56ac2b1f29

### Expected behavior

add hover effect on about and contact button

Tip: also add padding in contact button

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@sainathPatil09 are you contributing on behalf of gssoc or from ssoc ?

**Comment by apu52** [comment]
@sainathPatil09 are you contributing on behalf of gssoc or from ssoc ?

Otherwise we can't assign u

**Comment by sainathPatil09** [comment]
@apu52 sorry i am not from gssoc or ssoc, i am just here to learn contributing in open source

**Comment by apu52** [comment]
@sainathPatil09 okk u are assigned
