### ISSUE TITLE
[Feature Request]:  Add an "About" page for the Myntra Clone Website

### ISSUE THREAD

**Issue by Prutha-Upadhyay** [apu52/METAVERSE#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Myntra Clone section of the website currently does not have an "About" page. Adding an "About" page will provide visitors with more information about Cara and enhance their understanding of the section. 

### Use Case

Adding an "About" page for the Cara section will:

Provide visitors with detailed information about Cara, including its purpose and background.
Enhance the credibility and transparency of the website.
Increase user engagement by offering more context.

### Benefits

Improves user experience by providing more information.
Increases transparency and engagement with visitors.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@Prutha-Upadhyay Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
