### ISSUE TITLE
[Feature Request]: Want to Fix Ui Of Food Website

### ISSUE THREAD

**Issue by nishant0708** [apu52/METAVERSE#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently ui of foodwebsite is looking bad i want to fix that

### Use Case

It will enhance User Experience

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/101548649/d5dad8df-3cc3-46bf-90a2-c4dc455138d8)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@nishant0708 assigned for this issue too.
