### ISSUE TITLE
STACK

### ISSUE THREAD

**Issue by paulsuryanshu** [apu52/METAVERSE#82]
**Describe the project you want to add with tech stack**
Visualisation of stack using HTML,CSS, JAVASCRIPT

**Expected behavior**
we can perform basic stack operation push,pop,display....

**Screenshots (optional)**

**Additional context (Mandatory )**
 
- [X] I am a contributor in OSEN open source programme

 
- [X] I am a contributor in HACTOBERFEST 2023

**Comment by apu52** [comment]
@paulsuryanshu can you please attach some img of your project here in this issue?

**Comment by paulsuryanshu** [comment]
[image](https://github.com/paulsuryanshu/STACK/blob/main/stack/Screenshot%20(302).png)
