### ISSUE TITLE
[Feature Request]: Want to add bird shooting game

### ISSUE THREAD

**Issue by nishant0708** [apu52/METAVERSE#820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

want to add bird shooting game which will kill birds on double tap

### Use Case

It is fun addictive game

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@nishant0708 I have assigned you
