### ISSUE TITLE
[Feature Request]:  Adding follow us section in travel website footer

### ISSUE THREAD

**Issue by Gultreen** [apu52/METAVERSE#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add buttons that link to your social media profiles, encouraging visitors to follow you.
Builds a larger and more engaged online community.

### Use Case

Visitors click on the follow buttons to connect with your social media profiles, increasing your follower count and expanding your online community.

### Benefits

Users receive updates about new blog posts and travel deals through your social media channels, driving repeat traffic to your website.

### Add ScreenShots

![Travel](https://github.com/apu52/METAVERSE/assets/145576858/4fc507e6-0c42-4dae-90e1-1f569c21955e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@Gultreen you can start working on this

**Comment by Gultreen** [comment]
Okay thanks
