### ISSUE TITLE
[Feature Request]: daily diary 

### ISSUE THREAD

**Issue by shreya-2410** [apu52/METAVERSE#824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

it is not yet made.pls assign this to me in ssoc

### Use Case

The Metaverse Daily Diary Entry Website should provide a user-friendly, minimalist, and visually soothing interface for users to log their daily activities, thoughts, and experiences. Each diary entry should be saved in JSON format and displayed upon the user's return to the website, ensuring easy access and readability of past entries.

### Benefits

The Metaverse Daily Diary Entry Website should provide a user-friendly, minimalist, and visually soothing interface for users to log their daily activities, thoughts, and experiences

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@shreya-2410 u are assigned
