### ISSUE TITLE
[Bug]: Digital clock is not responsive

### ISSUE THREAD

**Issue by agastya3636** [apu52/METAVERSE#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Digital clock is not responsive

### Expected behavior

It should be responsive

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/124435030/346c50d5-cf56-41a3-8a67-4946030aecd8)

### On which device are you experiencing this bug?

Android, iPhone

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@agastya3636 you can start working on this
