### ISSUE TITLE
[Feature Request]: Want to Add Dog Game 

### ISSUE THREAD

**Issue by nishant0708** [apu52/METAVERSE#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A game similar to mario which main aim is to score max  points in 30s

### Use Case

it will enhance user Experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@nishant0708 adding a new game in this repo is not a valid contribution . Sorry to close this issue .
Please read the CONTRIBUTION.md file to know about all the rules of contributing.
