### ISSUE TITLE
[Feature Request]: Add MakeOver Game

### ISSUE THREAD

**Issue by abckhush** [apu52/METAVERSE#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Game Setup:
Implement the game board using HTML for structure and CSS for styling.
Use JavaScript for game logic, including sliding over various dress options.

User Interface:
Design a visually engaging and easy-to-style interface with visuals.

Game Mechanics:
1. Choose from a variety of clothing items, including tops, bottoms, dresses, and shoes.
2. Customize hairstyles and hair colors.
3. Increasing Styling Options : Every dress, hair, and skin type can be adjusted using Hue, Brightness and Intensity to add more variety.
4. Saving Styles: We can add an option to let them save the outfit they made.

### Use Case

It's a creative frontend project as it allows you as well as the user to engage with the website. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
You can start working on this @abckhush

**Comment by abckhush** [comment]
Thankyou @heysagnik . Could you pls add the level also?
