### ISSUE TITLE
[Feature Request]: Improving ui for video player

### ISSUE THREAD

**Issue by shreya-2410** [apu52/METAVERSE#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

HTML Changes:
Organized Layout: We restructured how the video player elements are arranged on the webpage. Now, everything related to the video and its controls is neatly wrapped in a box (<div class="video-wrapper">), making it easier to style and manage.
Visual Structure: We moved the controls (like play, pause buttons) inside this box, so they're closely connected to the video they control. This helps users understand where to find controls easily.
CSS Styling Updates:
Enhanced Look: We gave the video player a new appearance. The background is now darker, which makes the video stand out more. We also added rounded corners and a shadow around the video player to make it look more polished.
Modern Controls: The buttons and progress bar (the bar that shows how much of the video has played) got a makeover. The buttons look sleek and modern, and the progress bar now has a cool color change effect as the video plays.
JavaScript Functionality Improvements:
Better Play and Pause: We improved how the video starts and stops. Now, when you click play, the video plays, and the play button changes to a pause button. Clicking pause stops the video and changes the button back to play.
Smooth Control: The stop button was fixed so that when you click it, the video goes back to the beginning and stops. Before, it didn't always stop the video completely.
Updated Time Display: We made the time display (like "2:30 / 4:15") update in real-time as the video plays. It now shows you exactly where you are in the video.
Fullscreen Support: You can now click a button to make the video fill the whole screen, which is handy for watching videos without distractions.

### Use Case

Overall Impact:
These changes make the video player easier to use and nicer to look at. The layout is clearer, the buttons and progress bar are more stylish, and the video controls work smoothly. It's designed to give you a better experience when watching videos online, with everything working just as you'd expect.

### Benefits

These changes make the video player easier to use and nicer to look at. The layout is clearer, the buttons and progress bar are more stylish, and the video controls work smoothly. It's designed to give you a better experience when watching videos online, with everything working just as you'd expect.

### Add ScreenShots
before 
![image](https://github.com/apu52/METAVERSE/assets/137192044/54423d3b-c18e-4a2b-91b4-cb33b0060611)

after 
![image](https://github.com/apu52/METAVERSE/assets/137192044/9c5c434a-46a4-41b1-8210-22bd20ea3f11)
pls assign this to me i have already started working on this ..

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@shreya-2410 it's a very good issue .u are assigned.
