### ISSUE TITLE
[Bug]: Age Calculator not working

### ISSUE THREAD

**Issue by puneet426** [apu52/METAVERSE#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the age calculator does not give response

https://github.com/apu52/METAVERSE/assets/168094736/aff1f602-de40-4479-bd0c-96838846f76e

### Expected behavior

https://github.com/apu52/METAVERSE/assets/168094736/02e12e5b-5669-4b15-b637-8f4e26346bc9

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by puneet426** [comment]
hello @heysagnik please assign this issue to me

**Comment by puneet426** [comment]
i made a new ui of this calculator

**Comment by heysagnik** [comment]
Assigned you , and this issue will be valid for gssoc participation
