### ISSUE TITLE
[Feature Request]: BMI Calculator

### ISSUE THREAD

**Issue by puneet426** [apu52/METAVERSE#833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i wants to add BMI calculator on this website 

### Use Case

this feature help to calculate body fitness

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@puneet426  Adding a new project is not a valid contribution in this repo . So , I am sorry to close this PR .
But u can still make valid contributions (e.g fix bugs , add features , update documentation etc)
