### ISSUE TITLE
[Feature Request]:  KFC Clone

### ISSUE THREAD

**Issue by Damini2004** [apu52/METAVERSE#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Cloning the website

### Use Case

helps to know any structurer formatting in website

### Add ScreenShots

https://online.kfc.co.in/

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Damini2004 adding a new project is not a valid contribution in this repo . Sorry to close this issue . 
Please read all the the rules mentioned in CONTRIBUTING.md before contributing.
