### ISSUE TITLE
[Feature Request]: kubernetes for app container

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [apu52/METAVERSE#835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As the app is dockerize then i think it is also good to apply kubernetes on that container because kubernetes helps as a load balancer when more user base use the app and also help to revive the server automatic when it is down

### Use Case

it is very helpful in deploying the website and also it is helpful in scaling the website and also it automatic load balance the high amount of user

### Benefits

benefits of this feature are -
1. load balancing the website
2. always keep website alive
3. scale the website easily

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@agarwalhimanshugaya good issue . u are assigned.
