### ISSUE TITLE
@apu52  please allow me to add mini project CardFlip_Game

### ISSUE THREAD

**Issue by sudhanshu-77** [apu52/METAVERSE#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Added a mini project  CardFlip_Game

### Use Case

 CardFlip_Game is a great project for begineers to start their webdevelopment journey.

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/97780892/8800d056-8982-436d-8feb-db3ebec74046)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by sudhanshu-77** [comment]
Hi 👋 @apu52  please check my Pull Request #839 and allow me to add under gssoc24. Thankyou

**Comment by apu52** [comment]
@sudhanshu-77 Adding a new project is not a valid contribution in this repo . So , I am sorry to close this PR .
But u can still make valid contributions (e.g fix bugs , add features , update documentation etc)
