### ISSUE TITLE
[Bug]: Replace twitter with X

### ISSUE THREAD

**Issue by AkhilaSunesh** [apu52/METAVERSE#847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/apu52/METAVERSE/assets/140897461/2d889ef2-a4f1-4494-a679-833b5ef3abca)
project 9: food ordering website

### Expected behavior

.

### Add ScreenShots

.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@AkhilaSunesh u are assigned
