### ISSUE TITLE
[Feature Request]: Improve the UI of Number Guessing Game Website

### ISSUE THREAD

**Issue by Sanglap-Halder** [apu52/METAVERSE#849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to improve the UI so that it becomes more attractive

### Use Case

This change will improve its user experience with this page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@Sanglap-Halder Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Sanglap-Halder** [comment]
Thank you @anuragverma108, I will keep this in mind while working
