### ISSUE TITLE
Lyrics app not working

### ISSUE THREAD

**Issue by MetiUmashri** [apu52/METAVERSE#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The bug is that when we click get lyrics we don't fetch the lyrics. <br> kindly assign this issue to me

### Expected behavior

Probable issue is that the website is unable to fetch the lyrics as shown in the below provided screenshot.

### Add ScreenShots

<img width="959" alt="image" src="https://github.com/apu52/METAVERSE/assets/97387069/bbd193f1-53f3-4519-a766-3302017befa8">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@MetiUmashri Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
