### ISSUE TITLE
[Feature Request]: password strength checker has no files

### ISSUE THREAD

**Issue by nishant0708** [apu52/METAVERSE#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can  create this page for you 

### Use Case

it will not dissapoint user

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by nishant0708** [comment]
hey @apu52 please can you review this issue as it is valid or not . like its existing project which dont have any file i can create this project

**Comment by heysagnik** [comment]
> hey @apu52 please can you review this issue as it is valid or not . like its existing project which dont have any file i can create this project

Sorry for the delayed response 
@nishant0708  you can start working on this.
