### ISSUE TITLE
[Feature Request]: To add 2048 game

### ISSUE THREAD

**Issue by maradadivyasree020** [apu52/METAVERSE#854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To add the game 2048.
Tech Stack:HTML,CSS,JS

### Use Case

It would be a addition of new project in the games section.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@aindree-2005 according to the participation guidelines by GSSOC , you can't add new projects.  

cc @apu52
