### ISSUE TITLE
[Feature Request]: Image Generator App using JS and significant API with SEO Capabilities

### ISSUE THREAD

**Issue by codercake** [apu52/METAVERSE#855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

: A web application built using JavaScript that integrates with a significant image generation API (such as DALL-E, MidJourney, or similar). The application will allow users to input specific prompts to generate images based on AI models. Additionally, the app will have built-in SEO capabilities to optimize the generated images and their accompanying metadata for better visibility and indexing by search engines.

1. Automatic generation of SEO-friendly metadata based on user inputs.
2. Editable fields for custom metadata to improve search engine ranking.
3. Integration with social media sharing protocols (Open Graph, Twitter Cards) to ensure proper display of images and metadata on social platforms.
4. XML sitemap generation for images to help search engines index them more efficiently.

### Use Case

A content creator is building a new blog post about futuristic city designs. They need unique, AI-generated images to illustrate their concepts. Using the Image Generator App, they input prompts like "futuristic cityscape at sunset." The app generates several images based on this prompt. The creator selects the most suitable images and adds custom SEO metadata before embedding them into the blog post.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@codercake according to the participation guidelines by GSSOC , you can't add new projects.  

cc @apu52
