### ISSUE TITLE
[Feature Request]: Adding pricing and review section in travel website

### ISSUE THREAD

**Issue by Archiesachin** [apu52/METAVERSE#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add the 'Pricing' and 'review' section in the travel website. The navlinks are not working and the pricing and review section is missing. 

### Use Case

Adding the pricing section and linking the navlinks to its respective sections will make the website more complete. 

![Screenshot (1114)](https://github.com/apu52/METAVERSE/assets/103347688/cb4ef710-9144-4fec-bf7c-310af7f8ccc2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@Archiesachin you can start working on this, for any help you may reach out to me.
