### ISSUE TITLE
[Bug]: Result not found

### ISSUE THREAD

**Issue by piyansusahoo** [apu52/METAVERSE#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Result not found screen shows up even when there is nothing searched on the search bar.

### Expected behavior

Result not found should also be shown when a condition is met, that is when user searches for a particular thing and it is not available on the site.

### Add ScreenShots

https://github.com/apu52/METAVERSE/assets/130382676/a78788da-e19f-43e4-b721-68c9acf2679b

*Additional context*
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue

@OjashwiDwivedi Is also contributing to this issue so please assign her as well.

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@piyansusahoo you are ready to start 👍

**Comment by piyansusahoo** [comment]
Yes please assign @OjashwiDwivedi too we are working on this together.

**Comment by heysagnik** [comment]
> @heysagnik Yes please assign @OjashwiDwivedi too we are working on this together.

See I can assign both of you but in terms of gssoc only one who does the Pull Request gets the point, not two .

**Comment by piyansusahoo** [comment]
okay no problem,thank you for clearing it out,i will get to work.
