### ISSUE TITLE
Adding Signup/Login Functionality and Database Integration

### ISSUE THREAD

**Issue by gayatri-p786** [apu52/METAVERSE#859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement signup/login functionality, including **Google sign-up/sign-in**, and integrate a **database for user management** on the book review website. This enhancement will improve user engagement, enable personalized experiences, and lay the groundwork for future feature development.

### Use Case

- **Improved User Experience:** Users can create accounts to personalize their interactions, save favorite books, and engage in discussions.

- **Enhanced Security:** Secure authentication mechanisms ensure user data privacy and protection.

- **Advanced Features:** Enables features such as personalized recommendations, user-generated content (reviews, comments), and notifications.

- **Scalability:** A database will support the storage and retrieval of user data efficiently as the platform grows.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@gayatri-p786 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by gayatri-p786** [comment]
@anuragverma108 Thank you. Will follow your suggestions and get started on this.
