### ISSUE TITLE
Improve the poster of  METAVERSE Project

### ISSUE THREAD

**Issue by Suraj-kumar00** [apu52/METAVERSE#86]
**Describe the bug**

In the README description of Metaverse, the poster is not of high quality and much attractive and I can create a more attractive poster for this.

**Expected behavior**

New and better poster of Metaverse.

**Screenshots**

Will be available when I'll start working on it after assigning of this issue

**Additional context (Mandatory )**
 
- [x] I am a contributor in OSEN open source programme

 
- [x] I am a contributor in HACTOBERFEST 2023

Can I work on this issue?

**Comment by apu52** [comment]
@Suraj-kumar00 Welcome to Metaverse!!!!!!
Please follow the rules mentioned in contributing.md file

**Comment by Suraj-kumar00** [comment]
Hello @apu52, How are you doing?
I have created a pull request, please review it and merge!
