### ISSUE TITLE
[Feature Request]: Add title and icon

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add the title and icon to the anime list project.

### Use Case

This makes completes the anime list project

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/131477601/46765af1-ab18-498a-bba7-16686ce4fcc2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@chaanakyaaM all set to start .

**Comment by chaanakyaaM** [comment]
kindly review the PR.
