### ISSUE TITLE
[Feature Request]: DEEPFAKE DETECTION OF VIDEO USING TRAINED NEURAL NETWORK WEB APP

### ISSUE THREAD

**Issue by AbheetHacker4278** [apu52/METAVERSE#861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### DeepFake Detection using Res-Next50 model which is been trained using various
datasets like , Celeb-Df Dataset , FaceForensics++ Dataset , Challenge Dataset , which can do
Sequential analyse of the video by dividing the video into 20 parts and analyse those parts on
the basis of face tone , color , replaced face structrure(nose , eyes , mouth).

### Use Case

Easily can Used for various type of videos for detect by comparing the pretrained 6000+ videos

### Benefits

Can Easily Tell Which Video is FAKE or REAL

@apu52 Please Assign this Issue to Me under GSSOC24

### Add ScreenShots

![Screenshot 2024-06-26 114256](https://github.com/apu52/METAVERSE/assets/114290748/b9413d77-65c2-4ac8-b064-e4a9d180d890)

![image](https://github.com/apu52/METAVERSE/assets/114290748/2b62a4fe-783f-47c4-b058-dfc74c5445f8)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@AbheetHacker4278 sorry, we are not accepting any new projects. 


cc: @apu52
