### ISSUE TITLE
[Bug]:  Improve the UI of contacts page

### ISSUE THREAD

**Issue by AkhilaSunesh** [apu52/METAVERSE#862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Add hover cards to make the website aesthetic
location: https://apu52.github.io/METAVERSE/contact.html

### Expected behavior

.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@AkhilaSunesh assigned you, you can start working on this.

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue under GSSoc extended label.
