### ISSUE TITLE
[Bug]:  Logo directing to home page not working in LYRIC FINDER

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#864]
Hello @anuragverma108 @apu52 @heysagnik 
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The logo Hard Rock navigator doesnt seems to be working.

### Expected behavior

Once we search for the song if we have to go to home page, logo doesnt take back.

### Add ScreenShots

![Screenshot 2024-06-23 021939](https://github.com/apu52/METAVERSE/assets/129287425/b21574fe-e634-4cca-aaa4-88225738f5d5)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by sakshiglaze** [comment]
hello @apu52  @anuragverma108 @heysagnik 
Please assign this issue under gssoc and kindly add the necessary difficulty label>
ThankYou!

**Comment by heysagnik** [comment]
hey @sakshiglaze you may start working, looking for your contributions. For any help you may reach out to me
