### ISSUE TITLE
[Bug]: The project CODEFORCES_API not opening

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello @anuragverma108  @apu52 
when we click on the page the page goes 404. IT seems the project lacks .HTML FILE.

### Expected behavior

It is always better to something then nothing. Since one can not new create html file(dont know the context).
I recommend to have a completely new project!! RPS GAME--

Computer Opponent: Develop an opponent that can make intelligent choices, providing a challenging gameplay experience for the human player.
Autoplay Mode: Include an autoplay mode where the computer player competes against itself.
Real-time Scoring: Keep track of the scores for both the human player and the computer opponent in real-time. Display the scores prominently on the game interface to provide a sense of competition and progress.
Implementing persistent scoring in a rock-paper-scissors game, ensuring scores are not lost even after page reloads unless and until player resets the score.

### Add ScreenShots

![Screenshot 2024-06-26 144659](https://github.com/apu52/METAVERSE/assets/129287425/d3d9b9f0-924e-4470-8e47-7f5056df603f)
![Screenshot 2024-06-26 144719](https://github.com/apu52/METAVERSE/assets/129287425/e2801d99-a1e6-43da-b4ed-106f41671314)
![Screenshot 2024-05-15 155019](https://github.com/apu52/METAVERSE/assets/129287425/96ccc119-3f2c-4c6e-b522-9b672d02dbae)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@sakshiglaze under which event are you participating?

**Comment by sakshiglaze** [comment]
@heysagnik I am participating in both. But if there is something you can mark only one please mark it under gssoc.

**Comment by heysagnik** [comment]
@sakshiglaze assigned you
