### ISSUE TITLE
[Feature Request]: About Section Not Working on Myntra Clone

### ISSUE THREAD

**Issue by payalsinha12** [apu52/METAVERSE#866]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

The "About" section on the Myntra clone is not functioning as expected. Users are unable to view the information intended to be displayed in this section.

### Use Case

 Improves User Experience:
Provides Context: The "About" section can give users an overview of the project, explaining its purpose, goals, and the motivation behind its creation. This helps users understand what the application is for and how it can be useful to them.
Builds Trust: By including information about the developers, the technologies used, and the project's objectives, users can feel more confident in using the application. It adds a layer of transparency and credibility.
Guides Users: It can include instructions or guides on how to navigate the site, what features are available, and how to make the most of them. This is especially useful for first-time visitors.
2. Facilitates Developer Collaboration:
Onboarding New Contributors: For open-source projects, the "About" section can serve as an initial point of reference for new contributors. It can provide information about the project's structure, key features, and how to get involved.
Documentation: Including technical details about the stack, architecture, and development guidelines helps maintain consistency and quality across contributions. It can also include links to more detailed documentation or contribution guidelines.
3. Enhances Project Presentation:
Professionalism: A well-crafted "About" section demonstrates attention to detail and professionalism. It shows that the project is well-thought-out and maintained, which can attract more users and contributors.
Marketing: For projects aiming to gain traction, the "About" section can act as a marketing tool. It can highlight unique features, showcase testimonials or success stories, and provide a narrative that resonates with the target audience.

### Benefits

Benefits to the Project
Increased Usability:

User Guidance: Provides new users with essential information about the project's purpose, features, and navigation. This makes the application more user-friendly and accessible.
Enhanced User Experience: By clearly explaining what the application does and how to use it, users are more likely to have a positive experience, leading to higher user satisfaction and retention.
Professionalism and Credibility:

Transparency: Showcasing the development team, technologies used, and the project's goals adds a layer of transparency, making the project appear more professional and credible.
Trust Building: Users are more likely to trust an application that openly shares its mission, background, and the people behind it.
Effective Communication:

Clear Messaging: An "About" section helps convey the project's mission and vision clearly, ensuring that users and potential contributors understand the project's goals and objectives.
Attracting Contributions:

Onboarding New Contributors: For open-source projects, a detailed "About" section can help attract and onboard new contributors by providing them with a clear understanding of the project.
Documentation Hub: Serves as an initial reference point for developers, making it easier to understand the project's structure, coding standards, and contribution guidelines.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by payalsinha12** [comment]
@apu52 please assign me the issue

**Comment by payalsinha12** [comment]
@sanjay-kv please assign me

**Comment by anuragverma108** [comment]
@payalsinha12 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
