### ISSUE TITLE
[Feature Request]: 22. Quiz App , we can go to the next question by "enter " key in keyboard instead of always using Next button

### ISSUE THREAD

**Issue by jeevan10017** [apu52/METAVERSE#867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 22. Quiz App: we can go to the next question by using the "enter " key on the keyboard instead of always using the always Next button.

### Use Case

Use the keys on the keyboard instead of the Next button to go for the next question.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@jeevan10017 u are assigned
