### ISSUE TITLE
[Bug]: Shruti and Ankita image not showwing

### ISSUE THREAD

**Issue by UtkarshBirla28** [apu52/METAVERSE#868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Cannot see Shruti and Ankita images in contactus page

### Expected behavior

![Screenshot (106)](https://github.com/apu52/METAVERSE/assets/96072228/ba8a4b6f-5ed9-4c42-b1d5-80054f4fe870)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@UtkarshBirla28 under which are you participating?

**Comment by UtkarshBirla28** [comment]
> @UtkarshBirla28 under which are you participating? GSSOC or SSOC

@heysagnik GSOC

**Comment by apu52** [comment]
@UtkarshBirla28 u are assigned

**Comment by UtkarshBirla28** [comment]
@apu52 no level??
