### ISSUE TITLE
added hovering effect on contact page on images of owners

### ISSUE THREAD

**Issue by Krishna100604** [apu52/METAVERSE#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

added hover effect on the owners 

### Use Case

in homepage every contributor has that hovering effect so maintain consistency in website i added it

### Benefits

it looks better

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/110299021/85b550e5-cad5-4354-9704-4b93888bd7c3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Krishna100604** [comment]
@apu52  assign me this

**Comment by anuragverma108** [comment]
@Krishna100604 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by ssyy21** [comment]
@anuragverma108 please assign me this task under IEEE open source week.

**Comment by apu52** [comment]
@ssyy21 i have assigned u , u can start working , please try to submit your PR within 11.30 pm otherwise i can't be able to review the PR & merge it
