### ISSUE TITLE
add responsiveness for all screens

### ISSUE THREAD

**Issue by Krishna100604** [apu52/METAVERSE#872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

added responsive using media query

### Use Case

user can use it in mobile as well

### Benefits

can be used in mobiles as well

### Add ScreenShots

![Screenshot (162)](https://github.com/apu52/METAVERSE/assets/110299021/31f15d1d-300c-46d7-8013-cc4c81c2ea2e)
![Screenshot (161)](https://github.com/apu52/METAVERSE/assets/110299021/791ad10c-a96d-4ed4-a486-32522c22636c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Krishna100604** [comment]
@apu52  assign me this

**Comment by anuragverma108** [comment]
@Krishna100604 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by Krishna100604** [comment]
@anuragverma108 i guess i have to fork it again because while PR i am not able to merge cause i worked on old repo so i will fork it again and make changes
