### ISSUE TITLE
Restaurant_Website

### ISSUE THREAD

**Issue by Jatingupta9120** [apu52/METAVERSE#88]
**Describe the project you want to add with tech stack**

The restaurant website project is a full-stack web application that allows users to search for restaurants, view menus, and make reservations. The front end of the application is built using React, a popular JavaScript library for building user interfaces. The back end of the application is built using Node.js, a popular JavaScript runtime environment. The application uses a PostgreSQL database to store data about restaurants, menus, and reservations.

**Expected behavior**

Tech Stack:
Front-end: React, JavaScript, HTML, CSS
**Screenshots (optional)**

Tech Stack:
Front-end: React, JavaScript, HTML, CSS
![image](https://github.com/apu52/METAVERSE/assets/114533828/82a78c02-5bea-4b57-a3e6-84c0af6603a7)
![image](https://github.com/apu52/METAVERSE/assets/114533828/d780fe5a-ff9a-4b01-9eec-fa9e8d8afef0)

**Additional context (Mandatory )**
 
- [ ] I am a contributor in OSEN open source programme

 
- [X] I am a contributor in HACTOBERFEST 2023

**Comment by Suraj-kumar00** [comment]
Hi @apu52, I want to work on this issue as I created this.

**Comment by apu52** [comment]
> Hi @apu52, I want to work on this issue as I created this.

@Suraj-kumar00 Okay ! Please try to make another new Issue.
