### ISSUE TITLE
[Feature Request]: Want to Update Ui of Meme-Generator

### ISSUE THREAD

**Issue by nishant0708** [apu52/METAVERSE#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to Update Ui of Meme-Generator

### Use Case

it will enhance user experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@nishant0708 u are assigned .but can u provide here some updates about the UI??
