### ISSUE TITLE
[Feature Request]: Add reddit ui clone

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 i would like to add reddit UI clone.

### Use Case

This projects helps the uses to understand how to make reddit ui clone.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@chaanakyaaM adding a new project is not a valid contribution in this repo . sorry to close this issue . Please read the rules mentioned in CONTRIBUTING.md before contributing.
