### ISSUE TITLE
[Feature Request]: add icon and title

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The hms project is awesome but it would be even better if appropriate icon and title are added.

### Use Case

This helps improve the overall website look.

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/131477601/47482656-db08-46db-bd29-e889515f1922)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@chaanakyaaM u are assigned.
