### ISSUE TITLE
[Feature Request]: HOVER EFFECT ON THE BOOK TABS

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello @apu52 @anuragverma108 @heysagnik 
Hover effect makes the website user responsive. And even looks better.

### Use Case

tab will have a zoom effect as the user hover on it.

### Benefits

Enhancement of user experience.

### Add ScreenShots

![Screenshot 2024-06-26 150331](https://github.com/apu52/METAVERSE/assets/129287425/69f58ad8-b9a8-4e5e-9eb9-ee6465527423)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by sakshiglaze** [comment]
Hello @anuragverma108 @apu52 @heysagnik 
Please assign this under gssoc and the difficulty level too.

**Comment by sakshiglaze** [comment]
Hello @apu52  @anuragverma108  @heysagnik 
Please assign!!

**Comment by apu52** [comment]
@sakshiglaze u are assigned

**Comment by Subashree-selvaraj** [comment]
can you assign this issue to me?

**Comment by apu52** [comment]
> can you assign this issue to me?

yess , u are assigned ,
Just want to ask you under which open source programme u want to contribute ??
Like under WOB or GSSOC ext. or hactoberfest?

**Comment by Subashree-selvaraj** [comment]
> > can you assign this issue to me?
> 
> yess , u are assigned , Just want to ask you under which open source programme u want to contribute ?? Like under WOB or GSSOC ext. or hactoberfest?

GSSOC ext

**Comment by Subashree-selvaraj** [comment]
> > > can you assign this issue to me?
> > 
> > 
> > yess , u are assigned , Just want to ask you under which open source programme u want to contribute ?? Like under WOB or GSSOC ext. or hactoberfest?
> 
>Under  GSSOC ext sir

**Comment by apu52** [comment]
> > > can you assign this issue to me?
> > 
> > 
> > yess , u are assigned , Just want to ask you under which open source programme u want to contribute ?? Like under WOB or GSSOC ext. or hactoberfest?
> 
> GSSOC ext

u can start working

**Comment by Subashree-selvaraj** [comment]
Ok sure sir!

**Comment by ssyy21** [comment]
@apu52 please assign me this issue under IEEE open source week.

**Comment by apu52** [comment]
@ssyy21 i have assigned u , u can start working , please try to submit your PR within 11.30 pm otherwise i can't be able to review the PR & merge it
