### ISSUE TITLE
[Bug]: Image display error

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello @apu52 @anuragverma108  @heysagnik 
website lacks some image display

### Expected behavior

Image should be visible for a good website.

### Add ScreenShots

![Screenshot 2024-06-29 214222](https://github.com/apu52/METAVERSE/assets/129287425/248c1eeb-83e6-4141-8903-74d18adebe06)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
Participating on behalf of Gssoc or Ssoc

**Comment by sakshiglaze** [comment]
> Participating on behalf of Gssoc or Ssoc

Gssoc

**Comment by sakshiglaze** [comment]
Hello @anuragverma108 @apu52 @heysagnik 
Please assign this under gssoc and the difficulty level too.

**Comment by sakshiglaze** [comment]
> Participating on behalf of Gssoc or Ssoc

Hello @heysagnik  @apu52  @anuragverma108 
Please assign under gssoc

**Comment by apu52** [comment]
@sakshiglaze u are assigned.

**Comment by apu52** [comment]
@sakshiglaze just want to inform u that I can already see that u are already raising a lot of issues in this issues. But want to inform u one thing that According to the rules of this repo u can't raise more than 2 issues at a time . So please hold some patience & only after successful completion of the previous PR , raise new issues
