### ISSUE TITLE
[Feature Request]: JPG to PNG and PNG to JPG Image Converter

### ISSUE THREAD

**Issue by nikki-05** [apu52/METAVERSE#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The main feature of this project is the ability to convert JPG images to PNG format and vice versa. Users can upload a JPG image and convert it to PNG or upload a PNG image and convert it to JPG. The interface includes file inputs for uploading images, buttons to trigger the conversion, a preview section to display the converted image, and a download link to save the converted image.

### Use Case

This project allows developers to learn and practice JavaScript by building a functional web-based image converter If any developer, photographer or naive user needs to convert the formats, they can use this application.

### Benefits

It is convenient, simple, and easy to use.
Its seamless and quick nature makes it more versatile

### Add ScreenShots

![Screenshot 2024-06-29 230002](https://github.com/apu52/METAVERSE/assets/109809432/70c55e66-1b28-4209-b3e5-9d8337602449)
A sample for the feature 
I will enhance it more according to the needs

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@nikki-05 adding a new project in this repo is not a valid contribution. Sorry to close this issue . Please read all the rules mentioned in CONTRIBUTING.md file before contributing.
