### ISSUE TITLE
[Bug]: Responsiveness not appropriate

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello @apu52 @anuragverma108 @heysagnik 
Flex doesn't appear to be working properly.
Please assign issue under gssoc and difficulty level.

### Expected behavior

on small devices no of div should be less according to respective screen sizes.

### Add ScreenShots

![Screenshot 2024-06-29 232615](https://github.com/apu52/METAVERSE/assets/129287425/5e0bee36-72dd-4049-b5c1-d42a9eba7247)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@sakshiglaze You want to contribute it under GSSOC or SSOC ?

**Comment by sakshiglaze** [comment]
> @sakshiglaze You want to contribute it under GSSOC or SSOC ?

GSSOC

**Comment by sakshiglaze** [comment]
Hello @anuragverma108 @apu52 
Please assign this under gssoc and the difficulty level too.
