### ISSUE TITLE
[Bug]: tiktok_project 404

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello @apu52 @anuragverma108 @heysagnik 
file not found.
Please assign issue under gssoc and difficulty level.

### Expected behavior

try to get the file. Try tweaking JS code.

### Add ScreenShots

![Screenshot 2024-06-30 001303](https://github.com/apu52/METAVERSE/assets/129287425/2dbb1a7e-d768-4575-9c6d-bc79123e5567)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@sakshiglaze You want to contribute under GSSOC or SSOC ?

**Comment by sakshiglaze** [comment]
> @sakshiglaze You want to contribute under GSSOC or SSOC ?

Gssoc

**Comment by sakshiglaze** [comment]
Hello @anuragverma108 @apu52 
Please assign this under gssoc and the difficulty level too.
