### ISSUE TITLE
[Feature Request]: Improvise the custom cursor

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The existing custom cursor is good but it can be awesome by improvising the custom cursor.

### Use Case

cursor is the most interactive part of the website, this helps users enjoy the process of surfing through your website.

### Add ScreenShots

i would improvise the custom cursor like this:

https://github.com/apu52/METAVERSE/assets/131477601/04f785e5-b256-41da-a396-68628fd71bc2

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@chaanakyaaM Actually I genuinely like The existing Cursor which also matches with the UI of the website .I genuinely don't want to change it . So I am sorry to close this issue.
