### ISSUE TITLE
[UI Enhancement]: Adding a hover effect to the show cards on Hulu Clone Website

### ISSUE THREAD

**Issue by meetalik8** [apu52/METAVERSE#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the Hulu Clone Project is very static, not a lot of things for a user to interact with.

### Use Case

By adding a scaling effect on hover to the show cards, it would improve the User's Experience on the website, and also improve the UI of the website.

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/102135323/e065ba38-7e5f-460b-aefc-63ac69b57705)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by mryashsinghal** [comment]
I want to work on this issue. Assign this task to me under SSOC'24.

**Comment by meetalik8** [comment]
As I raised the issue, I would like to work on it!
