### ISSUE TITLE
[Bug]: Text to Voice Converter is not responsive

### ISSUE THREAD

**Issue by jeevan10017** [apu52/METAVERSE#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It is not responsive for smaller screens.

### Expected behavior

Text input space, button, and background overflow when the screen gets smaller.

### Add ScreenShots

![Screenshot 2024-07-01 000633](https://github.com/apu52/METAVERSE/assets/132948936/aab68726-73f2-4849-859e-5b47722f56fc)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
Hello @anuragverma108 @apu52 @heysagnik
Please assign this under ssoc and the difficulty level, too.

**Comment by apu52** [comment]
@jeevan10017 u are assigned.
