### ISSUE TITLE
[Documentation Update]: Add new frotnen project, Iphone 14 pro clone

### ISSUE THREAD

**Issue by vansh-codes** [apu52/METAVERSE#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Clone of iPhone 14 pro website 

### Suggested Change

Adding frontend project

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by vansh-codes** [comment]
@heysagnik Hi, Why is this issue invalid?? Can you please let me know?

**Comment by heysagnik** [comment]
> @heysagnik Hi, Why is this issue invalid?? Can you please let me know?

Adding new projects are against the guidelines of this Repository
