### ISSUE TITLE
[Feature Request]: Update the UI of CyberWise Website

### ISSUE THREAD

**Issue by why-aditi** [apu52/METAVERSE#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add images and fix the layout, so that it looks good as well as informative

### Use Case

Increases user interaction

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@why-aditi u are assigned
