### ISSUE TITLE
[Feature Request]:  SOCIAL MEDIA QUICK ACCESS EXTENSION

### ISSUE THREAD

**Issue by Khushi-Pushkar** [apu52/METAVERSE#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi @apu52 . I'm GSSoC'24 Contributor
i want to add Social Media Quick Access Extension 

A Social Media Quick Access Extension is a browser add-on that provides users with fast and easy access to their favorite social media platforms. 

### Use Case

Quick Navigation

### Benefits

Saves time by eliminating the need to open separate apps or tabs for each social media platform.

Reduces the time spent navigating between different social media platforms, allowing users to focus on other tasks.

Provides quick access to essential social media functions, helping users stay organized and efficient.

Simplifies the process of staying connected and engaged with social networks

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/142687709/ed50f876-9246-4e20-a8f7-7afc97db6bc0)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Khushi-Pushkar adding a new project in the repo is not a valid contribution. Please read the rules mentioned in CONTRIBUTING.md before contributing. Sorry to close this issue .but u can still make new other issues on which u want to work
