### ISSUE TITLE
[Feature Request]: Video to Audio

### ISSUE THREAD

**Issue by Khushi-Pushkar** [apu52/METAVERSE#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Video to audio conversion involves extracting the audio track from a video file.

### Use Case

.

### Benefits

Audio files are more portable and can be listened to while performing other tasks, providing flexibility for multitasking.

Audio files are typically smaller in size compared to video files, resulting in lower data usage and faster downloads or streaming

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Khushi-Pushkar adding a new project in the repo is not a valid contribution. Please read the rules mentioned in CONTRIBUTING.md before contributing. Sorry to close this issue .but u can still make new other issues on which u want to work
