### ISSUE TITLE
[Feature Request]: Email Validator

### ISSUE THREAD

**Issue by Khushi-Pushkar** [apu52/METAVERSE#907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

An email validator is a tool or function designed to verify the correctness and validity of an email address.

### Use Case

- Validating email addresses used for password recovery and other account management functions.
-  Ensuring that users provide valid email addresses during sign-up helps maintain data quality and enables reliable communication.

### Benefits

- Ensures that only correctly formatted email addresses are stored in databases.
- Reduces the incidence of invalid or fake email addresses.
- Provides immediate feedback to users entering incorrect email addresses.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Khushi-Pushkar adding a new project in the repo is not a valid contribution. Please read the rules mentioned in CONTRIBUTING.md before contributing. Sorry to close this issue .but u can still make new other issues on which u want to work
