### ISSUE TITLE
[Feature Request]: Hover effect of social icon and width of footer in home page

### ISSUE THREAD

**Issue by Maana-Ajmera** [apu52/METAVERSE#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- I want to add hover effect on social icons in footer , on hovering they will change to their respective logo colors and will scale up
- Also , I want to fix the width of footer on home page , it doesnt cover full width and hence doesnt look good , also their are no social icons in footer of home page , I want to add them like they are in about us section

### Use Case

It will help to improve UI of project

### Benefits

It will help in making the project look more good and appealing

### Add ScreenShots

Before :
![image](https://github.com/apu52/METAVERSE/assets/162733812/ccb111b6-5dcb-4ba9-a407-e8d11aa4fd78)

After:

https://github.com/apu52/METAVERSE/assets/162733812/970c7046-f0db-4b31-b0ca-34085190f61b

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
Hey you may start working on this
