### ISSUE TITLE
[Feature Request]: add icon and change title 

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The amazon clone is nice but there is no icon for the website, i would like to add it and change the title from 'Amazom' to 'Online shopping site in India' as it is the landing page of the website.

### Use Case

This makes the website UI look professional .

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/131477601/2c56def4-b96e-43d7-afc8-cc27604a91cc)

![image](https://github.com/apu52/METAVERSE/assets/131477601/345733af-708d-46f6-94a8-78b6ded8a170)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@chaanakyaaM u are assigned

**Comment by chaanakyaaM** [comment]
Kindly review the PR.
