### ISSUE TITLE
[Feature Request]:  Login/register page as asked in README

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello @apu52  @anuragverma108  @heysagnik 

Addition of login and register page using html css js node.js and postgreSQL.
It was asked in readme file of Health tracker project!

### Use Case

Customer Privacy increases. 

### Benefits

Not everyone will able to open someone's personal info.

### Add ScreenShots

![Screenshot 2024-07-05 045604](https://github.com/apu52/METAVERSE/assets/129287425/384e2c67-381f-4584-b8c7-538353e4bcb8)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@sakshiglaze u are assigned
