### ISSUE TITLE
[Bug]: Contact not directing to page section 

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello @apu52 @anuragverma108  @heysagnik 
Once you click the contact on navbar it should direct to particular section of page.

### Expected behavior

using Query selectors in JavaScript onscroll it should direct to particular section.
for user convenience
### Add ScreenShots

![Screenshot 2024-07-05 051442](https://github.com/apu52/METAVERSE/assets/129287425/3fabd1ee-d214-4d5d-8c78-31fd4325f4d6)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@sakshiglaze u are already assigned with 3 issues already , please don't raise more than 2 issues at a time . Please follow the rules mentioned in CONTRIBUTING.md file .I am closing your Some of the ISSUES & tagging some with "PENDING" .After completing the previously assigned issues , ping me there , I will assign u those issues
