### ISSUE TITLE
[Bug]: API call not working in weather app

### ISSUE THREAD

**Issue by sakshiglaze** [apu52/METAVERSE#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello @apu52 @anuragverma108 @heysagnik 
It shows undefined details.
API call not working

### Expected behavior

Need to call an api to fetch the details of asked city.

### Add ScreenShots

![Screenshot 2024-07-05 053157](https://github.com/apu52/METAVERSE/assets/129287425/97745ba6-f4ee-452d-93e5-7f42e90c7a6f)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ayesha-firdaus** [comment]
would like to work on this issue. please assign me

**Comment by apu52** [comment]
@ayesha-firdaus u are assigned
