### ISSUE TITLE
[Bug]: Recipe is not getting fetched in Recipe App

### ISSUE THREAD

**Issue by Archiesachin** [apu52/METAVERSE#922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Recipe is not getting fetched in Recipe App. When searched for any recipe it is giving error in console. 

### Expected behavior

We should add cards for few recipes on the frontend itself and there should be a feature to search for the recipes. 

### Add ScreenShots

![Screenshot (1158)](https://github.com/apu52/METAVERSE/assets/103347688/d272cc29-83f2-4927-b3e3-127d012e99cb)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Archiesachin u are assigned
