### ISSUE TITLE
[Feature Request]: Adding Random Color Generator

### ISSUE THREAD

**Issue by GAVINESHWAR** [apu52/METAVERSE#928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

random color generator is an project developed using HTML,CSS and JavaScript , It will  changes the background color randomly while clicking on the button and displays the value hexadecimal color code.

### Use Case

This is will added to the projects to change the background randomly

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/124431955/459bdb55-5254-425d-b5bc-40c1062e4c97)

@apu52 , assign me this issue to make contribution to the project.

Thank you

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@GAVINESHWAR webare not accepting new projects
