### ISSUE TITLE
[Feature Request]: Adding Image Search Engine Project

### ISSUE THREAD

**Issue by GAVINESHWAR** [apu52/METAVERSE#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Image Search Engine is an website developed using the HTML, CSS , JavaScript and Apis. It will display the images with description as search in the search bar. Multiple images with description will be displayed below have the show less and show more options.

### Use Case

The website will provide the images with description to  various topics .

### Add ScreenShots

![Screenshot 2024-06-24 110939](https://github.com/apu52/METAVERSE/assets/124431955/b46387da-5cee-4853-b7e5-84b9e4c7e03a)

![Screenshot 2024-06-24 110513](https://github.com/apu52/METAVERSE/assets/124431955/644a8e6d-d67d-4ea0-873a-03d5f2da45a6)

@apu52 , assign me this issue to make contribution to the project..

Thank you

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@GAVINESHWAR we are not accepting new projects
