### ISSUE TITLE
[Feature Request]: Add back to top button on the travel website

### ISSUE THREAD

**Issue by Sanglap-Halder** [apu52/METAVERSE#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a back to top button on the travel website.

### Use Case

By adding this feature it will be easy to come back to the top of the website easily by just one click. 

### Benefits

No need for extra scrolling

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Sanglap-Halder** [comment]
Please review this issue

**Comment by anuragverma108** [comment]
@Sanglap-Halder Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!
