### ISSUE TITLE
Adding Styles and hovering effect and animations to the Tindog Website

### ISSUE THREAD

**Issue by SuhainaFathimaM** [apu52/METAVERSE#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer and the body can be added with more styles..

### Expected behavior

Adding more styles and animations

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/153417476/9838efa3-7671-49f5-96d0-ef17b77bc520)

![image](https://github.com/apu52/METAVERSE/assets/153417476/434d5f5b-c120-46ec-b41d-20c3ec72b235)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
hey @SuhainaFathimaM , you may start working on this
