### ISSUE TITLE
[Bug]: Dark and light mode alignment issue

### ISSUE THREAD

**Issue by ChiragShukla222** [apu52/METAVERSE#941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the dark mode button is making the alignment of the site unstable and it's positioning is not good to
please assign the issue to me I can fix that

### Expected behavior

it should be aligned with in the nav bar and should not exceed x axis

### Add ScreenShots

![Screenshot (196)](https://github.com/apu52/METAVERSE/assets/119029971/c3a11c6b-aac2-48e1-b464-2cbe2474025e)
![Screenshot (197)](https://github.com/apu52/METAVERSE/assets/119029971/2e3d09ad-6658-4d2f-9dbe-32b87409778c)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ChiragShukla222** [comment]
@apu52 ?

**Comment by heysagnik** [comment]
Hey @ChiragShukla222 you can start working on this

**Comment by ChiragShukla222** [comment]
yes

**Comment by Praneetha-4** [comment]
can you please assign me the issue!

**Comment by apu52** [comment]
> can you please assign me the issue!

yess , u are assigned ,
Just want to ask you under which open source programme u want to contribute ??
Like under WOB or GSSOC ext. or hactoberfest?

**Comment by praneethaBrindavanam** [comment]
GSSOC ext.
