### ISSUE TITLE
[Feature Request]:  Want to create a seperate dynamic contributor page with No. of contributions 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [apu52/METAVERSE#942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to create a seperate contributions page where user can see the number of contributions , his name done by the person .
I will make it with the same theme 

### Use Case

![image](https://github.com/apu52/METAVERSE/assets/118350936/2561ae31-4d15-4cec-94a0-598d6306ecc4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@apu52 is this necessary?

**Comment by apu52** [comment]
> @apu52 is this necessary?

u can assign him .I want to see the new contributor page assigned by him.

**Comment by apu52** [comment]
@Ayushmaanagarwal1211 I want to suggest you to make a complete new page on this in the website without making any changes in the already existing pages . & try to make the page according to the theme of the website

**Comment by Ayushmaanagarwal1211** [comment]
> @Ayushmaanagarwal1211 I want to suggest you to make a complete new page on this in the website without making any changes in the already existing pages . & try to make the page according to the theme of the website

Yeah sure i will create a seperate page for that

**Comment by Ayushmaanagarwal1211** [comment]
@apu52  and @heysagnik  Should i start working on that

**Comment by apu52** [comment]
> @apu52 and @heysagnik Should i start working on that

yes.u can start .I am assigning u
