### ISSUE TITLE
[Feature Request]: Add icon and hover effect

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add the icon and hover effects to the footer links.

### Use Case

As this project is in the front page, everyone views it, so it needs to be perfect.

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/131477601/9f9e8648-4ab3-4eb8-aee2-ba1efd92bcc6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@chaanakyaaM you can start working on this ?
