### ISSUE TITLE
[Bug]: HOTSAR CLONE APP Lands on 404 Error Page

### ISSUE THREAD

**Issue by agrawal-yash** [apu52/METAVERSE#946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicking on the project that is live on Github Pages, the index.html file is not found, and thus it throws a 404 error message. 

### Expected behavior

Github pages should find the correct index.html file and display it.

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/139786074/481b08a4-b9ab-4548-aa62-f6a0a35de90c)

### On which device are you experiencing this bug?

Android, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@agrawal-yash you can start working on this
