### ISSUE TITLE
[Feature Request]: Enhancement of the netflix footer

### ISSUE THREAD

**Issue by jayanththalla** [apu52/METAVERSE#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the footer of the Netflix, there is no proper alignment and description 

### Use Case

The footer is not the same as the official footer so we have to change the footer

### Add ScreenShots

please assign me @pa

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@jayanththalla , you are ready to start ?

**Comment by jayanththalla** [comment]
> @jayanththalla , you are ready to start ?

yes if u assign me i can start

**Comment by heysagnik** [comment]
> > @jayanththalla , you are ready to start ?
> 
> yes if u assign me i can start

Sorry my mistake

**Comment by jayanththalla** [comment]
![image](https://github.com/apu52/METAVERSE/assets/121346142/17b1ef94-8abc-4554-ac6b-b9dcb779ff5d)
When I run on my  localhost the netflix is different from deployment page 
How can i fix ?
Can i fix total project or other?

**Comment by apu52** [comment]
> ![image](https://private-user-images.githubusercontent.com/121346142/347844018-17b1ef94-8abc-4554-ac6b-b9dcb779ff5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzUyNTksIm5iZiI6MTcyMDg3NDk1OSwicGF0aCI6Ii8xMjEzNDYxNDIvMzQ3ODQ0MDE4LTE3YjFlZjk0LThhYmMtNDU1NC1hYzZiLWI5ZGNiNzc5ZmY1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxMjQ5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWRiZDRhMjQ3N2M5NWI2ZWYzY2JjZmEwZDI0NzIwZWJiMmY2NDg0ZTYyMTUzZmU2YWU4Y2U0NTQ5NWZkMTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TI1ayJ3z5dhjScqptGap07f17rPIZXEP_17lg7676qU) When I run on my localhost the netflix is different from deployment page How can i fix ? Can i fix total project or other?

ok I see. u can fix the total project
