### ISSUE TITLE
Netflix Front Page Project

### ISSUE THREAD

**Issue by Geeks-Arpan** [apu52/METAVERSE#95]
Project Name: Netflix Front Page Clone

Tech Tools: Html,Css and Js

**Description**
Netflix is a subscription-based streaming service that allows our members to watch TV shows and movies on an internet-connected device.

**Screenshots (optional)**
![Screenshot 2023-10-30 060943](https://github.com/apu52/METAVERSE/assets/99377659/211698b8-dcc7-44ec-96a3-ead5883d1733)

**Additional context (Mandatory )**
- [x] I am a contributor in OSEN open source programme 
- [x] I am a contributor in HACKTOBERFEST 2023

**Comment by devharsh007** [comment]
If u need a Netflix homage clone  only , I can do that ! 
if u need anything else do tell me.

**Comment by apu52** [comment]
@Geeks-Arpan The project is already present in this repo 
Please try to attach a new project or you can enhance /add features in the already present project

**Comment by apu52** [comment]
> If u need a Netflix homage clone only , I can do that ! if u need anything else do tell me. @Geeks-Arpan

@devharsh007 if u want to contribute in this repo please raise a new issue
