### ISSUE TITLE
[Documentation Update]: I want to add Privacy notice and copyright policy pages

### ISSUE THREAD

**Issue by Maana-Ajmera** [apu52/METAVERSE#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

There is no privacy notice and copyright policy in the website.

### Suggested Change

- We can add privacy notice and copyright policy in the website 

- I will design the pages keeping in mind the theme of the project

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Maana-Ajmera** [comment]
@apu52 @anuragverma108 @heysagnik I want to work on this, please assign it to me

**Comment by heysagnik** [comment]
@Maana-Ajmera you are good to start

**Comment by Maana-Ajmera** [comment]
@heysagnik Working on it !
