### ISSUE TITLE
[Bug]: Temperature Converter is not working  App.30

### ISSUE THREAD

**Issue by jeevan10017** [apu52/METAVERSE#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Total Logic is incorrect in Temperature converterthe converter

### Expected behavior

In Fahrenheit to Celcius Converter, none of the expected results matched.

### Add ScreenShots

![Screenshot 2024-07-09 232628](https://github.com/apu52/METAVERSE/assets/132948936/14dec2d1-0ecc-4c54-be7b-45ea427e586e)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by anuragverma108** [comment]
@jeevan10017 Assigned!
Make sure to attach before & after screenshots in your PR. Also, star the repo before working on it. While creating your PR, ensure you pull all existing changes beforehand to avoid conflicts.
Happy open-source contributing!

**Comment by jeevan10017** [comment]
@anuragverma108  I have created a Pull request(#935) last Sunday for another Issue, Not yet reviewed. Does it get any conflicts if I create another Pull request before it merges?

**Comment by apu52** [comment]
> @anuragverma108 I have created a Pull request(#935) last Sunday for another Issue, Not yet reviewed. Does it get any conflicts if I create another Pull request before it merges?

I have merged your previous PR . So u can freely now make a new PR.  Extremely Sorry for the delay
