### ISSUE TITLE
[Feature Request]: Account Creation and Database Setup for Medication Schedule Website

### ISSUE THREAD

**Issue by gayatri-p786** [apu52/METAVERSE#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current website is static with non-functional buttons. To enhance user interaction and provide personalized services, we propose implementing account creation (login and sign-up functionality) and setting up a basic database schema for storing user data and medication schedules.

### Proposed Features

**Account Creation:**

- **Sign-Up:** Users can create a new account using their email and a password. Additionally, allow users to sign up using Google authentication.
- **Login:** Users can log in using their registered email and password or via Google authentication.
- **Session Management:** Implement session management to keep users logged in across different pages during their session.

**Database Setup:**

- **User Schema:** Store user information such as user ID, email, password (hashed), display name, and sign-up method (email/password or Google).
- **Medication Schedule Schema:** Store medication schedules for each user, including medication name, dosage, frequency, and reminders.

Implementing account creation and database setup will transition the website from a static site to a dynamic web application, significantly improving its utility and user engagement.

### Use Case

- **User Onboarding:** Allow new users to sign up and create accounts, enabling personalized experiences.
- **User Authentication:** Provide secure login functionality to access personalized data and manage medication schedules.
- **Data Persistence:** Ensure user data and medication schedules are stored securely and can be retrieved upon subsequent logins.

### Benefits

- **Enhanced User Experience:** Users can create accounts and access their medication schedules, improving the overall usability and functionality of the website.
- **Personalized Services:** With user accounts, personalized medication schedules and reminders can be implemented, increasing user engagement and adherence to medication plans.
- **Foundation for Future Features:** Establishing a robust authentication system and database schema lays the groundwork for future features such as sharing schedules with healthcare providers, integrating with other health apps, and more.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@gayatri-p786 u are assigned. u can start working on it

**Comment by gayatri-p786** [comment]
Thanks @apu52!  I'll get started on this.
