### ISSUE TITLE
[Documentation Update]:  Add project task reminder 

### ISSUE THREAD

**Issue by ananyag309** [apu52/METAVERSE#959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Add project task manager 
Tech Stack

- **HTML**: Structure and content.
- **CSS**: Styling and layout.
- **JavaScript**: Logic and interaction.
- **LocalStorage**: Persistent data storage in the browser.

### Suggested Change

# Features

- **Task Management**: Add, edit, and delete tasks.
- **Due Date and Time**: Set deadlines with date and time pickers.
- **Priority Levels**: Assign priority (Low, Medium, High) to tasks.
- **Persistent Storage**: Tasks are saved in local storage for persistence.
- **Responsive Design**: User-friendly interface optimized for various screen sizes.

### Rationale

contribute under SSOC'24

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ananyag309 adding a new project is not a valid contribution in this repo . so sorry to close this issue . U can still make new issues on which u want to work on by going through all the rules mentioned in CONTRIBUTING.md file
