### ISSUE TITLE
Enhance Age calculator 

### ISSUE THREAD

**Issue by ananyag309** [apu52/METAVERSE#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i am willing to enhance age calculator under ssoc

### Use Case

I will enhace css and functioning 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ananyag309 which features u want to add/enhance in the age calculator??
