### ISSUE TITLE
[Feature Request]: Adding hover effects

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add hover effect to the footer links of the food website.

### Use Case

This improves the interactivity of the website with the user

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ebe772f1-6362-4acd-8afd-1e5e5633648a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@chaanakyaaM you may start working
