### ISSUE TITLE
[Feature Request]: Add scroll down progress bar.

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/METAVERSE#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Description: I would like to add a website progress indicator bar to book review website.

### Use Case

Uses: it helps users to show how far the website has been scrolled and helps the website UI more attractive.

### Benefits

Benefits: improves the overall website's UI and make it look professional.

### Add ScreenShots

Like this:
![Screenshot (345)](https://github.com/user-attachments/assets/5cf178cc-8363-4e66-9ac8-fa61c03ce055)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@chaanakyaaM you can start working on this
