### ISSUE TITLE
[Feature Request]: Re-Create Cursor Trail effect to Improve UI/UX

### ISSUE THREAD

**Issue by MastanSayyad** [apu52/METAVERSE#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @apu52 and @heysagnik 

The current cursor animation looks laggy and odd instead I would like add a trail effect to look more interactive, engaging and improve UI/UX, I will ensure to match it to the website design theme

Like this:

https://github.com/user-attachments/assets/841dd647-f990-43c9-b317-2cff2f3f54d1

### Use Case

Increase Users engagement and User experience 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@MastanSayyad you can start working
