### ISSUE TITLE
[Bug]: extra toggle when screen size is small 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when screen size is reduce in about us page an extra toggle appears

### Expected behavior

there should be only one toggle for changing into dark mode . 

### Add ScreenShots

https://github.com/user-attachments/assets/c3b90d34-247f-4abf-8cb9-4c6b742be585

![Screenshot 2024-07-13 194103](https://github.com/user-attachments/assets/1a77b7df-12ea-4ab1-abb4-546e4e62baff)

- in this image below in light mode r1 ,r2 , r3 is written i will remove that also . 
![image](https://github.com/user-attachments/assets/98df07f0-8bda-4908-bff6-d9dd1d94c670)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@heysagnik @anuragverma108 please assign me this issue under gssoc labels

**Comment by heysagnik** [comment]
@ANKeshri You may start working on this
