### ISSUE TITLE
[Feature Request]: Add hcf calculator 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

a calculator to find hcf of two numbers .

### Use Case

we can find hcf of 2 numbers 

### Benefits

we can find hcf of 2 numbers 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7bf5eb38-0915-4d7e-a424-02adb9f214bb)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@heysagnik @apu52 @anuragverma108 please assign me this issue

**Comment by heysagnik** [comment]
@ANKeshri you can't add new projects, rather contribute to existing projects

**Comment by ANKeshri** [comment]
> @ANKeshri you can't add new projects, rather contribute to existing projects

sure thank you
