### ISSUE TITLE
[Feature Request]: Send mail after membership sub of Netflix

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [apu52/METAVERSE#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to implement a mail sending feature in the Netflix clone project. When the user enters their email address in the field and clicks "Get Started", the user receives a confirmation mail of their membership subscription as a immediate feedback. This will improve the user experience.

### Use Case

Implementing the mail sending feature enhances the Netflix clone project by offering immediate feedback to users upon entering their email and clicking "Get Started." This instant confirmation email reassures users of their successful membership subscription, enhancing trust and improving overall user experience. The feature ensures clear communication, making the onboarding process seamless and engaging for new subscribers.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Ayesha-Siddiqua88 under which particular open source programme do u want to contribute??

**Comment by Ayesha-Siddiqua88** [comment]
GSSoC'24

**Comment by apu52** [comment]
@Ayesha-Siddiqua88 u are assigned
