### ISSUE TITLE
[Feature Request]: Add a contack us form for the contact us page .

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

a contact us form for contact us page

### Use Case

if someone want to contact they can fill the form 

### Benefits

make interaction 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ae2c2673-a794-4e02-aaee-9d070c793cf4)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ANKeshri u are assigned
