### ISSUE TITLE
[Bug]: Bugs in TicTacToe Game

### ISSUE THREAD

**Issue by abckhush** [apu52/METAVERSE#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. No draw condition
2. A person can still play on the remaining boxes.a person can still play on the remaining boxes even after winning

### Expected behavior

1. Draw condition should be specified, enhancing the UX.
2. After winning, boxes should be disabled till reset button is clicked,

### Add ScreenShots

Bug1:
![image](https://github.com/user-attachments/assets/5c124170-38fb-462a-ab2d-34f5c2c79274)

Bug2:
![image](https://github.com/user-attachments/assets/4f6e7eb7-40e5-45c7-a58e-9b8b77f736d7)
![image](https://github.com/user-attachments/assets/4e4e9d34-dbd0-4118-9cb4-38828e970780)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@abckhush u are assigned
