### ISSUE TITLE
[Feature Request]:  Add features to the Restaurant Website

### ISSUE THREAD

**Issue by abckhush** [apu52/METAVERSE#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It is a single-page website right now with no functionality. The feature I would like to add is: Menu
By clicking on the photos shown in the ss, they can go to deserts, snacks, beverages, veg, non-veg and much more.

### Use Case

It would enhance the UX as well as add functionality to the page.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5912d1dd-3992-46ef-9793-31243e520c65)
![image](https://github.com/user-attachments/assets/a18e3b69-0462-4146-b1a4-437ce07f8dea)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@abckhush u are assigned . But I want to request u to please complete the previous assigned issue & then only work on this issue
