### ISSUE TITLE
[Feature Request]: Add "Frequently Asked Questions" section in Netflix Clone

### ISSUE THREAD

**Issue by kanishashah5** [apu52/METAVERSE#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

>  The "FAQ" section is currently not functional. 
> Adding this will provide visitors with more information about Netflix website and enhance their understanding.

### Use Case

Making it functional will:
Help visitors with detailed information about the website including its subscription cost and related stuff.

### Benefits

Improves user experience by providing information.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@kanishashah5 u are assigned
