### ISSUE TITLE
[Feature Request]: Improve UI of Travel Website

### ISSUE THREAD

**Issue by Sanglap-Halder** [apu52/METAVERSE#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will change the UI of the Travel Website

### Use Case

With a good UI it will look more attractive

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Sanglap-Halder what UI changes u want to add in the travel_website ?? can u please provide some details

**Comment by Sanglap-Halder** [comment]
@apu52 I have made a few improvements in UI. You can review these ---

https://github.com/user-attachments/assets/9f9ef147-590a-4795-8992-d8b1e88e3528

If you want something more then I will add that feature also.

**Comment by apu52** [comment]
> @apu52 I have made a few improvements in UI. You can review these ---
> 
>  Untitled.video.-.Made.with.Clipchamp.mp4 
> If you want something more then I will add that feature also.

looking really good .I am assigning you .push the changes

**Comment by Sanglap-Halder** [comment]
I pushed the changes please checkout my new PR
