### ISSUE TITLE
[Feature Request]: make a menu page in Bakery website .

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

there will be menu page available for bakery website

### Use Case

users can see what are the items available to eat .

### Benefits

users can see what are the items available to eat .

### Add ScreenShots

https://github.com/user-attachments/assets/a2425dc6-05b4-423c-a524-8fcdc8921d12

sample : 
![image](https://github.com/user-attachments/assets/7b2c6234-ff2c-4d69-88d1-dc7fca654993)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@heysagnik @apu52 please assign me this issue

**Comment by apu52** [comment]
@ANKeshri u are assigned .but I want to suggest u to please complete the previously assigned issue & only after the successful submission of the previously assigned issue work on this

**Comment by ANKeshri** [comment]
> @ANKeshri u are assigned .but I want to suggest u to please complete the previously assigned issue & only after the successful submission of the previously assigned issue work on this

@apu52 sure sir
