### ISSUE TITLE
[Feature Request]: I want to add footer in "hackathons" website

### ISSUE THREAD

**Issue by Maana-Ajmera** [apu52/METAVERSE#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently there is no footer in "Hackathons" website , I want to add footer to it

### Use Case

Footer helps to add a complete look to a website and adds to the uI of the webpage

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2d650746-0147-4171-81fe-2fe0ad0317a5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Maana-Ajmera** [comment]
@heysagnik @apu52 Please assign it to me

**Comment by apu52** [comment]
@Maana-Ajmera u are assigned
