### ISSUE TITLE
[Feature Request]: Enhancing login signup page in myntra clone

### ISSUE THREAD

**Issue by Maana-Ajmera** [apu52/METAVERSE#988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Earlier , the login/signup page of myntra is not good

### Use Case

It would help in better UI

### Add ScreenShots

Before:
![image](https://github.com/user-attachments/assets/509e28f8-e4bb-411a-b04f-bd8d3a47773d)

After:
![image](https://github.com/user-attachments/assets/4979e170-e502-4b7a-8302-bd918047bba0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Maana-Ajmera** [comment]
@heysagnik @apu52 Please assign it

**Comment by apu52** [comment]
@Maana-Ajmera I have assigned u .but first please try to complete previously assigned issue
