### ISSUE TITLE
[Feature Request]: amazon clone changes 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/METAVERSE#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

want tp add country and google translator in amazon clone 

### Use Case

want tp add country and google translator in amazon clone 

### Benefits

want tp add country and google translator in amazon clone 

### Add ScreenShots

clone : 

![Screenshot 2024-07-16 114902](https://github.com/user-attachments/assets/60260af5-77d1-4213-a4ee-d17e0facfd6e)

real website 

![Screenshot 2024-07-16 114908](https://github.com/user-attachments/assets/2865bca7-a5e3-4c82-b915-e655ad916e11)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ANKeshri  I have assigned u .but first please try to complete previously assigned issue

**Comment by ANKeshri** [comment]
> @ANKeshri I have assigned u .but first please try to complete previously assigned issue

I have completed can you please review them
