### ISSUE TITLE
Documentation Update Correct Markdown Usage in Readme.md

### ISSUE THREAD

**Issue by Zoha-Waheed** [apu52/METAVERSE#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The image tag inside HTML is not required in Markdown. 

### Suggested Change

By uisng only Markdown Syntax can improve the whole documentation part.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Zoha-Waheed** [comment]
Assign this issue to me as a GSsoc '24 Contributor.

**Comment by apu52** [comment]
@Zoha-Waheed u are assigned

**Comment by Zoha-Waheed** [comment]
> @Zoha-Waheed u are assigned

Thanks for it.
Coming with PR soon.

**Comment by Zoha-Waheed** [comment]
> @Zoha-Waheed u are assigned

PR sent, please merge it.

(Assignee and label must)
