### ISSUE TITLE
[Documentation Update]: Adding TOC in documentation

### ISSUE THREAD

**Issue by Zoha-Waheed** [apu52/METAVERSE#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The current README file lacks a Table of Contents (ToC), making it difficult for users to quickly navigate through the document and find relevant sections. This can be especially problematic for users who are new to the repository and want to understand its structure and content efficiently.

### Suggested Change

To improve the usability and navigation of the README file, we should add a Table of Contents. This ToC will provide a structured overview of the document's sections, allowing users to jump directly to the parts they are interested in. The ToC will be placed right after the introduction section for optimal visibility.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by Zoha-Waheed** [comment]
Please assign this issue to me as a GSsoc '24 Contributor

**Comment by apu52** [comment]
@Zoha-Waheed I have assigned u .But please try to complete previously assigned issue

**Comment by Zoha-Waheed** [comment]
> @Zoha-Waheed I have assigned u .But please try to complete previously assigned issue

No worries.
On it.

**Comment by Zoha-Waheed** [comment]
> @Zoha-Waheed I have assigned u .But please try to complete previously assigned issue

Please merge these PR,  other PRs are cooking :)
