### ISSUE TITLE
[Documentation Update]: Lack of Detailed Setup Instructions

### ISSUE THREAD

**Issue by Zoha-Waheed** [apu52/METAVERSE#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The README file currently lacks detailed instructions on how to set up the project locally. Without clear guidance on prerequisites, cloning the repository, installing dependencies, and running the project, new contributors and users might find it challenging to get started.

### Suggested Change

To make the onboarding process smoother and more accessible, we need to include a detailed section on how to set up the project locally. This section will cover all the necessary steps from prerequisites to running the project, ensuring users have all the information they need to start contributing or using the project.

Assign this issue to me as a GSsoc '24 Contributor.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Zoha-Waheed I have assigned u previously 2 issues. So please try to complete previous 2 issues at first & please don't raise more than 2 issues at a time. After completing previously assigned issues ping me here .Then I will assign u

**Comment by Zoha-Waheed** [comment]
> @Zoha-Waheed I have assigned u previously 2 issues. So please try to complete previous 2 issues at first & please don't raise more than 2 issues at a time. After completing previously assigned issues ping me here .Then I will assign u

Much obliged.
will sure follow the timelne.
