### ISSUE TITLE
[Documentation Update]: Inconsistent Color Scheme and Typography

### ISSUE THREAD

**Issue by Zoha-Waheed** [apu52/METAVERSE#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The current README file may have inconsistencies in its color scheme and typography, which can affect the readability and visual appeal of the document. A consistent color scheme and typography ensure a professional look and improve user experience.

### Suggested Change

To ensure a consistent and professional appearance, we need to standardize the color scheme and typography throughout the README file. This includes using a uniform font style, size, and color for headings, subheadings, and other text elements.

Assign this issue to me as a GSSOC '24 contributor.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by heysagnik** [comment]
@apu52 kindly check if this is needed

**Comment by Zoha-Waheed** [comment]
> @Zoha-Waheed I have assigned u previously 2 issues. So please try to complete previous 2 issues at first & please don't raise more than 2 issues at a time. After completing previously assigned issues ping me here .Then I will assign u

I have submitted PR of previous issues, please assign other pending issues.
Gracias.
